### ISSUE TITLE
Better LAG support

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#126]
At the moment, there is no support for handling LAGs at an interface level.  LAGs only work on kit that doesn't use pseudointerfaces for the ethernet bundle.

This improvement will touch several areas of the code, including back-end SQL queries, some front-end stuff, l2database and possibly also graphing code.

**Comment by fooelisa** [comment]
Submitted https://github.com/inex/IXP-Manager/pull/199 
This fixes p2p stats on LAGs with MACs behind the logical interface for me.

**Comment by nickhilliard** [comment]
confirmed working on arista kit.  Should also be fine on Dell/Cisco.
