### ISSUE TITLE
"Hidden" contact group type / extract improvement

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#128]
Is it possible to have a contact group that users cannot see, just for admin purposes only i.e. it only appears to the IXP Admin superusers for flagging particular campaigns / mailing lists etc.

Also is it possible to add to the cli extract routine to select if there's an associated user login and what type of user to select.

Currently have to do something pretty clunky like this:

/srv/ixp/bin/ixptool.php -a cli.cli-export-group -p name=technical,format=csv | grep -v "Admin Account" | grep -vi noc@ | grep -iv support@ |  grep -iv peering@

To generate an e-mail contact list of actual humans and not NOCs and admin accounts.

I'd like to do an occasional exercise to flag the non-humans, or people that we never want to e-mail with a contact group.

Also it seems to extract all contacts regardless of the member account status. A way to select by customer status would make this usable as at the moment we connect directly to the database to get the contacts we want with specific queries.

So I want to do something from a script like:

"extract all the technical and admin contacts that are not member superuser, for currently active members, that are not flagged "don't mail"" (e.g. they are likely to be human contacts!)

So we can e-mail them about specific activity/events.

**Comment by barryo** [comment]
Closing as this seems to stretch more deeply into CRM functionality which will not happen pre-v4 and should be discussed if still desired in a more formal manner post v4.
