### ISSUE TITLE
Add port media types in DB / Interface

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#130]
Would be very useful if we could see / use the switchport media type in the interface (so, members can see what type of port they have, and also we can use this in the DB.)

Our other scripts use MAU-MIB / CISCO-MAU-CAPABILITY to get this information from the switches about the optic / port type for each port.
.1.3.6.1.2.1.26.2.1.1.3

This returns a type code, of which the most interesting are:

                      "0"  => "",
                   "0.0" => "",
                   "10" => "10BaseTHD",
                   "11" => "10BaseTFD" ,
                   "15" => "100BaseTXHD",
                   "16" => "100BaseTXFD",
                   "17" => "100BaseFXHD",
                   "18" => "100BaseFXFD",
                   "21" => "1000BaseXHD",
                   "22" => "1000BaseXFD",
                   "23" => "1000BaseLXHD",
                   "24" => "1000BaseLXFD",
                   "25" => "1000BaseSXHD",
                   "26" => "1000BaseSXFD",
                   "27" => "1000BaseCXHD",
                   "28" => "1000BaseCXFD",
                   "29" => "1000BaseTHD",
                   "30" => "1000BaseTFD",
                   "31" => "10GigBaseX",
                   "32" => "10GigBaseLX4",
                   "33" => "10GigBaseR",
                   "34" => "10GigBaseER",
                   "35" => "10GigBaseLR",
                   "36" => "10GigBaseSR",
                   "37" => "10GigBaseW",
                   "38" => "10GigBaseEW",
                   "39" => "10GigBaseLW",
                   "40" => "10GigBaseSW"

**Comment by bcix** [comment]
Hi,

we also have 10G DWDM 40km (ER) and 80km (ZR) optics inside our switches.
Of course, and for as CWDM as well, each transceiver has its own wavelength (e.g. CH22, CH23 ...) ,
better described as ITU Channel http://www.flexoptix.net/en/dwdm-channels/
  
We also tend to use the 40G and 100G ports in our networks gear, soon.
For the 100G ports in our Arista 7500E Switches, we are have the following optic
types for now:

100GBASE-XSR10 
100GBASE-LR4
100GBASE-ER4


Good page for the current Arista 40G/100G interface types:

https://www.arista.com/en/products/transceivers-cables

**Comment by barryo** [comment]
@bcix - I'm fairly certain that we're not going to go down the road of hard coding optic types. We'll just read them as per @listerr 's example in the issue description above.

**Comment by barryo** [comment]
Now implemented in v3.7.2 - https://github.com/inex/IXP-Manager/releases/tag/v3.7.2

Note that media discover is based purely on the IANA MAU MIB. As such, only supported types are discovered.

Non-IANA MAU data such as wavelength, light levels, etc are not part of this.
