### ISSUE TITLE
Upgrade detection

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#134]
upgrades are catching people out due to db schema changes.  Can we store the ixp manager version number statically in the database and run a check any time an admin logs in, so that if they're different, it will pop up a warning that there's a mismatch.  If we could extend this to submodules, that would be even better.  The overhead on this should be low if the data is stored in memcache.

**Comment by barryo** [comment]
Closing as composer and hooks are a part of core v4 development.
