### ISSUE TITLE
Live Port States with SNMP Poll breaks with Brocade FCX

### ISSUE THREAD

**Issue by bcix** [inex/IXP-Manager#149]
Hey,

just try to add another Brocade FCX-Switch to IXP-Manager (/ixp/switch-port/op-status/switch/)
When I try to use Live Port States with SNMP Poll I just receive a blank white page.

When I contact the switch from the IXP Manager Server with ```snmpstatus```, 
there's no problem in connecting the switch via SNMP. 

The IXP-Manager logfile only shows only: 
```2014-04-15T19:51:14+02:00 DEBUG (7) [myip]: Logger instantiated```

but not the expected 

```[switchname] Updating SerialNumber from  to (not implemented)```

Any hints on this ?

Thanks, Thorleif

**Comment by bcix** [comment]
Also requested here: https://github.com/opensolutions/OSS_SNMP/issues/12

**Comment by barryo** [comment]
Brocade FCX - detected fine, see comments in opensolutions/OSS_SNMP@e379724d1159795b310df4f368bbd18086a09f0a

**Comment by barryo** [comment]
Brocade RX8 - detected fine, see comments in opensolutions/OSS_SNMP@e8f44b892f181da7b893ff50aec5ef94e13490f1

**Comment by barryo** [comment]
Dell Force10 - just added, see opensolutions/OSS_SNMP@cbf7bef022a08b2efc71664726faefbd815d2f3f

@bcix - to be of use, you need to add a vendor for this. You can do it in the UI or just execute the following:

```sql
INSERT INTO `vendor` VALUES ( 0, 'Dell Force10', 'DellForce10', 'dell_force10' );
```

To test, you'll need to bring OSS_SNMP up to master:

```sh
cd library/OSS_SNMP.git/
git pull
git checkout master
git pull
```
