### ISSUE TITLE
Prefix history management in database

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#152]
At the moment, all announced prefixes are deleted after 7 days (non configurable).  This should be made configurable or ∞, depending on whether the operator wants to have a full prefix announcement history or not.

**Comment by barryo** [comment]
@nickhilliard - does this relate to [compare-route-server-prefixes.pl](https://github.com/inex/IXP-Manager/blob/master/tools/runtime/route-servers/compare-route-server-prefixes.pl)? In the current version I don't see any `DELETE`'s with a reference to 7 days?

**Comment by barryo** [comment]
Also @listerr asks:
> there seems to be an issue with the rs prefix analysis never
> deleting prefixes when the member stops announcing it to the route
> server, it's still showing as "Advertised and Accepted".

**Comment by listerr** [comment]
Doesn't seem to work on our system and we have some members complaining that there are prefixes still there that they are no longer announcing. Any chance of fixing the script?

**Comment by barryo** [comment]
Everything related to this was reworking in v5.0.0.
