### ISSUE TITLE
Customer users don't see OOB access tab (which superuser does)

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#167]
When viewing a customer as superuser there is an OOB tab showing terminal-server access info, but when the customer logs in they don't see it. It only has info like terminal-server name, address and port, so it seems OK (and appropriate) for the customer to see it too. At the moment we are having to manually add the info as notes to the customers, and that seems like duplicated effort.

**Comment by barryo** [comment]
Timing out this as it's not on INEX's list and no +1's since 2014.
