### ISSUE TITLE
Lots of sess_ files in /srv/ixp/var/session

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#170]
Just backing up the ixp directory prior to attempting an upgrade.

root@beta:/srv/ixp/var/session# ls -c1 | wc -l
147122

It would seem apparent that something isn't cleaning up after itself. There are lots of files being left behind like:

-rw------- 1 www-data www-data   41 Oct 14 22:17 sess_vvtgjvv7c3ajqsnqa78fooce31
-rw------- 1 www-data www-data   41 Jan 11  2014 sess_vvtloft3p20292hmafksvst3q3
-rw------- 1 list     www-data   41 Oct 11  2013 sess_vvtm76al5vg8dumgs2tuho2bo2
-rw------- 1 www-data www-data   41 Jun 15 21:40 sess_vvualqbog80usf8t9vktb4r8c1
-rw------- 1 root     root       41 Jun 29 00:40 sess_vvuea07p1t7evk20f87686gpv6
-rw------- 1 www-data www-data   41 Jul 12 12:17 sess_vvujnvvb5g9nbqr9etdoh9tqa3
-rw------- 1 list     www-data   41 Nov 17  2013 sess_vvv1iv2b13fd3pmb7desrea232
-rw------- 1 www-data www-data   41 Feb  8  2014 sess_vvv3psotlgop5rql7m1mmhr1i3
-rw------- 1 list     list       41 Jun 16 06:20 sess_vvv6oll8nmj9p1gkta5kgjdd57
-rw------- 1 www-data www-data   41 Jul 20 23:35 sess_vvvjikviikin92112k270qq6u1
-rw------- 1 www-data www-data   41 Dec 21  2013 sess_vvvo9j7n7qbdl36ej9m6vaivt7
-rw------- 1 www-data www-data   41 Aug  2 06:47 sess_vvvp2ntoat46f07sfc5d9f0km6

All contains string like:

Application|a:1:{s:11:"initialized";b:1;}

**Comment by barryo** [comment]
@listerr - this was an issue specific to your install. Garbage collection probability was set to 0 in `/etc/php5/apache2/php.ini`:

    session.gc_probability = 0

This disables GC. I've reset to the default of 1 which, along with `session.gc_divisor = 1000`, means GC will run every 1,000 session initialisations on average.
