### ISSUE TITLE
Discards not graphed on Extreme XOS platforms

### ISSUE THREAD

**Issue by will-h** [inex/IXP-Manager#171]
On Extreme, discards due to congestion are not counted in the ifMIB/ifOutDiscards OIDs.
So we need an option to graph extremeCongDropPkts - .1.3.6.1.4.1.1916.1.4.14.1.1 as well as / instead of ifOutDiscards on this platforms.

**Comment by barryo** [comment]
Via skinning / templating, there's actually a very easy way to implement this without worrying about the backend which is relatilvely frozen until post v4.

See the above commit. @will-h this assumes we just need to graph extremeCongDropPkts for *discards out*?

**Comment by will-h** [comment]
Works for physical ports, just needs the mrtg config changing so the aggregate/lag graphs are the sums of the  extremeCongDropPkts not ifOutDiscards
