### ISSUE TITLE
LAGs incorrectly numbered in interface

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#192]
If a customer has more than one LAG (for example 2 x 2 x 1GE LAGs) the interface doesn't number the ports correctly:

First LAG displays:

Port 1 of 2 in LAG
Port 2 of 2 in LAG

Second LAG displays:

Port 3 of 2 in LAG
Port 4 of 2 in LAG

**Comment by rowanthorpe** [comment]
This also came up as one of two points in #156 but I think only one of the points was addressed when it was resolved - so I add that link just for some context. Now I consider it though, the wording is perhaps not really "incorrect". Try mentally parsing it not as:

* [1 of 2] in LAG
* [2 of 2] in LAG
* [3 of 2] in LAG
* [4 of 2] in LAG

but as:

* 1 of [2 in LAG]
* 2 of [2 in LAG]
* 3 of [2 in LAG]
* 4 of [2 in LAG]

Perhaps even better would be:

* Port 1 of "LAG 1 with 2 ports"
* ...
* Port 7 of "LAG 3 with 3 ports"
* Port 8

(here port 8 is not part of a LAG)

or even:

* Port 1 => LAG 1, Port 1 of 2
* ...
* Port 7 => LAG 3, Port 3 of 3
* Port 8

**Comment by listerr** [comment]
Errr.. Huh?

Confusing!

It's probably just badly phrased then.

R.


On Mon, Mar 02 at 12:28:09 PM, Rowan Thorpe wrote:

> This also came up as one of two points in #156but I think only one of
> the points was addressed when it was resolved - so I add that link
> just for some context. Now I consider it though, the wording is
> perhaps not really "incorrect". Try mentally parsing it not as:
>  [1 of 2] in LAG [2 of 2] in LAG [3 of 2] in LAG [4 of 2] in LAG 
> but as:
>  1 of [2 in LAG] 2 of [2 in LAG] 3 of [2 in LAG] 4 of [2 in LAG] 
> Perhaps even better would be:
>  Port 1 of "LAG 1 with 2 ports" ... Port 7 of "LAG 3 with 3 ports" Port 8
> (here port 8 is not part of a LAG)
> or even:
>  Port 1 => LAG 1, Port 1 of 2 ... Port 7 => LAG 3, Port 3 of 3 Port 8 
> —
> Reply to this email directly or view it on GitHub.



--
Rob Lister
rob@lonap.net
LONAP Ltd

**Comment by barryo** [comment]
@rowanthorpe - I'm mirroring @listerr 's confusion here :wink:

The interfaces are clearly delimited by *Connection n* so the fix is just to reset the counter.
