### ISSUE TITLE
Arista Switch brings MRTG errors

### ISSUE THREAD

**Issue by bcix** [inex/IXP-Manager#198]
Hi,

after adding an Arista 7504E to IXP-Manager, the MRTG scripts are throwing errors:

ixptool.php -a statistics-cli.gen-mrtg-conf
```
PHP Notice:  Undefined index: bits in /ixp/var/templates_c/e93fa05ddf4bf00c3d37c125aacb4a509e8d923c.file.switch-aggregates.cfg.php on line 81
PHP Warning:  implode(): Invalid arguments passed in /ixp/var/templates_c/e93fa05ddf4bf00c3d37c125aacb4a509e8d923c.file.switch-aggregates.cfg.php on line 81
PHP Notice:  Undefined index: pkts in /ixp/var/templates_c/e93fa05ddf4bf00c3d37c125aacb4a509e8d923c.file.switch-aggregates.cfg.php on line 81
PHP Warning:  implode(): Invalid arguments passed in /ixp/var/templates_c/e93fa05ddf4bf00c3d37c125aacb4a509e8d923c.file.switch-aggregates.cfg.php on line 81
```

and in the generated mrtg.conf:

```ERROR: CFG Error in "maxbytes[switch-aggregate-core-n15-bits]", file ixpmanager.cfg line 394: 0 must be a Number bigger than 0```

Generated mrtg conf segment:

```
#####################################################################################################################    
#
# core-n15 Bits traffic
#


Target[switch-aggregate-core-n15-bits]: 
MaxBytes[switch-aggregate-core-n15-bits]: 0
Title[switch-aggregate-core-n15-bits]:    BCIX - Peering Bits / second on core-n15
Options[switch-aggregate-core-n15-bits]:  growright,bits
YLegend[switch-aggregate-core-n15-bits]:  Bits / Second
Directory[switch-aggregate-core-n15-bits]: switches

            
    
#####################################################################################################################    
#
# core-n15 Packets traffic
#


Target[switch-aggregate-core-n15-pkts]: 
MaxBytes[switch-aggregate-core-n15-pkts]: 0
Title[switch-aggregate-core-n15-pkts]:    BCIX - Peering Packets / second on core-n15
Options[switch-aggregate-core-n15-pkts]:  growright
YLegend[switch-aggregate-core-n15-pkts]:  Packets / Second
Directory[switch-aggregate-core-n15-pkts]: switches
```

**Comment by bcix** [comment]
Not sure, but it looks like  IXP Manager V3.7.2 brings some other MRTG config file generation issues.

After removal of the arista switch and generating a new mrtg.conf, our total graph looks wrong, 
http://www.bcix.de/bcix/traffic/ as well as some member port graph looks wrong now, as well. 

Have too look into it in more detail.

**Comment by barryo** [comment]
@bcix - are you sure it's since v3.7.2? The [mrtg config files](https://github.com/inex/IXP-Manager/tree/master/application/views/statistics-cli/mrtg) have not changed in months.

If you take out your new switch, does it revert to normal behaviour?

**Comment by bcix** [comment]
Hi,

what I changed last night: 

* Upgrade to v3.7.2
* adding a cronjob for ixptool.php -a switch-cli.snmp-poll 
* adding the Arista Switch

The mrtg conf cronjob runs every morning, I saw wrong graphs this morning and removed the arista switch from IXP-Manager.

Now I have wrong graphs. 

I lookd at the switch with the fewest connected member ports now:

What If found now, that the two member port on  the force10 port te 0/0
has no more graph and IXP-Manager says it's now on port 0/1, which is an unsed port ?? 
 The same for the second member port. its connected to te 0/2 but XPM-Manager now says it's on te 0/3
and the graph is empty.

Could this be  related to the new cronjob "ixptool.php -a switch-cli.snmp-poll "
and this moves the ports +1 ? Have to check other switches as well.

**Comment by barryo** [comment]
Hi @bcix. You've stumbled onto the answer:

> This switch was replaced during holidays as the old one crashed. The new one has a newer firmware and as I far as I remember, the release notes are saying, that the SNMP interface IDs were renumbered with a certain firmware version during the firmware upgrade.

IXP Manager matches interfaces on the switch to interfaces in the database based on the ifIndex. If the ifIndex changes on an existing port then two things happen:

* the old port in the database with the now non-existent ifIndex gets marked as a *DB Only* port. This is highlighted in the UI as this is clearly an inconsistency.
* the new port gets added to the database.

So, now you need to manually bring this into a consistent state. You can do this my updating the individual member ports and then deleting the db only ports. You may also be able to craft a MySQL statement to remove all the new ones, and then update the ifIndex on the old ones. E.g.:

```sql
DELETE FROM switchport WHERE ifIndex > X AND ifIndex < Y AND switchid = Z;
UPDATE switchport SET ifIndex = ifIndex + N WHERE switchid = y;
```

**Comment by bcix** [comment]
Hi Barry,

thanks for the good tips and the SQL. As the offset "N" was different between the port types (e.g. te / fortyGigE and ma) it was quite a lot work to get everything fixed.  

Still open, if the title of this isuue: "mrtg and Arista" will work, now...? It thinks this is something related with issue  https://github.com/inex/IXP-Manager/issues/197 , as well?

Spent to much time into fixing the ifIndex issue, can only spend time for Arista integration testing later.

**Comment by barryo** [comment]
Hi @bcix - glad it all got sorted :+1: 

Re #197 - that's in the master branch now. I may try and address it along with opensolutions/OSS_SNMP#11
