### ISSUE TITLE
Discrepancy between Release Notes and Doctrine Schema Validation

### ISSUE THREAD

**Issue by kosfar** [inex/IXP-Manager#205]
Hi,
while upgrading to 3.7.0, the Release notes instruct us to:
ALTER TABLE vlan  ADD peering_matrix TINYINT(1) NOT NULL DEFAULT 0,  ADD peering_manager TINYINT(1) NOT NULL DEFAULT 0;

We added the extra columns, restarted memcached but after doing "bin/doctrine2-cli.php orm:validate-schema" it kept complaining about the database schema not being in sync with the mapping files and asking to execute: 
ALTER TABLE vlan CHANGE peering_matrix peering_matrix TINYINT(1) NOT NULL, CHANGE peering_manager peering_manager TINYINT(1) NOT NULL

After executing the above query doctrine validation succedeed. I suppose that this is at least a small bug in Release Notes.

Regards

**Comment by barryo** [comment]
The issue here is that the ORM Designer tool we are using (Skipper) did not previously support default values.

You should now run something like:

```sql
UPDATE vlan SET peering_matrix = 0, peering_manager = 0;
```
