### ISSUE TITLE
"Undefined index: sid" message while trying to view switch ports via SNMP

### ISSUE THREAD

**Issue by rm1984** [inex/IXP-Manager#207]
Hello,

I found a strange misbehavior concerning switch ports.

In my infrastructure, I use automatic switch ports discovery via SNMP, and it works fine.
I can see all of my ports by clicking on "Ports (database only)" on the dropdown menu.

But, when I click on "View Live Port States (with SNMP poll)" or "View / Edit Ports (with SNMP poll)", I get a 404 page with the following message:

> Error 404

> Sorry - the page you are looking for cannot be found

> You may have followed a broken link, an outdated search result, or there may be an error on our site. If you typed in a URL, please make sure you have typed it in correctly. In particular, make sure that the URL you typed is all in lower case.

And I get the following message in my Apache error log:

```
[Fri Apr 10 15:29:29.213735 2015] [:error] [pid 11868] PHP Notice:  Undefined index: sid in /tmp/39bc5c97fb6269ca92aac8b916dc46acde3e12cf.file.list-toolbar.phtml.php on line 58, referer: http://MY_IP/ixp/switch/list
[Fri Apr 10 15:29:29.213746 2015] [:error] [pid 11868] PHP Notice:  Trying to get property of non-object in /tmp/39bc5c97fb6269ca92aac8b916dc46acde3e12cf.file.list-toolbar.phtml.php on line 58, referer: http://MY_IP/ixp/switch/list
```

Hope this may be useful (and any hint to solve the problem would be great).

Thanks

**Comment by barryo** [comment]
Hi @rm1984 - does this continue to be an issue for you? I suspect it may have been a memcached issue but, could you:

1. restart memcached and try again?
2. provide exact steps from the login page to replicate?

**Comment by barryo** [comment]
I've tried to replicate this on all switch dropdowns but I cannot - using latest version v3.7.3.

Closing unless the OP can replicate with instructions on v3.7.3.

**Comment by rm1984** [comment]
Hi @barryo,

I restarted memcached but with no success.

The exact steps I take to get the error are:

1) login (as administrator)
2) click on "Switches" on the left-side menu
3) click on "Switch ports" (and then I get the full and right listing of all the ports I got beforehand via SNMP discovery)
4) click on "View Live Port States (with SNMP poll)" (but clicking on "View / Edit Ports (with SNMP poll)" leads to the same result)

furthermore, as soon as I get the error, the URL in the browser's address bar changes to:

`http://MY_IP/ixp/%3Cbr%20/%3E%3Cb%3ENotice%3C/b%3E:%20%20Undefined%20index:%20sid%20in%20%3Cb%3E/usr/local/ixp/var/templates_c/1865212a93df69c916cc247f4b818107e9b7bf76.file.list-toolbar.phtml.php%3C/b%3E%20on%20line%20%3Cb%3E50%3C/b%3E%3Cbr%20/%3E%3Cbr%20/%3E%3Cb%3ENotice%3C/b%3E:%20%20Trying%20to%20get%20property%20of%20non-object%20in%20%3Cb%3E/usr/local/ixp/var/templates_c/1865212a93df69c916cc247f4b818107e9b7bf76.file.list-toolbar.phtml.php%3C/b%3E%20on%20line%20%3Cb%3E50%3C/b%3E%3Cbr%20/%3Ehttp://MY_IP/ixp/switch-port/op-status/switch/`

My version of IXP Manager is the latest from the official GIT repository (updated yesterday), and my switch is a Juniper Networks EX4200-48T.

Thanks again.

**Comment by barryo** [comment]
> 3) click on "Switch ports" (and then I get the full and right listing of all the ports I got beforehand via SNMP discovery)
> 4) click on "View Live Port States (with SNMP poll)" (but clicking on "View / Edit Ports (with SNMP poll)" leads to the same result)

ah! an unintended use of this function :wink:

it needs to be limited to a specific switch before you can use those other options. I'll commit a fix now.
