### ISSUE TITLE
mysql password (and perhaps other sensitive data) emailed in the clear when relevant exception is hit

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#209]
I noticed that some of the exception-emails which arrived when we were experimenting with our staging install were including the mysql-password in the traceback (obviously errors struck by PDOconnection.php usually included this info), and I suspect there are probably one or two other situations where similarly sensitive bits of data get emailed as a consequence of exceptions. In the particular configuration we used this wasn't an issue, but because other people's setups will probably involve one/several of:

 * emails traversing an untrusted network
 * emails traversing untrusted relays
 * emails traversing unencrypted channels between some relays

my inner-paranoic thinks perhaps it is worth trying to redact some sensitive data before sending, just to minimize foot-shooting? or if that seems not worth the investment of time, perhaps a reminder-note in the install-docs to ensure exception-emails don't cross untrusted networks/relays would be useful...

**Comment by barryo** [comment]
Thanks @rowanthorpe - we prefer to be secure by default so have disabled alerts by email in the default configuration.

Note that it would be database connection specific issues that would throw an alert as you mention above. A general SQL query failing would not include connection details.
