### ISSUE TITLE
Quanta Switch

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#210]
Per https://github.com/opensolutions/OSS_SNMP/wiki/Device-Discovery here is the requested information for a Quanta switch.

Quanta LB4M
Software Version	1.0.2.17
Operating System	VxWorks5.5.1

root@Unbound-Indy-1:~# snmpget -c public -On -v 2c 10.250.250.2 .1.3.6.1.2.1.1.1.0
.1.3.6.1.2.1.1.1.0 = STRING: "FASTPATH Switching"

root@Unbound-Indy-1:~# snmpget -c public -On -v 2c 10.250.250.2 .1.3.6.1.2.1.1.2.0
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.4413.1.2.2

root@Unbound-Indy-1:~# snmpget -c public -On -v 2c 10.250.250.2 .1.3.6.1.2.1.47.1.1.1.1.11.1
.1.3.6.1.2.1.47.1.1.1.1.11.1 = STRING: "QTFCPW0350251"

**Comment by barryo** [comment]
@MHammett - that has been added and pushed to master. I'm not particular happy with Quanta's nondescript sysDescr but I guess it is what it is...

**Comment by MHammett** [comment]
@barryo There's lots of things I'm not particularly happy with.  ;-) Hopefully we'll be running Juniper soon.
