### ISSUE TITLE
peeringmacrov6 cannot be updated via the UI

### ISSUE THREAD

**Issue by apolyr** [inex/IXP-Manager#212]
We use IXPmanger in order to produce our route server configuration. However, the v6 config for one of our customers was incorrect. After digging around, I see that in the database there are two different fields for AS-SETs:

  `peeringmacro` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `peeringmacrov6` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,

Indeed the customer has different values in these two fields:

INSERT INTO `cust` VALUES (1,1,1,1,NULL,'Greek Internet Exchange',1,'grix','GR-IX',199399,300,'XX','XX','XX','XX','XX','12x5','http://www.gr-ix.gr','cocolala','AS-GRIX','open','http://www.gr-ix.gr','2014-03-13',NULL,1,1,NULL,'2015-06-11',1,'superuser','2014-03-13','NO',0)

The second value seems to be a leftover; both fields should have the same value.

The peeringmacrov6 field cannot be updated through the UI (we run IXP Manager V3.7.2). The "edit customer details" button opens a page with a single "Peering Macro" field, which only updates the peeringmacro field of the cust table.

**Comment by barryo** [comment]
`peeringmacrov6` is not a leftover but a quick hack for a IXP Manager user who had a member with different v4 and v6 macros. 

The following commit adds the field to the UI.

Note that the IPv4 peering macro is used when there is no v6 macro set. To force no macro for IPv6, set it as AS-NULL. This caveat is including in the frontend.
