### ISSUE TITLE
Euro-IX data non-Latin output, and extra backslashing

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#216]
Having setup euro-ix data output, I am seeing two issues:

 * any non-Latin characters are being output as escaped unicode values, which (may be intentional? but) makes some entries entirely non-grokable by the human eye. Maybe that doesn't matter, as this is primarily for machine-consumption though... e.g. `"name": "\u039d\u03ad\u03b1 \u0395..."`
 * forward-slashes are being backslashed which again (may be intended? but) make things look a bit golf-like... e.g.` "url": "http:\/\/www.grnet.gr"`

If both of those are intentional and the (human) readability aspect is low-enough importance, then feel free to just close this issue as a "feature" rather than a "bug"

**Comment by barryo** [comment]
@nickhilliard - this is your baby but I suspect the above are unintentional and a proposed fix can be merged in above.

**Comment by nickhilliard** [comment]
rfc7158:

section 7: "Any character may be escaped."
section 8.1: "JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default encoding is UTF-8"

while technically correct, the original output is definitely a bit wonky.  This looks a pile better.
