### ISSUE TITLE
Feature-request: to be able to disable AS112 options by config-var

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#217]
I was requested to remove AS112 tickboxes/display from our ixp-manager interface, because for various reasons we have to organise AS112 through other channels - so customers having the tick-boxes/display is confusing (and doesn't work anyway). I managed to make the changes [see this gist for the diff](https://gist.github.com/rowanthorpe/3b6e70704644ef069569) but it required creating 6 skin files.

I guess it wouldn't be hard to instead add a "frontend.." config-var to application.ini, and to put a conditional in place of each omission I made, so just setting the var to "0" is enough to make the options/display disappear. In the skinned-change I deliberately took the least-invasive approach (didn't disable as112 in the controllers, etc), as all we wanted was to avoid visual confusion in the frontend, but if you want to implement the config-approach, you may want to got further down the stack than I did...

**Comment by barryo** [comment]
> I guess it wouldn't be hard to instead add a "frontend.." config-var to application.ini, and to put a conditional in place of each omission I made

I think this is what we'd need as a pull request to make this change:

- new application.ini config option such as `as112_ui_active`
- default templates to use this new option to show / hide as112 elements

**Comment by rowanthorpe** [comment]
@barryo: I've hacked together what you suggest. I will test it tomorrow before PR-ing it.
