### ISSUE TITLE
Smarty-included files are non-relative, breaking encapsulation in skins

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#218]
While working on the changes I mentioned in #217 (see the gist linked there) it took a *long* time to realise why one file I skinned was apparently not overriding the in-tree version. In the end it was not due to caching as I'd suspected, but because I overrode `application/views/customer/overview-tabs/ports/port.phtml`, yet `application/views/customer/overview-tabs/ports.phtml` has the following line:

```
{include file='customer/overview-tabs/ports/port.phtml'}
```

and because I hadn't skinned *that* file it was still including the non-skinned file I thought I had overridden.

Because the included file-path has no leading slash I presumed it was a relative link. In the end (with help from a colleague) I found the include directive prepends "application/views/" to that to get an absolute link, so I had to also skin the ports.html template and hardcode the line to:

```
{include file='_skins/grix/customer/overview-tabs/ports/port.phtml'}
```

If there is any way in Smarty to specify "file-link relative to this template-file" it would be better in general to use that when including templates within templates - to save confusion, and to avoid skinning two files for a change in only one of them.

**Comment by rowanthorpe** [comment]
...to clarify, feel free to interpret "relative" as "relative to this file" or "relative to the base of the configured skinned views, falling back to the base of the non-skinned views", based on what's appropriate. There may be two different ways to skin that cat, based on smarty's limitations (sorry for the bad pun).

**Comment by barryo** [comment]
This is actually much less complex that you think:

`include` is Smarty's built in file inclusion directive; `tmplinclude` is our version which is skinning aware.

:beers:
