### ISSUE TITLE
Remove from mailman list when a contact is deleted

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#22]
When a contact is deleted, delete from mailing list if marked as subscribed via IXP Manager.

This will help us clean the mailing list as users register and delete old contacts etc.

Possibly add option for a list that is only managed via IXP Manager (i.e, if they are not on IXP manager then they aren't added to the list) as we can configure multiple lists in mailman and have umbrella lists or subscribe them to each other, so one can be managed manually and one via IXP Manager.

**Comment by listerr** [comment]
Situation is less than ideal, because I would really like to split the
mailman lists up so it's made of multiple lists:

members@ list which auto-includes the following:

 members-ixpman   - managed via ixpman
 members-mailman  - managed via mailman
 members-post-only - post only list (can post but receives no copies
 managed from ixpman)

We set up this mailman config but were unable to proceed further because
of the IXP manager side of things not really working for us. Members
have been asking us for years that they want an "announce" list which
does not have general discussion but only LONAP announcements.

The problem is that it insists on every subscriber of the list being a
user in IXP manager (not just a contact), and only allows for one e-mail
address per user account. Managing it via IXP manager is somewhat
clunky for the admin. There's no simple "get me a list of all
subscribers for this customer and what they're subscribed to" it's a lot
of clicking around, switching back and forth between user accounts etc.

Ideally we'd have it all managed in one place in IXP manager and not
have users in mailman at all (all subscriptions and unubscriptions have
to be manually checked and approved, and it can be difficult to relate
which members the list subscription belongs to.) I'd sooner that
somebody just login to IXP Manager and do what they want.

Also we need to check that in the process, a member does not manage to
unsubscribe ALL contacts from the lists. (i.e, I need to enforce that at
least one contact is subscribed to the announce list.)

So, whilst I set up the lists, we did not proceed with telling members
to update anything, otherwise it would be a massive shambles.
Hoping that a fix would be forthcoming in IXP Manager sometime soon,
I left it like that. :)

Reminds me that we (LONAP) should probably turn off the mailing list
sync feature for now as it doesn't work for us and causes more problems
that it solves.


Rob


This is a forwarded message

**Comment by barryo** [comment]
Thanks @listerr - the above is uber-useful for trying to sketch out how the next iteration of this should work.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: mailing list management, if to be kept within IXP Manager, needs a complete rework rather than tweaks on the current system which was INEX-specific.*
