### ISSUE TITLE
Timestamps stored in local time in some tables and in UTC in others

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#221]
I have searched exhaustively and as far as I can see this is not due to an oversight in our configuration anywhere (although I'd be happy to be wrong). I am seeing that after the update-prefixes-and-asns cronjob runs the entries in irrdb_prefix (and possibly irrdb_asn, I didn't check) are being updated with UTC timestamps, and after the compare-prefixes cronjob runs the entries in rs_prefixes are being updated with localtime. Both servers the cronjobs run on are configured the same in terms of locale & system-clock, and output the same for `date`, etc, and I can't find any UTC leftovers in our ixpmanager configs. This hasn't seemed to have any adverse effect on the interface level, but it did make understanding sql output very confusing for a while today when I was troubleshooting an unrelated issue with a customer's "accepted prefixes" apparently not updating (solved).

**Comment by nickhilliard** [comment]
ah.  that will be a direct consequence of writing code in this part of the world between october and march. I blame the geography.

Otherwise, noted and we'll get this sorted.

@barryo I suspect that religiously sticking to UTC for sql timestamps might be the best option here.

**Comment by barryo** [comment]
Nah, I don't think this is a coding issue. MySQL helpfully obfuscates timezone differences by storing everything internally as UTC. When you set a date(time) in MySQL, it converts to UTC based on the current TZ of the server and vice verse when reading a time.

It's probably an issue with PHP's timezone setting. 

http://php.net/manual/en/datetime.configuration.php

@rowanthorpe - I'll close as I expect this is the issue. Please reopen if not.
