### ISSUE TITLE
After upgrade to IXP Manager V3.7.3 update-l2database.pl stopped working

### ISSUE THREAD

**Issue by bcix** [inex/IXP-Manager#224]
Hi,

after upgrade to IXP Manager V3.7.3 update-l2database.pl stopped working.

Our daily morning cronjob comes back with:

We run:
```
 /ixp/tools/runtime/l2database/update-l2database.pl   -vlan 100
```
Result:
```
DBD::mysql::st execute failed: Unknown column 'virtualinterfacename' in 'field list' at /ixp/tools/runtime/l2database/update-l2database.pl line 99.
DBD::mysql::st execute failed: Unknown column 'virtualinterfacename' in 'field list' at /ixp/tools/runtime/l2database/update-l2database.pl line 99.
```

Is this related to change https://github.com/inex/IXP-Manager/pull/199 , which might require a DB schema update which is not mentioned at the notes for V3.7.3 https://github.com/inex/IXP-Manager/releases ?

Thanks, Thorleif

**Comment by barryo** [comment]
Hi @bcix - yip, you need to refresh your views:

    mysql -u username -ppassword [dbname] < tools/sql/views.sql

Updating docs now.

**Comment by bcix** [comment]
Hi @barryo - thanks al lot, now it works again!
