### ISSUE TITLE
Geeting a issue while running localhost

### ISSUE THREAD

**Issue by Nitin29** [inex/IXP-Manager#226]
Hello All,

We are new to IXP manager facing a issue.

After completion of "Installation 06 Apache Setup" while running  http://localhot/ixp
getting a message "bootstrap() ->run(); "

Looking for your support.

Nitin

**Comment by barryo** [comment]
Hi @Nitin29 - can you take this to the [mailing list](https://www.inex.ie/mailman/listinfo/ixpmanager) and provide more details / logs?

I presume you've installed / met the requirements at: https://github.com/inex/IXP-Manager/wiki/Installation-01-Requirements and php is installed and running?

E.g., if you create a file in `public/phpinfo.php` with:

```php
<?php
phpinfo();
```

and access it via http://localhost/ixp/phpinfo.php what do you get?

Again, follow ups to the mailing list please - issues are for bugs / feature requests / etc.
