### ISSUE TITLE
reseller customers do not disappear from reseller view when they leave the ixp

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#231]
from @listerr:

> On a related note, I have found that the "resold" customers, even if you set
> them as having left, they still remain in the "reseller's" view, and the
> reseller can't see which ones are live or gone.
> 
> Ideally I would like for there to be a record that a member was a resold
> customer and which reseller, but without having to unlink them
> completely.

**Comment by barryo** [comment]
I think the easiest solution here is to just hide customers that have left from this view.

The problem with showing old ones is that the reseller then has the expectation of that facility. But, when the customer moves from reseller A to reseller B (or direct), that association will no longer exist and  it will just disappear from the first reseller.

We'd have to implement a many-to-many relationship between customer / reseller with dates to implement the above. IXP Manager is not intended to replace a customers' / resellers' own CRM system.
