### ISSUE TITLE
Add useful information to the 'Route Server Prefix Analysis' 'Advertised but Not Accepted' tab

### ISSUE THREAD

**Issue by mahtin** [inex/IXP-Manager#232]
Presently the **Route Server Prefix Analysis** page has a **Advertised but Not Accepted** tab which lists routes not allowed by the route server(s). See [Route Server Prefix Analysis Tool](https://github.com/inex/IXP-Manager/wiki/Route-Server-Prefix-Analysis-Tool) and [table-routes.phtml](https://github.com/inex/IXP-Manager/blob/master/application/views/rs-prefixes/table-routes.phtml) and [rs-prefixes/list.phtml](https://github.com/inex/IXP-Manager/blob/master/application/views/rs-prefixes/list.phtml).

I would like to propose an enhancement that allows the route to be tagged in some way should a larger CIDR be in the accepted routes list (the _Advertised & Accepted_ tab). This would help helpful to peers when an IX doesn't execute **le 24** (**le 64**) filtering.

The [Repositories/RSPrefix.php](https://github.com/inex/IXP-Manager/blob/master/application/Repositories/RSPrefix.php) logic along with [Entities/RSPrefix.php](https://github.com/inex/IXP-Manager/blob/master/application/Entities/RSPrefix.php) would implement this change.

Should an IX actually implement **le 24** (**le 64**) filtering, then this new code would simply be a null operation.

**Comment by barryo** [comment]
This was implemented in v5.0.0 via https://docs.ixpmanager.org/features/route-servers/#displaying-filtered-prefixes and is discussed / demonstrated in a number of 2019 presentations at https://www.ixpmanager.org/presentations
