### ISSUE TITLE
SQL schema diagram should be updated 

### ISSUE THREAD

**Issue by mahtin** [inex/IXP-Manager#236]
Does https://github.com/inex/IXP-Manager/tree/master/data/schemas need to be updated? It's a few years old.

**Comment by barryo** [comment]
It's mostly right but I'll cut a new one. What I actually need to do is cut out some of the feature-creep stuff in there.

**Comment by barryo** [comment]
See: https://dl.dropboxusercontent.com/u/42407394/schema-ixp-manager-v2-20150918.pdf

That's the latest from v4-dev which should be on par with master (v3).
