### ISSUE TITLE
multiple as-set objects not supported for irrdb-cli.update-prefix-db action

### ISSUE THREAD

**Issue by medea61** [inex/IXP-Manager#239]
if a peer has multiple as-sets configured (e.g. AS-CUST-SET1 AS-CUST-SET2) irrdb-cli.update-prefix-db trips over this as of the way bgpq3 parses args.

bgpq3 -l pl -j "AS-CUST-SET1" -4 --> produces sane output
bgpq3 -l pl -j "AS-CUST-SET2" -4 --> produces sane output
bgpq3 -l pl -j "AS-CUST-SET1 AS-CUST-SET2" -4 --> produces emtpy output
bgpq3 -l pl -j 'AS-CUST-SET1 AS-CUST-SET2' -4 --> produces emtpy output
bgpq3 -l pl -j AS-CUST-SET1 AS-CUST-SET2 -4 --> produces sane output

BGPQ3.php adds doublequotes with escapeshellarg() all over the place, which basically is a good idea for producing sane output, but is very unlucky in this case. apparently bgpq3 parses the doublequotes and ends up returning empty results.

tested with bgpq3 0.1.32-rc6

**Comment by barryo** [comment]
A peer on an IX should have a single as-set. That as-set should contain all other required as-sets. bgpq3 will recursively unravel them.

**Comment by nickhilliard** [comment]
@medea61: following up what @barryo said, there is no standard cli syntax for specifying multiple as-sets.  irrtoolset and strict rpsl would handle this by requiring "AS-CUST-SET1 and AS-CUST-SET2".  bgpq3 seems to require an argv separated list.  Other rpsl parsers don't support this at all.

In this situation it would be far simpler and more portable to request that the customer creates a single as-set.
