### ISSUE TITLE
Route server private ASN for community use with 32-bit ASN members

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#240]
We have a member requirement to use the communities on the route server to enable selective advertisements to peers. Member considers it a blocker to using the route servers.

However, of course, the current spec as implemented (RFC 5668) does not support the community model used by IXPs. with 32-bit ASNs.

Therefore we need to find a workaround to this limitation until such time as it's addressed.

Proposed solution is to allocate such members a private 2-byte ASN for use with the route server communities, to enable backward compatibility.

I would need an extra field somewhere in IXP manager to put this ASN, and an update to the template to accept this ASN in the community string for this peer when building the route server configuration.

The hacky hack is probably just to disable RS support entirely in IXPman for this member and add a static chunk of config, but this is going to cause it to be fiddly to manage, and many stats to be wrong etc.

**Comment by barryo** [comment]
Hey @listerr 

> However, of course, the current spec as implemented (RFC 5668) does not support the community model used by IXPs. with 32-bit ASNs.

Indeed. A growing issue.

> Therefore we need to find a workaround to this limitation until such time as it's addressed.
> 
> Proposed solution is to allocate such members a private 2-byte ASN for use with the route server 
> communities, to enable backward compatibility.
>
> I would need an extra field somewhere in IXP manager to put this ASN

Yeah, no. In our industry there is nothing more permanent that a temporary solution. And this is very hacky. 

If you want to hack in a solution, I can help you craft the right syntax for the Smarty template to make this work for these particular members.

Failing a proper solution via IETF, our planned solution is to allow members manage opt outs on the route server via a UI on IXP Manager (with other bells and whistles).

My 2c.

**Comment by listerr** [comment]
I agree that this is a hack, however our customer has this requirement otherwise they will not peer with the route servers, and hence fell that they will not get value from the exchange.

I'm not holding my breath that IETF will deliver a permanent fix any time soon, and it will take even longer for it to be supported by vendors, so yes, the temporary fix will have to be more or less permanent for the foreseeable future, or we just continue to ignore this issue.

So we either implement some way to address this, or risk that members will feel discriminated for having a 32-bit ASN, they aren't able to use the functionality of the route servers, and leave the exchange.

I like the idea of doing something controllable from the web UI, although as we essentially have a customer who is paying for service they are not able to use, I need to make this work for them in the next few days somehow.

Over to you...

**Comment by barryo** [comment]
Rob, as I said, *If you want to hack in a solution, I can help you craft the right syntax for the Smarty template to make this work for these particular members.* - ping me on email with the specifics and we'll work out a config and then post / commit the template for anyone else.

**Comment by nickhilliard** [comment]
some other ixps have been using one of the extended community mechanisms for this.  This would be a better option.

**Comment by barryo** [comment]
@nickhilliard any examples?

**Comment by nickhilliard** [comment]
i'm pretty sure gr-ix are doing this.  Definitely one or two of the euro-ix ixps, but i can't remember exactly which.

**Comment by nickhilliard** [comment]
looks like the config is up on the bird wiki:

https://gitlab.labs.nic.cz/labs/bird/wikis/Route_server_with_community_based_filtering_and_single_RIB

**Comment by barryo** [comment]
This was originally solved as follows: 

To only advertise routes from asXXX to asYYY and no one else, you need to add in the equivalent functionality for 32bit ASNs to the `ixp_community_filter()` function in the file: `application/views/_skins/XXXX/router-cli/server/bird/header.cfg`.

Essentially, after the lines:


```php
function ixp_community_filter(int peerasn)
{
        if !(source = RTS_BGP) then
                return false;
```

add in:

```php
        # Filter to advertise asXXX routes to asYYY only
        if (bgp_path.first = XXX) then
        {
            if (peerasn = YYY) then
                return true;

            return false;
        } 
```

@listerr may have found an alternative solution?

**Comment by matejv** [comment]
I noticed this thread just now.

Here at SIX.SI we've been (ab)using the Route origin extended community - same as in the example Nick posted above.

Here is the BIRD template 
https://github.com/ArnesSI/IXP-Manager/blob/arnes-skin/application/views/_skins/arnes/router-cli/server/bird/header.cfg#L138

and updated IXP-Manager documentation for our members:
https://github.com/ArnesSI/IXP-Manager/blob/arnes-skin/application/views/_skins/arnes/static/route-servers.phtml#L208

This solution worked fine in the lab. But I'm not sure any of our members actually used it in practice. Not many 32bit ASes at our exchange and even less filtering going on.

**Comment by barryo** [comment]
Thanks @matejv - that's actually the same as @listerr's implementation.

I suspect we all suffer from the same issue: *not many 32bit ASes at our exchange and even less filtering going on*.

I'm going to close as I think the original requirement has been solved.
