### ISSUE TITLE
Billing/Registration address display missing a line

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#242]
Both customer registration and billing pages have 3 lines for address, then City and Postcode on the address input boxes.

The display page however is missing a line from the address.

So a billing address entered like this:
https://ixpman.server/customer/billing-registration/id/NN

The Old Church House
12 High Street
Crinkley Bottom
FELPERSHAM
FL1 2AN

Displays like this:
https://ixpman.server/customer/overview/id/NN/tab/billing

The Old Church House
12 High Street
FELPERSHAM
FL1 2AN

Which does cause me to look to see if I entered it incorrectly.

Would also be awesome if there was some way to copy the billing <-> registration address over with one click, since entering the same address twice is boring. :)

R.

**Comment by nickhilliard** [comment]
good catch.  fixed in 0e061c0

**Comment by barryo** [comment]
Reopening to:

1. port to v4
2. implement the copy fn @listerr suggested as it bugs the hell out me too

**Comment by barryo** [comment]
All done :beer:
