### ISSUE TITLE
adding mac-address to vlan-interface

### ISSUE THREAD

**Issue by medea61** [inex/IXP-Manager#243]
We are considering to automatically generate mac-acls per peer-port. For that to happen we need to have the mac-address(es) registred to the respective vlan-interface. Preferably editable by the customer himself (skinnable option?) so that in the end no manual intervention by ixp-staff is required if the customer changes his equipment.

Anybody else interested in this feature? We are considering sponsoring.
Otherwise: would a pull-request be accepted in case we consider to develop this ourselfs?

**Comment by barryo** [comment]
Hey - thanks for opening this. As we discussed in Berlin, this is very much near the top of our list. We have a proposal document nearly complete regarding sponsorship and a full time developer. Can you wait until the first week in January and we'll start circulating? 

(feel free to ping me on the 8th of Jan!)

**Comment by medea61** [comment]
We are still very open to the sponsoring and I will ping you again in January. For ourselfs we may have to hack together an intermediate/temporary solution anyway given our timelines. In the best case some code may be refactorable...

**Comment by barryo** [comment]
Hey @medea61 - just in case you missed this on the euro-ix mailing list:

https://www.inex.ie/noncms/2016-02-IXP-Manager-Funding-1.3.pdf

**Comment by barryo** [comment]
Closing this issue as it's on the v4 roadmap referenced above.
