### ISSUE TITLE
Resseller ports

### ISSUE THREAD

**Issue by heitorganzeli** [inex/IXP-Manager#245]
Hello,

I'm current analyzing the ixp-manager because we want to use it to manage our network here at IX.br.
I was trying to map our reseller ports inside the system but i don't think i managed to do it right.

Here at IX.br we designate two vlans (v4 and v6) for each member and translate it to specific bridge domains in the network core. So, for reseller ports, I thought I should map multiple virtual interfaces, one for each resold participant, to a single physical reseller interface or port.

Ideally, each resold member should have one virtual interface that could be attached to a physical interface owned by a reseller member. And, these virtual interfaces could have multiple Vlans attached to them like any other.

From what I understood of the current software design this scenario can't happen because you aren't able designate the same switch ports (or LAG) to multiple members.

I'm willing to make the necessary code changes so the software better meets our needs,
but would still like to know if we're going through the right path.

thanks

**Comment by barryo** [comment]
> From what I understood of the current software design this scenario can't happen because you aren't 
> able designate the same switch ports (or LAG) to multiple members.

Correct. The current reseller implementation is via fan out ports.

We at INEX ourselves need this implemented and we are some way along the path to doing that.

Are you on the [mailing list](https://www.inex.ie/mailman/listinfo/ixpmanager)? We hope to make an announcement along these lines next week.
