### ISSUE TITLE
Warn or restrict when adding superusers

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#247]
It's easy to accidentally add a customer user or customer superuser as a system-wide superuser, giving them access to far more than they should.

Is it possible to either:

a) Pop up some sort of warning when this option is selected "Are you sure this is REALLY what you want to do?"

b) Restrict adding superuser accounts to certain customer accounts only (e.g. the internal/customer?) rather than just any customer?

Rob

**Comment by barryo** [comment]
I like (b).

**Comment by barryo** [comment]
(b) is now implemented as follows:

* hard coded to not allow superadmins on non-internal customers
* superadmin option removed when we know it's a non-internal customer
