### ISSUE TITLE
Option to change/turn off default phone number suggestions

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#25]
Two users have mentioned they have: 

"+353 86 876 543 / +353 1 765 4321" in their info for phone/fax info.

Can there be an option to turn this off, or put it underneath the text box instead of in it?

(Also we'd quite like "+44 1234 5678") but this seems to be a library thing?)

**Comment by barryo** [comment]
Fixed in internal development by commit islandbridgenetworks/IXP-Manager@5beff4e9965220090a442a9e80d21e34866e92a8.

This will be available in v4.8.
