### ISSUE TITLE
Suggestion: Change Smarty package to v3.1.21+ and use GitHub

### ISSUE THREAD

**Issue by LindsayHill** [inex/IXP-Manager#251]
The Smarty package is now available via GitHub (https://github.com/smarty-php/smarty/blob/master/COMPOSER_RELEASE_NOTES.txt)

Is it possible to change IXP-Manager to use Smarty v3.1.21+, and pull it from there? 

This will simplify composer.json, remove the need to change Composer settings to allow non-secure downloads, and remove the links to googlecode, which is closing down.

**Comment by barryo** [comment]
Yip, this something on my todo list as it's a work in progress elsewhere.

Historical context: https://github.com/opensolutions/ViMbAdmin/pull/169

**Comment by barryo** [comment]
Fixed in current active dev branch.
