### ISSUE TITLE
Suggestion: Move to Chosen v1.5.1+

### ISSUE THREAD

**Issue by LindsayHill** [inex/IXP-Manager#252]
bower.json selects chosen v1.4.2.

There was a tagging issue with chosen v1.4.2 (https://github.com/harvesthq/chosen/issues/2324), which results in this output when launching IXP-Manager with Vagrant:
`==> default: bower chosen#~1.4.2           mismatch Version declared in the json (1.4.1) is different than the resolved one (1.4.2)`

Using a later version of chosen fixes this problem.

**Comment by LindsayHill** [comment]
Actually maybe hold off on that one - the bower-chosen version has un-minified versions (https://github.com/harvesthq/chosen/commit/00f2e25d3a0d0ba3a0b21494d635c04bcfc55338)

So if you change to v1.5.1 here, it breaks things like application/view/header-css.phtml that refer to `/bower_components/chosen/chosen.min.css`

**Comment by barryo** [comment]
Hi @LindsayHill  - be careful here, you're stepping between two worlds :wink: 

The master branch in currently v3 and will be branched off as a security maint branch soon.

The default branch, v4, has yet to be officially released with documentation. This is planned to co-incide with euro-ix in April.

v3 is the recommend version right now. v3's header-css file shouldn't refer to the bower install. This is an error which I'll fix.

**Comment by LindsayHill** [comment]
Hey @barryo that's great news about an official launch for v4. I'll be in Europe during early April, but won't be making it to Euro-IX. Are you presenting there? Hopefully it's published online.

I've been looking more at the v4 branch since that's more of the 'future.' Still getting my head around it. Obviously going to be a bit tricky going through the framework transition but it should be good for the future.

**Comment by barryo** [comment]
> Are you presenting there? Hopefully it's published online.

We host a regular IXP Manager workshop at Euro-IX and slides (and, if recorded, video) are made available.

From the last workshop:

https://www.inex.ie/noncms/euroix27-inex-ixp-manager-workshop-introduction.pdf
https://www.inex.ie/noncms/euroix27-inex-ixp-manager-v4-deep-dive.pdf
https://www.youtube.com/watch?v=v8PRUQlRMRM (not the best quality)
