### ISSUE TITLE
changes to public member list

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#255]
Is it possible to change the member list page (/public/member-details) to

1. Only include members whose status is "Normal" (i.e. only list them as a member once we actually mark them as connected in the database)

2. If "Abbreviated Name" is populated, use this field for the company name instead of the company name. Several member want to be listed as a certain brand or name other than the company name.

Thanks,

Rob

**Comment by barryo** [comment]
Hey Rob,

is that for this: http://www.lonap.net/members.php

Let me know what URL you use to pull the data for http://www.lonap.net/members.php and I'll have a look. This is skinned so it should be a local change.

Barry

**Comment by listerr** [comment]
Hi Barry,

It's getting it from:  https://portal.lonap.net/public/member-details

Could probably have a go at this myself but I don't know what the
variables are to pull the relevant things out of the database, i.e.
what I would need to get at the abbreviated name instead of
{$c->getName()}


Rob


On Sun, 10 April, 2016 at 3:04:08 PM, barryo wrote:


> Hey Rob,
> is that for this: http://www.lonap.net/members.php
> Let me know what URL you use to pull the data for
> http://www.lonap.net/members.php and I'll have a look. This is skinned so it should be a local change.
> Barry


Regards,


Rob


-- 
Rob Lister
rob@lonap.net
+44 20 3137 8330

**Comment by barryo** [comment]
@listerr - i changed the DB query function in the above commit for only members physically connected. This function was actually created for you so should be fine. 

Additionally, I s/getName()/getAbbreviatedName() in the template.

**Comment by barryo** [comment]
btw, a better way of handling this in the future is by grabbing the JSON from the Euro-IX member schema and using that.
