### ISSUE TITLE
mrtg-rrd question

### ISSUE THREAD

**Issue by melkior** [inex/IXP-Manager#256]
Hi,

is it possible to use existing utilities to generate mrtg graphs with .rrd? I'm experimenting with mrtg.cfg option

LogFormat: rrdtool

and it converts mrtg .log files into .rrd and continue to fill .rrd files, so I'd now like to generate .png files (not on the fly). Is it atm possible or should I, for example, modify sflow-graph.php to make it work?

Thanks.

P.S. Using ixp manager v3

**Comment by barryo** [comment]
> is it possible to use existing utilities to generate mrtg graphs with .rrd?

In a few days, yes 😄 

This is being implemented as part of a DECIX bounty within a larger INEX project to completely rewrite the graphing backend. 

It's all happening in the *nf-graphs-decix* branch and will be released alongside the euro-ix IXP Manager workshop next week.

It will require an upgrade to IXP Manager v4 which will also be released next week.

Sneak peek:

https://github.com/inex/IXP-Manager/blob/nf-graphs-decix/resources/views/services/grapher/mrtg/header.plates.php#L30

**Comment by melkior** [comment]
Ok, nice, thanks.

Anyway, our site is planned to go production in a few days also, but v3 :-)
Can you tell me will it be possible to upgrade v3 -> v4 and how hard it will be?

P.S. Kudos, great app.

**Comment by barryo** [comment]
> Anyway, our site is planned to go production in a few days also, but v3 :-)

Then I suggest you go with log for now and migrate to rrd when you upgrade.

> Can you tell me will it be possible to upgrade v3 -> v4 and how hard it will be?

Documentation is a work in progress but it'll be a bit of work. v4 is a new framework with new packaging - it's a much more modern use of the PHP ecosystem. Upgrading will be a parallel installation and switchover.

**NB: PHP7 is a requirement for v4 so bear this in mind.** I.e. The just released Ubuntu 16.04 LTS will be the recommended platform.

Draft / work in progress docs: https://ixp-manager.readthedocs.org/en/latest/upgrade-from-v3.html

**Comment by melkior** [comment]
Hi,

I'm currently testing v4 and trying GRAPHER_BACKEND_MRTG_DBTYPE=rrd

As i see it really converts log files into rrd, but stops creating images/html.
After reading this link http://oss.oetiker.ch/mrtg/doc/mrtg-rrd.en.html it looks like that behavior is correct,
so can you just point me out is there a way ixpmanager v4 can use rrd backend on for example overall peering graphs page?

Thanks

**Comment by barryo** [comment]
Hey @melkior - there's an issue here. See:

* https://www.inex.ie/pipermail/ixpmanager/2017-March/001012.html
* https://www.inex.ie/pipermail/ixpmanager/2017-June/001092.html

This really is near the top of my list but just not top priority. Hopefully later this week.

**Comment by melkior** [comment]
Ok, thanks on info
