### ISSUE TITLE
differentiation between declared port speed and configured port speed

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#260]
In cases where the IXP provides subrate connectivity, the declared port speed at an IXP may not match the port speed which is configured on the access device.  This has implications for a bunch of things including mrtg maxbytes, etc.

There needs to be a new field added to the database to support the subrate speed.

**Comment by listerr** [comment]
+1 for this

**Comment by saschaboerner** [comment]
+1. For now, we have a customized file "database/Entities/PhysicalInterface.php" with added bandwidths of 250Mbps and 2.5Gbps. There should be more common speeds (like 250M, 2.5G etc) included in default.

**Comment by netfreak98** [comment]
+1

**Comment by barryo** [comment]
First pass of this now complete and includes:

- New `rate_limit` column on the database (the ask here is for rate limited ports - if there are other use cases this can still be used, the actual physical effect is how one codes the provisioning system / manually configures the switch.
- *Rate Limit* field when adding and editing a physical interface through the normal virtual interface overview. **NB:** this means if using the wizard, you configure the physical speed and then edit the physical interface afterwards. The wizard is meant to cover the 90% scenario and I'd prefer to keep it de-cluttered. 
- This is for member ports; not core ports (d'uh!).
- Speed reported on various member screens as the rate limited speed (and sometimes, where space / appropriate) as x / y and also GUI labels to make it clear when a port is rate limited.
- IX-F Member Export now reports rate_limit speed and adds an IXP Manager specific field called `if_phys_speed` to show the physical port speed.
- The switch configuration viewer (e.g. [INEX's one](https://www.inex.ie/ixp/switch/configuration) also updated to support this.
- Port utilisation updated to be congnisant of this.
- Switch provisioner yaml/json output now has `rate_limit` for peering ports, `null` means not in use.

> This has implications for a bunch of things including mrtg maxbytes, etc.

mrtg *not* updated. MRTG config uses the *detected speed* from MRTG. Not sure of the value of swapping this for the rate limited speed? Rate limiters can be buggy / misconfigured / etc and we'll want to see that traffic.

Code currently sitting in ratelimit branch.
