### ISSUE TITLE
getMailingListSubscribers() does not handle customers which have left

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#261]
If a customer leaves, they are still subscribed to mailing lists.

database/Repositories/User.php:getMailingListSubscribers() does not refer to cust and check for self::DQL_CUST_CURRENT, but it doesn't look as simple as that.

**Comment by listerr** [comment]
Yes, there are a few issues with the mailing list code including the
problem you mention. It does need a bit of a rethink.

https://github.com/inex/IXP-Manager/issues/22

Rob


On Wed, 1 June, 2016 at 12:08:46 PM, Nick Hilliard wrote:


> If a customer leaves, they are still subscribed to mailing lists.
> database/Repositories/User.php:getMailingListSubscribers() does not
> refer to cust and check for self::DQL_CUST_CURRENT, but it doesn't look as simple as that.


Regards,


Rob


-- 
Rob Lister
rob@lonap.net
+44 20 3137 8330

**Comment by barryo** [comment]
The mailing list code was written to solve a very INEX-specific issue and is well documented here:

https://github.com/inex/IXP-Manager/wiki/Mailing-List-Management

I guess the end goal would be to fully integrate / have IXP Manager as the canonical source of mailing list subscribers but that's a bigger piece of work with some edge cases / Mailman feature duplication:

* subscribe / unsubscribe without an IXP Manager account? Shouldn't really be possible but:
* we often add non-INEX members to different mailing lists so this needs to be schematically handled.

**Comment by barryo** [comment]
Regarding the OP:

> If a customer leaves, they are still subscribed to mailing lists.

Yes, unless a staged approach is taken:

1. user has mailing list subscription managed by IXP Manager
2. admin unsubs user
3. admin runs sync process
4. admin deletes user

This is not ideal and in practice for the very odd member leaving event, we've handled this manually.

This is all effectively covered by the feature request that is #22 so closing.
