### ISSUE TITLE
JSON api output for private VLANs/member ports

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#262]
Is there a JSON output that lists private VLANs and member ports, for example

```
vlans
    + private
       + vlan-id
         + switch
            + port
        + switch
            + port
            + port

```
So we can automate VLAN configuration from switch A, port N, to switch B, port Y.

**Comment by barryo** [comment]
Sorry @listerr - as you probably surmised, the answer to this is no. The only JSON export is the public facing one which (understandably) only presents public VLANs.

**Comment by listerr** [comment]
Okay,

Perhaps I'm asking the wrong question.

What is the way forward on this then?


Rob


On Mon, 1 August, 2016 at 11:26:12 AM, barryo wrote:


> Sorry @listerr- as you probably surmised, the answer to this is no.
> The only JSON export is the public facing one which (understandably) only presents public VLANs.
> —


Regards,


Rob


-- 
Rob Lister
rob@lonap.net
+44 20 3137 8330

**Comment by barryo** [comment]
> What is the way forward on this then?

More API access is on the development plan.

Right now, for scripting, the easiest is direct MySQL queries. Not ideal but that's all there is. IIRC, you have a Perl tool that does a ton of these already?

**Comment by listerr** [comment]
On Thu, 4 August, 2016 at 11:38:55 AM, barryo wrote:

> What is the way forward on this then?

> More API access is on the development plan. Right now, for scripting,
> the easiest is direct MySQL queries. Not ideal but that's all there
> is. IIRC, you have a Perl tool that does a ton of these already?

Yes, we have an internal whois service which could possibly be adapted
to output things in JSON/some more useful format.

So yes, should be simple enough to write some service that can produce
the required output - just wanted to check that I was not going to
re-invent any wheels.


Regards,


Rob


-- 
Rob Lister
rob@lonap.net
+44 20 3137 8330
