### ISSUE TITLE
vlan not specified - falling back to BRIDGE-MIB for compatibility

### ISSUE THREAD

**Issue by melkior** [inex/IXP-Manager#264]
Hi,

after adding new switch (dell force10 new firmware) update-l2database.pl returns this message:

DEBUG: cix03: vlan not specified - falling back to BRIDGE-MIB for compatibility
DEBUG: cix03: attempting BRIDGE-MIB (.1.3.6.1.2.1.17.4.3.1.2)
WARNING: cix03: cannot read BRIDGE-MIB or Q-BRIDGE-MIB. Not processing cix03 further.

snmpwalk -On -v 2c -c xxxxxxxx YYY.YYY.YYY.YYY .1.3.6.1.2.1.17.4.3.1.2
.1.3.6.1.2.1.17.4.3.1.2 = No Such Instance currently exists at this OID

So, is there any way to manually set vlan or oid to make this work?

Also, maybe this will be interesting to You guys. Here is switch info:

snmpwalk -On -v 2c -c xxxxxxxx yyy.yyy.yyy.yyy .1.3.6.1.2.1.1.1.0
.1.3.6.1.2.1.1.1.0 = STRING: "Dell Networking OS
Operating System Version: 2.0
Application Software Version: 9.10(0.0)
Series: S4810
Copyright (c) 1999-2016 by Dell Inc. All Rights Reserved.
Build Time: Sun Apr 10 06:42:55 2016"

So, had to copy/modify Platforms/vendor_dell_force10.php to match this string.

**Comment by nickhilliard** [comment]
The S4810 should work.  Did you specify the vlan on the command-line with the --vlan CLI switch? e.g.

% ./tools/runtime/l2database/update-l2database.pl --vlan 666

**Comment by melkior** [comment]
Looks like --vlan option is working but can't fully test it now because of other technical reasons.

Thanks
