### ISSUE TITLE
interface login timeout annoyance

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#265]
Once annoyance I find with the interface is that it times out my login. Fine, I can login again, but then I have to enter again what I was doing, because it does not resume.

Example, fill in a form of information and click save. Then everything I've entered is thrown away and I'm chucked back at the login screen. After logging in, it doesn't return to the place I was.

Perhaps could have an option to not make me want to throw my laptop across the room every time this happens:

Find tab with IXP Manager in.
Enter something in search box
Log in again
Enter something *again* in the search box

etc

:)

**Comment by listerr** [comment]
Or perhaps if it's going to time out, bounce back to the login screen at that point rather than waiting for me to do something and then throw me out.

**Comment by barryo** [comment]
Set the following in `application/config/application.ini` as approriate (values in seconds):

```
resources.namespace.timeout = 3600
resources.session.remember_me_seconds = 3600
```
