### ISSUE TITLE
rs_prefixes.custid

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#267]
SIXP ran into a problem where rs_prefixes ended up with a bunch of entries where custid was set to NULL.  The schema should be changed to set the custid type to be INT NOT NULL.

**Comment by mahafaye** [comment]
urgent help would be needed. thanks in advance

**Comment by mahafaye** [comment]
Any news on the bug mention is there a patch for it that we can apply fast.

**Comment by barryo** [comment]
Hi @mahafaye - schema changes require new major releases so that won't happen quickly - probably September sometime.

What are the consequences of this issue? Any idea how these null entries get into the database?

A daily cron job to delete these may help for now?

**Comment by nickhilliard** [comment]
hi @mahafaye, this isn't a problem on your installation.

we'll get around to fixing this bug, but it's low prio because it's difficult to replicate and there is no-one currently affected by it.

**Comment by mahafaye** [comment]
I guess a quick workaround would be better for now hence most aren't
affected with this bug. But for now the only thing I want us to see is if
we can getting working by accepting the SIXP prefix 196.49.1.0/24.

My other option is to do single peering with each of them who are peering
right now. By the way we also have a peer at the IXP Comium we would be
finalizing with them pretty soon for setup.

/mohamed

**Comment by barryo** [comment]
Closing -> this is no longer used and deprecated and has been replaced with the new filtered prefixes machanism.

**Comment by mahafaye** [comment]
pls proceed with closing of ticket.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
