### ISSUE TITLE
Improve Virtual Interface Portchannel UI

### ISSUE THREAD

**Issue by will-h** [inex/IXP-Manager#271]
Following on from https://github.com/inex/IXP-Manager/issues/126 - the settings in Virtual Interfaces-> Advanced Options are not at all clear. On switches with a 'parent' Port-Channel interface, you must manually enter the port name under Virtual Interface Name for e.g. sflow to work. 

Ideally this box would be moved out of 'Advanced', IMHO, and display a drop-down list limited to unassigned port-channel interfaces. (dream)

**Comment by barryo** [comment]
Just assigned to @nickhilliard as he was recently dealing with all this.

**Comment by barryo** [comment]
We have added documentation to this (both within the UI and [in the docs](https://docs.ixpmanager.org/usage/interfaces/#viewing-editing-an-interface).

As this varies incredibly from switch to switch, I'm not sure we can do much more.

Also, from a UI perspective, once set, the advanced options are always open.
