### ISSUE TITLE
Searchable port / customer notes

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#273]
May have asked this one before - 

Is it possible that port notes and customer notes can be searchable?

All customer notes visible from one page?

Currently we store useful details such as cable IDs in the notes fields as a place to put them until a better feature comes along.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: full text searching is a bigger job and probably not what you mean. A single view of all customers notes would better -> IDEAS file.*
