### ISSUE TITLE
IP Address Management

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#274]
Just a placeholder to try and gather some thoughts / ideas about possible improvement to IPv4 Address Assignment in the interface of IXP Manager, and not a top priority, though if you are redesigning other elements around this, may be worth considering:

There are probably differences of opinion, or thoughts on what could be done. so based on my experiences:

IP address management could improve.
1. IPv4 address assignment could be better than “massive unwieldy drop-down list  of IPv4 addresses.”  :)
2. IP addresses are recycled after some period of non-use. Show IPs previously allocated to disconnected members, or ARP sponged? Expire after some time?
3. Allow IP address reservation with no port associated? (In reality, we don’t just randomly hand them out; existing members going from 1 to 2 ports, in the majority of cases, would get a second consecutive IP address which is already “reserved”. As the IP address range fills up however, for some IXPs this possibly becomes more of a nicety. Other IXPs have “random” allocation policies and therefore consecutive IP addresses isn’t guaranteed.) 
4. Upgrading ports or moving IP addresses from one interface to another is fiddly in the current interface. There's a lot of copying/pasting, clicking around to move an assigned IP from one interface to another.

Looking at our old zone files, I can identify some "states" for IP addresses:
1. Not allocated (available to be issued)
2. Allocated to a member for possible future use (reserved)
3. Allocated to a member and assigned to an interface (in use)
4. Withdrawn (member has left; IP address is ARP sponged; to be returned to (1) in due course
5. "Other" - used for route servers / internal things or otherwise not available.

There was a (probably) LONAP-specific quirk in that, to keep addresses in the zone file where the member had not given us any reverse DNS, or unassigned, we did something like "ip81-220.no-dns-yet.lonap.net."

Probably another one that doesn’t fit nicely into the current database schema and would require some thought as to how exactly it's handled in the database.

Since automating the Reverse DNS updates from IXP Manager, we can’t use the zone files as the authoritative source for IPv4 address allocation “state”  - there was useful stuff in the zone file as commented out entries such as " ; IP Address sponged, robl, 2013-07-23" so we lost a bit of the state history or have to store that elsewhere.

This also means that if an IP address is not assigned to an interface in IXP Manager, it cannot currently “exist” in any other state (ARP sponged, reserved, used for some other purpose etc. unless they are deleted entirely from IXP Manager’s database in order to avoid them being shown as available to be assigned.) 

So - how to make an interface which is better than the current, but which is generic enough / allows for a variance of policies/methods of IP assignment in different IXPs?

LONAP does things in a certain way, partly for essential reasons, and others are "niceties", but would be good to get some input from other IXPs.

**Comment by barryo** [comment]
So the IP address controllers have been rewritten in [v4.7.0](https://github.com/inex/IXP-Manager/releases/tag/v4.7.0) which includes some new things. These and existing features address most of your queries:

> IPv4 address assignment could be better than “massive unwieldy drop-down list of IPv4 addresses.” :)

To be fair, the *massive unwieldy drop-down list of IPv4 addresses* will only be as massive and unwieldy as the amount of IP addresses you pre-create. Separate to that, the interface has *as you type searching*. Some time ago (pre 4.7.0 but I can't remember when exactly), we make the form on the add new interface wizard such that you can enter an IP address and if it does not exist, it will be created.

> IP addresses are recycled after some period of non-use. Show IPs previously allocated to disconnected members, or ARP sponged? Expire after some time?

There's currently no provision or plans for past IP address state.

> Allow IP address reservation with no port associated? (In reality, we don’t just randomly hand them out; existing members going from 1 to 2 ports, in the majority of cases, would get a second consecutive IP address which is already “reserved”. As the IP address range fills up however, for some IXPs this possibly becomes more of a nicety. Other IXPs have “random” allocation policies and therefore consecutive IP addresses isn’t guaranteed.)

Same as above I'm afraid - this would also require some additional element of state beyond whether an IP is assigned to a VLAN interface or not.

> Upgrading ports or moving IP addresses from one interface to another is fiddly in the current interface. There's a lot of copying/pasting, clicking around to move an assigned IP from one interface to another.

The layer 3 (VLAN interface) configuration is separate to the layer 2 (physical interface) configuration. Upgrading ports or moving ports should just be a matter of editing the physical ports - nothign fiddly required unless I misunderstand you?

See: http://docs.ixpmanager.org/usage/interfaces/

While I can certainly see some benefits of the state suggestions, I've added the request for state to the longer term IDEAs file for now as it hasn't and won't make the shorter term development list I'm afraid. Priorities for 2018H1 are to close out the ZF -> Laravel migration and redo the end user area.

**Comment by barryo** [comment]
btw @listerr - if you look at the commits to IDEAs you'll see it's not a dumping ground for good ideas to go and die - they do make their way through eventually with time, effort, resources and increased demand 😉 

https://github.com/inex/IXP-Manager/commits/master/IDEAS
