### ISSUE TITLE
Support GoBGP for route servers

### ISSUE THREAD

**Issue by shusugmt** [inex/IXP-Manager#275]
GoBGP is a new oss BGP daemon which can be used as a route server at IXPs.

https://github.com/osrg/gobgp

Through the quick investigation, I figured out there are at least two things need to be done to add GoBGP support.
1. Implement config generation
2. Tweak or add script for Route Server prefix analysis tool
   - current script for BIRD is at `tools/runtime/route-servers/compare-route-server-prefixes.pl`

The second part is not mandatory for those who use BIRD as a primary route server, so I'll get on to config generation first.

**Comment by nickhilliard** [comment]
@s2ugimot this would be very welcome.  You will need to create a new directory called ```application/views/router-cli/server/gobgp/``` and put your template in there.  The easiest approach is to follow the example of the existing entries for header.cfg, footer.cfg and neighbor.cfg.

As you say, the current ```compare-route-server-prefixes``` script depends on bird, but this could be changed to also accept api output from gobgp.

If you want to submit diffs, can you sign a Contributor License Agreement?  There are instructions here:

https://github.com/inex/IXP-Manager/blob/master/CONTRIBUTING.md
https://github.com/inex/IXP-Manager/wiki/Contributor-License-Agreement

**Comment by s2ugimot** [comment]
@nickhilliard I'll check the licensing thing tomorrow.

Just done adding templates for GoBGP config. Can you please check #277

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: OpenBGPd and GoBGP support are on the development plan and do not require a standalone ticket.*
