### ISSUE TITLE
Problem with update-l2database.pl and Arista 7280R running 4.17.1.1F

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#276]
So. Seems like Arista nowadays suffers from the Juniper EX-thingie, or something related at least.
 Seems to be a new behavior in 4.17.1.1F. But it *could* actually be there in previous versions as well and be related to some sort of configuration thingie.

I did a nasty workaround to get this working but it should really be fixed in a better way, also my "workaround" is hard coded as well for my VLAN ID.

So, I changed jnxExVlanTag to an Arista specific OID (aristaEntSensorMIB) to run separate stuff for Arista, and since I don't have any Juniper boxes I didn't care about retaining the Juniper fix.

I then got a final MAC address where the 2 first digits were actually the hex value for the VLAN ID so I had to add a new OID for dot1qTpFdbPort calling it ARISTAdot1qTpFdbPort (again, to separate it) where I included the VLAN in the OID. Really nasty. But it works ;)

So, looking forward to a non-super-duper-ugly fix for this! :-)

```
# diff -u update-l2database.pl.org update-l2database.pl.new
--- update-l2database.pl.org	2016-10-09 17:10:09.360223393 +0200
+++ update-l2database.pl.new	2016-10-09 17:10:56.723182121 +0200
@@ -185,9 +185,10 @@
 		'dot1dBasePortIfIndex'	=> '.1.3.6.1.2.1.17.1.4.1.2',
 		'dot1qVlanFdbId'	=> '.1.3.6.1.2.1.17.7.1.4.2.1.3',
 		'dot1qTpFdbPort'	=> '.1.3.6.1.2.1.17.7.1.2.2.1.2',
+		'ARISTAdot1qTpFdbPort'	=> '.1.3.6.1.2.1.17.7.1.2.2.1.2.203',
 		'dot1dTpFdbPort'	=> '.1.3.6.1.2.1.17.4.3.1.2',
 		'dot1dTpFdbAddress'	=> '.1.3.6.1.2.1.17.4.3.1.1',
-		'jnxExVlanTag'		=> '.1.3.6.1.4.1.2636.3.40.1.5.1.5.1.5',
+		'jnxExVlanTag'		=> '1.3.6.1.4.1.30065.3.12',
 	};
 
 	$debug && print STDERR "DEBUG: $host: started query process\n";
@@ -254,7 +255,7 @@
 	# return data on Q-BRIDGE-MIB rather than BRIDGE-MIB
 	if (!$vlan && $junipermapping) {
 		$debug && print STDERR "DEBUG: $host: attempting special Juniper EX Q-BRIDGE-MIB query for unspecified vlan\n";
-		$qbridgehash = snmpwalk2hash($host, $snmpcommunity, $oids->{dot1qTpFdbPort}, \&oid2mac, undef);
+		$qbridgehash = snmpwalk2hash($host, $snmpcommunity, $oids->{ARISTAdot1qTpFdbPort}, \&oid2mac, undef);
 		if ($debug) {
 			if ($qbridgehash) {
 				print STDERR "DEBUG: $host: Juniper EX Q-BRIDGE-MIB query successful\n";

```

**Comment by rasssta** [comment]
Ping @nickhilliard

**Comment by nickhilliard** [comment]
Already supported - you need to use the ```--vlan``` command line argument with arista EOS.
