### ISSUE TITLE
How can i use the ZABBIX instead of MRTG to display the traffic graph ?

### ISSUE THREAD

**Issue by lyangwillow** [inex/IXP-Manager#279]
How can i use the Zabbix instead of MRTG display the traffic graphs ?

Our IX always used Zabbix display the traffic graphs.

**Comment by jamestutton** [comment]
I currently have a working implementation of this feature so hope to publish some beta code shortly.

**Comment by barryo** [comment]
Also sounds interesting.

Have you used Grapher?

https://ixp-manager.readthedocs.io/en/latest/features/grapher/

**Comment by jamestutton** [comment]
Yes its Grapher based and basically has near complete config generation support as long as the base devices are perconfigured in Zabbix.
