### ISSUE TITLE
Route server config prefix aggregation

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#281]
Hello,

We've recently taken on some new members who have upwards of 40,000 prefixes found in the IRRDB, and this is generating quite a large BIRD configuration file. They only actually advertise a tiny subset of these prefixes.  For other members, the query with bgpq3 returns every tiny prefix.

```
root@beta:/home/robl# bgpq3 -j AS-MESH | grep "prefix" | wc -l
2643
root@beta:/home/robl# bgpq3 -Aj -m 24 AS-MESH | grep "prefix" | wc -l
679

root@beta:/home/robl# bgpq3 -j AS7713:AS-TELKOM-TRANSIT | grep "prefix" | wc -l
51967
root@beta:/home/robl# bgpq3 -Aj -m 24 AS7713:AS-TELKOM-TRANSIT | grep "prefix" | wc -l
8875
```

As a result, the BIRD config is getting pretty large and unwieldy.

```
robl@rs1e:~$ ls -lah /etc/bird/bird-vlanid1-ipv4.conf
-rw-rw-r-- 1 root bird 4.8M Nov 28 18:17 /etc/bird/bird-vlanid1-ipv4.conf

```
LONAP's RS policy is to accept more specifics, up to /24.

I have been thinking about if we could make the BIRD config more efficient by aggregating the IRRDB prefixes during config generation. (Probably the right place to do this would be when the RS config is generated, with a config option to enable more specifics / aggregation or not. This way the database and prefix tool in the interface isn't affected, though possibly it would help if we could flag which prefixes had been aggregated, for example.)

Thoughts?

**Comment by nickhilliard** [comment]
> Thoughts?

Bird is pretty efficient at config file management.  Is this causing a
specific problem with performance?

**Comment by rasssta** [comment]
We at STHIX also accept more specifics, up to /24, and have implemented this in the following way:

# We only populate the database with up-to-/24 and up-to-/64:

--- /tmp/Bgpq3.php	2017-08-31 10:18:43.840387431 +0200
+++ Bgpq3.php	2017-08-30 21:52:26.388941191 +0200
@@ -151,6 +151,12 @@
         if( $proto == 6 )
             $cmd = '-6 ' . $cmd;
 
+	if ($proto == 4)
+		$cmd = '-m 24 ' . $cmd;
+
+	if ($proto == 6)
+		$cmd = '-m 64 ' . $cmd;
+
         $cmd = $this->path . ' ' . $cmd;
 
         $output = [];

# In our neighbors.foil.php template we tell BIRD to accept more specifics up to /24 and /64

--- /srv/ixpmanager/resources/views/api/v4/router/server/bird/neighbors.foil.php	2017-08-14 21:36:05.418038010 +0200
+++ neighbors.foil.php	2017-08-31 10:24:13.701285969 +0200
@@ -86,7 +86,18 @@
 <?php   if( count( $int['irrdbfilter_prefixes'] ) ):
     /* allnet = [ <?php echo $t->softwrap( $int['irrdbfilter_prefixes'], 4, ", ", ",", 16 ); ?> ]; */ ?>
 
-    allnet = [ <?= implode( ', ', $int['irrdbfilter_prefixes'] ) ?> ];
+    allnet = [ <?php
+	$cq=0;
+	foreach ($int['irrdbfilter_prefixes'] as $prefix) {
+		if ($cq>0) {
+			echo ", ";
+		};
+		$cq++;
+		if (preg_match('/:/', $prefix))
+			echo preg_replace('#/([0-9]*)$#', '/$1{$1,64}', $prefix);
+		else
+			echo preg_replace('#/([0-9]*)$#', '/$1{$1,24}', $prefix);
+	} ?>];
 
     if ! (net ~ allnet) then
             reject;

**Comment by listerr** [comment]
Thanks - looks interesting. 

In some ways it would be useful to have the interface explain more clearly that a prefix:-

IS being accepted by virtue of having a less specific.
IS NOT being accepted because it is longer than /24 (or /64)

I can imagine it causing some confusion if for example the offending pile of /30s they are advertising trip the max prefix on the route server but in the web interface, they only see the prefixes they intended.

Also it's mentioned in a more recent issue https://github.com/inex/IXP-Manager/issues/329
#329

**Comment by AleksBelytskyi** [comment]
Hello,

I think it is better to use '-R' option of bgpq3 to allow more specific routed as well.
It will decrease the number of prefixes in a database and will make bird config file less.
Please correct if I'm wrong.

**Comment by nickhilliard** [comment]
support for more specifics was added in IXP Manager v4.7.

**Comment by barryo** [comment]
Just reopening this to evalaute the `-R` suggestion which may be a good idea.

**Comment by rfc1036** [comment]
This should be optional since the common behaviour is to not accept more specifics.

**Comment by barryo** [comment]
The use of `-R` is a good idea but there is an issue:

1. a member is configured to allow more specifics and `-R` used => thus only the members supernets are in the database
2. admin changes member to only accept specifics
3. route server reconfiguration kicks off before irrdb update (these are decoupled) => route server may drop many prefixes

I'll keep this open so that we can add an event to this action which would immediately kick off an IRRDB update for the question in question.

From v4.8 onwards, you can implement this safely if as a policy you always allow more specifics by editing the bgpq3 path in .env to include this option:

```
IXP_IRRDB_BGPQ3_PATH="/usr/local/bin/bgpq3 -R"
```

**Comment by barryo** [comment]
There is great scope here for reducing Bird and DB entries:

```
$ bgpq3 -R 24 AS-GOOGLE | wc -l
      97
$ bgpq3  AS-GOOGLE | wc -l
    8119
```

**Comment by listerr** [comment]
This one could be considerably optimised:-

$ bgpq3 AS45102 | wc -l
17802
$ bgpq3 -A AS45102 | wc -l
54
$ bgpq3 -R 24 AS45102 | wc -l
47

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues.

Where appropriate, will:

* Relocate to the IDEAS file.
* Add additional information below.
* No relocation / additional information for uber-stale issues.

*Additional information: this has been relocated to IDEAs. Similar comments to inex/IXP-Manager#610. NB: Ideas is not where things go to die (check the history of the file). It's where I house keep things that have no short term prospects of implementation. We have plans for OpenBGPd support, etc and all this requires big revisions to how we generate route server configs in IXP Manager. We'll include this in that process.*
