### ISSUE TITLE
IXP-Manager installation issue

### ISSUE THREAD

**Issue by fakrul** [inex/IXP-Manager#286]
I am having issue installing IXP-Manager. In "Installation 04 Configuration" says there will be a sample configuration file in application/config "application.ini.dist". But in my application/configs/ I only have:

```
# ls -lah application/configs/
total 16K
drwxr-xr-x 2 root root 4.0K Jan  4 16:48 .
drwxr-xr-x 6 root root 4.0K Jan  4 16:22 ..
-rw-r--r-- 1 root root 1.1K Jan  4 16:22 route-collector-example.conf.dist
-rw-r--r-- 1 root root  907 Jan  4 16:22 route-server-example.conf.dist
```

And alos .htaccess.dist missing under public/

Thanks
Fakrul

**Comment by barryo** [comment]
Hi @fakrul 

Please note that the more appropriate place for installation help is the mailing list - see: http://www.ixpmanager.org/support.php - I'll answer below and then close the issue. You can follow up on the list.

The actual answer is below but it would be more appropriate to install v4 at this point. While not officially released, it is production ready and in use at a couple IXPs. Beginnings of documentation can be found [here](https://ixp-manager.readthedocs.io/en/latest/admin/100-install.html) and we're happy to help on list.

Looks like you missed this bit from [section 02](https://github.com/inex/IXP-Manager/wiki/Installation-02-Downloading):

> NB: please checkout the v3.8 branch now as IXP Manager clone may use the in development v4 branch / master branch by default:
>
>     git checkout v3.8

Additional detail: https://www.inex.ie/pipermail/ixpmanager/2016-August/000784.html
