### ISSUE TITLE
database views and views.sql

### ISSUE THREAD

**Issue by aduitsis** [inex/IXP-Manager#287]
When importing a v3 database into an instance of IXP-Manager v4, one would typically use artisan doctrine:schema:update, etc, per the instructions. It may be that this does not create the necessary views in the db. Using views.sql to create the views is actually mentioned in the wiki, but not in https://ixp-manager.readthedocs.io/en/latest/admin/110-upgrade-from-v3.html. File schema-v3-to-v4.sql does not deal with views either. This was noticed while importing a v3 database from an old install for experimentation. Re-applying views.sql to get update-l2database.pl (which uses a particular view) to work was necessary.

Regarding clean installs, bootstrap.sh also does not install the views in a clean install and vagrant-base.sql does not include them.

**Comment by nickhilliard** [comment]
yep, the installation documention for v4 needs a lot of work and there are a bunch of things that aren't there, including this, but also configuring the config/ixp_tools.php file, the route servers and various other things.  We are aware of the issue.

Ultimately, views.sql will disappear as it's only used by the perl scripts, and there are only 4 of those left which are used in anger.  All the other perl scripts are obsolete or deprecated.

**Comment by aduitsis** [comment]
Hello and thanks for the response,

Slightly off-topic: Perl developer here, so I'd be happy to contribute. The good thing about the Perl parts is that they can be quite easily transferred to other machines along with their libraries without too much hassle. To make that even better, a small set of changes can be made that allows the Perl scripts and libraries to be run from a separate directory, without the need to install anything in other directories in a system. If you are interested, I can provide patches given a little time.

Re: this issue: Okay, clear enough, assuming it will be fixed / improved in time. You can close or keep the issue open at your discretion.

**Comment by nickhilliard** [comment]
I think the safest thing to do here is to assume that every upgrade needs views.sql to be executed.  Changes don't happen that often, but if they aren't done, then problems can emerge.

**Comment by nickhilliard** [comment]
documentation fixed in https://github.com/inex/ixp-manager-docs-md/commit/fa0dabeeb26b29858cd18857bb0ac30f43909233
