### ISSUE TITLE
JsonSchema takes into account only one vlan per connection 

### ISSUE THREAD

**Issue by aduitsis** [inex/IXP-Manager#290]
This was spotted by @zmousm and @aduitsis. We think it is probably a bug and we can issue a pull request if needed. Oddly enough, there is a comment in the relevant code actually implying out the alleged bug, so the authors might wish to first confirm that it is indeed a bug.

In JsonSchema.php:getMemberInfo ( relevant part: https://github.com/inex/IXP-Manager/blob/master/app/Utils/Export/JsonSchema.php#L247-L279 ), an iteration over vlan interfaces is being made. However, the $vlanentry array is initialized outside the iteration loop, so each successive loop is probably overwriting the previous $vlanentry keys. Finally and again outside the loop, the $vlanentry is being pushed only once into the vlan_list key of the $conn array. We believe $vlanentry should be pushed multiple times into an intermediate array (e.g. $vlanlist) and then that array used as the value of the vlan_list key.

**Comment by barryo** [comment]
Hi @aduitsis - thanks for pointing this out. It's now fixed.

Note that we still do not include private VLANs as this would not be relevant to the purpose of the JSON schema.
