### ISSUE TITLE
p2p stats broken after deleting virtual interface

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#294]
after deleting a vli from "Interfaces (Virtual)" the p2p stats page for all customers is broken, showing the "Oops something went wrong" page.

restarting memcached solves the issue. i had deleted everything in ixp/var/templates_c as well, not sure if that was needed or not.

**Comment by rasssta** [comment]
I'm on v3.7.3

**Comment by barryo** [comment]
Hi @rasssta - this isn't reproducible on v4 with Grapher.

I'm afraid we're no longer supporting v3 for bug fixes as we just don't have the resources.

If you cannot upgrade for internal reasons, we're happy to look at a pull request against the `release-v3` branch.
