### ISSUE TITLE
Changes to the IP management Screens

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#296]
I'd like to see the ability to do bulk modification (likely just deletion) to IP addresses, ie: selecting a group of ten and deleting them.

Also, when I have a search filter up and I delete an IP, I'd like it to return to the IP addresses screen with the filter in place. Now it goes back to that screen without the filter.

**Comment by barryo** [comment]
Hi @MHammett 

Thanks for that. I'm going to close this and have added it to the [ideas](https://github.com/inex/IXP-Manager/blob/master/IDEAS) file.

As a rule, we don't keep feature requests open that are not on our medium or short term goal list unless accompanied by a PR. In, say, the last ~8 years, we have only once needed to change IP addresses in bulk and that was a for a LAN renumbering and in that case it was quicker to execute a single SQL query than design out a UI for it. This doesn't mean we won't improve the handling of this, just that it won't happen as a dedicated short/medium term goal but rather more likely as a batch of feature improvements as we move stuff from ZF to Laravel.
