### ISSUE TITLE
Fresh Install Issues - PHP7.1 dependencies

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#298]
This was a fresh install. Loaded the standard template I've used on all other systems (including my other IXP 4.2 install). Entered the CT through the host. Ran WGET. Ran script.

I did a fresh install because of errors I was getting in the other container.

The installer quits before completion.

`Creating database and database users...mysql: [Warning] Using a password on the command line interface can be insecure.
[done]
Installing / updating composer - PHP's package manager...[done]
Creating .env file...[done]
Running composer to install PHP dependancies (please be patient)... root@ixpm:/#`

`===========================================================
Wed Mar  8 04:11:30 UTC 2017
===========================================================

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ocramius/proxy-manager 2.1.x-dev -> satisfiable by ocramius/proxy-manager[2.1.x-dev].
    - ocramius/proxy-manager 2.1.x-dev requires php ^7.1.0 -> your PHP version (7.0.15) does not satisfy that requirement.
  Problem 2
    - ocramius/proxy-manager 2.1.x-dev requires php ^7.1.0 -> your PHP version (7.0.15) does not satisfy that requirement.
    - doctrine/migrations dev-master requires ocramius/proxy-manager ^1.0|^2.0 -> satisfiable by ocramius/proxy-manager[2.1.x-dev].
    - Installation request for doctrine/migrations dev-master -> satisfiable by doctrine/migrations[dev-master].`

**Comment by barryo** [comment]
Sorry @MHammett - the req on 7.1 snuck in by accident. 

Welcome to life on the bleeding edge 😨
