### ISSUE TITLE
should update-l2database.pl skip switches with no snmp community ?

### ISSUE THREAD

**Issue by aduitsis** [inex/IXP-Manager#301]
When running ixptool -a switch-cli.snmp-poll, switches with no community set in the database are skipped, as explicitly explained in the debug output. 

The update-l2database.pl on the other hand, does not skip those switches. 

Worse still, a look at snmpopen function of Net_SNMP_util.pm from Net::SNMP Perl module, reveals that, absent a community, snmpopen is called with a hostspec like '@switchname' (instead of plain switchname). Which means that Net::SNMP->session will be called with community set to '' and the default value 'public' will probably not be used. Note, this is not strictly a bug in IXP-Manager, rather the Net_SNMP_Util does not handle this corner case.

The solution will probably be either to skip switches with absent a community string, aligning the update-l2database with the php tools' behavior or to explicitly set community to public when there's no community in the IXP database. I would dare say the first suggestion is better. 

Can provide (trivial) patch if necessary of course.

**Comment by nickhilliard** [comment]
oops, fixed in 05ef045.

Net_SNMP_Util is a horrible hack.  The only reason it's used is because the other snmp modules are also horrible.
