### ISSUE TITLE
PP: Cannot change partner duplex port on edit

### ISSUE THREAD

**Issue by barryo** [inex/IXP-Manager#307]
After setting a duplex port, we need to cease it and then re-create it to change the duplex port. It would be useful to be able to edit this.

Something like altering the logic in `store()` to the following plus adding code to handle the change.

```php
// display the duplex port if set or the list of all duplex ports available
$partnerPorts = D2EM::getRepository( PatchPanelPort::class )->getPatchPanelPortAvailableForDuplex( $ppp->getPatchPanel()->getId(), $ppp->getId() );

if( $ppp->hasSlavePort() ) {
    $partnerPorts = array_merge( [ $ppp->getDuplexSlavePortId() => $ppp->getDuplexSlavePortName() ], $partnerPorts );
}
```

**Comment by yannrobin** [comment]
+ adding possibility to remove a partner port from a patch panel port
