### ISSUE TITLE
Password Strength / 2fa

### ISSUE THREAD

**Issue by barryo** [inex/IXP-Manager#308]
From the mailing list: 

https://www.inex.ie/pipermail/ixpmanager/2017-March/001013.html

Herman Loennechen wrote:
> Is it possible to add requirements to the password policy?
> 
> As far as we can tell the current requirement is determined here in 
> ResetPassword.php:
> 
> ->addValidator( 'stringLength', false, array( 8, 30, 'UTF-8' ) )

Correct (there and one other place iirc).

> Is there / do you plan to support special characters, case sensitivity 
> etc. as a password requirement?

There are no plans. If there were, we'd need to also offer an opt out or configurability.

IMHO, we're not an application for the masses and deal with a very savvy audience (IXP customers) and I'm conflicting about imposing such restrictions on them.

I'm more interested in 2fa actually. But if/when we do 2fa, we'd also make password strength configurable. 

Auth is currently handled by the older framework and it needs to move to the newer one (Zend -> Laravel). Doing that would roll in 2fa. But, honestly, our development horizon is pretty full for the next three months.

**Comment by jamestutton** [comment]
We are in the process of doing a build with 2FA support.  It uses both TOTP and OTP passwords and its a rewrite of the current auth model so can be added with a few additional files and single line change. For our use case 2Fa is hard requirement so its built as 1 in all in model.

I will try to get it pushed back into a public repo in the next few weeks.

**Comment by barryo** [comment]
Sounds interesting! See [details on contributing here](https://github.com/inex/IXP-Manager/blob/master/CONTRIBUTING.md).

**Comment by barryo** [comment]
Will be handled as part of #354
