### ISSUE TITLE
clarification / consistency for switch.name vs switch.hostname

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#310]
`switch.hostname` should be used instead of `switch.name` in any location where there is a requirement to talk to the switch.  This is a problem in at least:

- `update-l2database.pl`
- `application/views/nagios-cli/conf/switch-templates.phtml`

**Comment by nschrenk** [comment]
I ran into this issue and modified update-l2database.pl to use switch.hostname instead of switch.name. The commit can be found at https://github.com/nschrenk/IXP-Manager/commit/6f07777246b4c702cff819cb74b4c9604a5674f0
Let me know if you'd like me to submit a pull request.

**Comment by nickhilliard** [comment]
- `application/views/nagios-cli/conf/switch-templates.phtml` obsolete due to laravel upgrade.

- `update-l2database.pl` fixed in https://github.com/inex/IXP-Manager/commit/11df3451219e0972bc0fccd60fc36e264b0ee42b.
