### ISSUE TITLE
Deleting Patch Panel Ports

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#311]
When you delete a patch panel, the ports in it aren't deleted.

**Comment by barryo** [comment]
Correct. Deleted patch panels are *soft deleted* on the assumption that you'll want some kind of archive of historical patch panels / cross connects.

I'm going to close this as I have your email requesting this and other features and will look at opening specific issues on them when I've had a chance to think them through.

**Comment by MHammett** [comment]
My specific issue is that as I learn the system, I have a ton of duplicate ports showing up.
![patch panel ports](https://cloud.githubusercontent.com/assets/12503490/24838083/989f3f7c-1d06-11e7-8eeb-75f836d9107b.PNG)

Above the line are from a panel that was deleted, below the line are from a current panel.

I hope I'm not seen as high maintenance or a whiner.  ;-)

**Comment by barryo** [comment]
Deleting ports was added a few weeks ago. Just FYI

**Comment by MHammett** [comment]
Thanks!
