### ISSUE TITLE
Graphing Documentation Update

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#312]
The "rrdtool" package is needed.

Also, I had to add "LANG=C" to the mrtg.sh script it says to run in cron.

**Comment by MHammett** [comment]
"librrds-perl" too

**Comment by MHammett** [comment]
Typos assumed in the sentence, "An example of hour to customise the MRTG..."

**Comment by nickhilliard** [comment]
typo fixed and pushed.

LANG=C is an operating system requirement on some linux variants.  This should be the default on Ubuntu cron.

The perl dependencies need to be checked separately using:

```
~/ixp-manager/tools% perl runtime/check-perl-dependencies.pl
```

**Comment by MHammett** [comment]
I have Ubuntu 16.04 and needed to set it, but maybe it has something to do with the container template I used.

"check-perl-dependencies.pl" doesn't exist in the 4.x documentation, but I'll run that now.
