### ISSUE TITLE
Adding IPv6 to Port

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#314]
I was adding a customer when I realized that I hadn't added my IPv6 addresses to this iteration of IXP Manager. I added the IPv6 range, then added it to the customer's port. I hit "save changes" on the Virtual Interface screen not knowing if I needed to save the changes on each "parent" menu on my way back to the top. I got this error. The addition of the IPv6 address to the port stuck, so maybe I got this because I made no changes on the screen I clicked "save changes" on?
[Adding IPv6 Error.txt](https://github.com/inex/IXP-Manager/files/908734/Adding.IPv6.Error.txt)

**Comment by barryo** [comment]
I think this has been fixed.
