### ISSUE TITLE
Add circuits to patch panels

### ISSUE THREAD

**Issue by 9simon** [inex/IXP-Manager#315]
We have sometimes larger circuits to connect something and it goes over multiple patch-panels. An example for such a circuit would be like:

switch1 Port3 wants to connect to router1 port10, which is located on a different floor/room. 

switch1 Port3 -> Patched to -> Rack A01, KEV5 Fiber 7 -> connects via a trunk cable to an other patch panel -> Rack X01 KEV 1 Fiber 7 -> Patched to -> X01 KEV2 Fiber 3 -> connects via trunk cable to another patchpanel on another floor -> X11 KEV1 Fiber 3 -> Patched to -> router1 port10

So it would be great to have the following:
- Front and backside of the ports / connectors of a patch panel
- Assignment of a patch panel port to another patchpanel port
- 1:1 linking of whole patch panel backside or frontside ports to another patch panel (or ranges of ports)

**Comment by barryo** [comment]
This type of circuit management functionality is why we had a number of aborted starts / over complicated this project / feature in the past.

On the redesign, we explicitly decided not to implement circuit management as it's too large and pushes outside the scope of both where we think IXP Manager fits and the functionality we were trying to create.

Thanks for the suggestion but I'm afraid we won't be implementing this functionality.
