### ISSUE TITLE
Mailing List Management Documentation Typo

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#316]
"we not longer recommend" should be "we no longer recommend"

**Comment by MHammett** [comment]
"cp config/mailinglists.php.dist config.mailinglists.php" should be "cp config/mailinglists.php.dist config/mailinglists.php"

**Comment by nickhilliard** [comment]
fixed in d23a2c6

**Comment by barryo** [comment]
Thanks for those @MHammett 

To try and further steam line this, I've created:

http://docs.ixpmanager.org/dev/docs/
