### ISSUE TITLE
Error in IXP Manager v4 on Ubuntu LTS 16.04

### ISSUE THREAD

**Issue by HarshadH** [inex/IXP-Manager#317]
We have used the below steps for IXP Manager v4 on Ubuntu LTS 16.04:-

#We have downloaded the script using below command:-
wget https://github.com/inex/IXP-Manager/raw/master/tools/installers/ubuntu-lts-1604-ixp-manager-v4.sh

#and executed it using below command:-
bash ./ubuntu-lts-1604-ixp-manager-v4.sh

But after following this steps, we are getting the below error:-
ERROR 1364 (HY000) at line 5: Field 'ixf_ix_id' doesn't have a default value

Could you please suggest me to resolve this issue.

**Comment by nickhilliard** [comment]
You need to add in your IX-F IXP ID from https://db.ix-f.net/api/ixp.  If your IXP doesn't have an IX-F ID yet, you will need to email secretariat /at/ euro-ix.net to ask them to add you.

**Comment by HarshadH** [comment]
Can you please give detailed information on how can I get an IX-F ID from secretariat /at/ euro-ix.net & how can I add my IX-F IXP ID from https://db.ix-f.net/api/ixp or can you provide me the exact solution.

**Comment by barryo** [comment]
Apologies. This was actually due to a database schema issue which was fixed with the above commit.

If you run the command again, it should work.
