### ISSUE TITLE
allow customers to view / set reverse DNS for IP and also port status in ports view

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#32]
Would like an option to allow customers to view, and eventually set their own reverse DNS in the ports view page.

Also display the port status e.g "Connected/Awaiting X-Connect/Quarantine" might be useful in customer page.

**Comment by listerr** [comment]
any progress on this?

**Comment by barryo** [comment]
In motion. Plan is to have something concrete for Euro-IX in April.

**Comment by barryo** [comment]
All covered in the longer term TODOs and as part of [core v4 development](http://www.barryodonovan.com/2014/09/15/ixp-manager-planning-for-v4) -> closing.
