### ISSUE TITLE
Routers page not looking right...

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#321]
[IXP Manager Routers Page.pdf](https://github.com/inex/IXP-Manager/files/971890/IXP.Manager.Routers.Page.pdf)
![ixp manager routers page](https://cloud.githubusercontent.com/assets/12503490/25637744/b4856516-2f4b-11e7-8905-5dfaaf64b304.PNG)

**Comment by barryo** [comment]
@MHammett - this is an `APP_URL` issue in `.env`.
