### ISSUE TITLE
reseller uplink interface

### ISSUE THREAD

**Issue by aduitsis** [inex/IXP-Manager#324]
Hi,

Not sure whether this qualifies as a bug or is intended behaviour, so please bear. The problem is relevant with the procedure that must be followed to set a switch port as a reseller uplink.

If a switch port has already been marked as type reseller from the switch ports menu, then it doesn't appear in the available interfaces list when trying to add it to a reseller via the add interface wizard.

To workaround, one has to set the port's type to unset, then add it to the reseller via the interface wizard, then go again to the switch ports menu and change its type back to reseller.

I would respectfully submit that even when a port is already of type reseller, it should still be possible to associate with a specific reseller without having to temporarily set its type to unset.

Your opinion on whether this is indeed a bug would be highly appreciated.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.
