### ISSUE TITLE
Configuration management switch

### ISSUE THREAD

**Issue by AleksBelytskyi** [inex/IXP-Manager#328]
Hi,

Probably this wrong way to ask such question here, but I don't know another way.

Is it possible to manage a configuration of the switch ports by IXP Manager?
Set up a port description,  admin status of ports, VLAN on ports, etc. through the admin panel.
I can find nothing about this in the documentation and in configuration files of the IXP Manager.

Thank you in advance.

IXP Manger V4.5.0

**Comment by barryo** [comment]
Hi @AleksBelytskyi 

The mailing list is the best place for this:

https://www.inex.ie/mailman/listinfo/ixpmanager

and this conversation just came up recently:

https://www.inex.ie/pipermail/ixpmanager/2017-June/001101.html

(read the whole thread).

**Comment by AleksBelytskyi** [comment]
Hi @barryo 

Thank you for the fast reply and links for my question.
I will read this.
