### ISSUE TITLE
v4 p2p graph problem

### ISSUE THREAD

**Issue by melkior** [inex/IXP-Manager#332]
Hi,

after v3 -> v4 upgrade everything seems ok except one thing. One customer pointed out at their p2p graphs and said there could be a problem.

Avg out (green) is overwriting avg in (blue) as seen in this image

![grapher-sflow-bits-day-ipv4](https://user-images.githubusercontent.com/1012754/28871418-c91d4490-7784-11e7-94f4-1b5b4b53284c.png)

This is daily p2p graph with other customer and is not an isolated example. If avg in is smaller than avg out, then avg in is being overwritten.

Is there any way to fix this?

Thank you

**Comment by barryo** [comment]
It's the ordering within the RRD generation.

I have it fixed on my local dev copy but need to knock it into shape. Heading off on ~2 weeks holidays and will get it pushed when I'm back.

**Comment by melkior** [comment]
Ok, nice. I'm also going on holidays and will check changes after.

Thanks

**Comment by melkior** [comment]
Hi,

just curious, is this committed? I would like to apply this specific change to my current .deb package. Can you point where to look? Thanks

**Comment by barryo** [comment]
Hi @melkior 

Just pushed b1b33e7d45459b440fc141c250a9dfbdce14526f now which fixes this.

Sorry for the delay.

**Comment by melkior** [comment]
Backported and it works. Thanks
