### ISSUE TITLE
/ipvX-address/add

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#333]
the handler for creating new IP addresses is too simplistic in that it doesn't check whether the resulting IP addresses are legitimate.  E.g. if you tell the system to create 512 IPv4 addresses starting at 1, it will create x.x.x.1 to x.x.x.512.

**Comment by barryo** [comment]
This is fixed in the new Laravel controllers in [v4.7.0](https://github.com/inex/IXP-Manager/releases/tag/v4.7.0).
