### ISSUE TITLE
Can't add new customers

### ISSUE THREAD

**Issue by kylespencer** [inex/IXP-Manager#334]
When attempting to add new customers via http://196.49.15.198/default/customer/add/id/ I receive an "unexpected error" with the following logfile entry:

> ************************************************************************
> ****************************** EXCEPTIONS *******************************
> ************************************************************************
> 
> --------------------------- EXCEPTION --------------------------
> 
> Message: An exception occurred while executing 'INSERT INTO cust (name, type, shortname, abbreviatedName, autsys, maxprefixes, peeringemail, nocphone, noc24hphone, nocfax, nocemail, nochours, nocwww, peeringmacro, peeringmacrov6, peeringpolicy, corpwww, datejoin, dateleave, status, activepeeringmatrix, peeringDb, lastupdated, lastupdatedby, creator, created, MD5Support, isReseller, irrdb, company_registered_detail_id, company_billing_details_id, reseller) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Liquid Telecom", "1", "liquid", "Liquid Telecom", "", "", "", "", "", "", "", "0", "", "", "", "selective", "https:\/\/www.liquidtelecom.com\/", "2017-09-07", null, "1", "1", null, null, null, "kspencer", "2017-09-07", "UNKNOWN", 0, 4, 2, 2, null]:
> 
> SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'autsys' at row 1
> Line: 115
> File: /srv/ixpmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
> 
> Trace:
> 
> #0 /srv/ixpmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
> #1 /srv/ixpmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO cus...', Array)
> #2 /srv/ixpmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
> #3 /srv/ixpmanager/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
> #4 /srv/ixpmanager/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
> #5 /srv/ixpmanager/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
> #6 /srv/ixpmanager/library/OSS/Controller/Action/Trait/Doctrine2Frontend.php(625): Doctrine\ORM\EntityManager->flush()
> #7 /srv/ixpmanager/library/OSS/Controller/Action/Trait/Doctrine2Frontend.php(709): IXP_Controller_Frontend->addProcessForm(Object(IXP_Form_Customer), Object(Entities\Customer), false)
> #8 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): IXP_Controller_Frontend->addAction()
> #9 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
> #10 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> #11 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
> #12 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
> #13 /srv/ixpmanager/app/Exceptions/Handler.php(59): Zend_Application->run()
> #14 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(82): IXP\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
> #15 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
> #16 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #17 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
> #18 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #19 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #20 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
> #21 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #22 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #23 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
> #24 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #25 /srv/ixpmanager/app/Http/Middleware/UrlResolver.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #26 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): IXP\Http\Middleware\UrlResolver->handle(Object(Illuminate\Http\Request), Object(Closure))
> #27 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #28 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #29 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
> #30 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #31 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #32 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #33 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
> #34 /srv/ixpmanager/public/index.php(84): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #35 {main}
> 
> Array
> (
>     [0] => Array
>         (
>             [file] => /srv/ixpmanager/library/OSS/Controller/Trait/Error.php
>             [line] => 78
>             [function] => compact_debug_backtrace
>             [class] => OSS_Debug
>         )
> 
>     [1] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php
>             [line] => 516
>             [function] => errorAction
>             [class] => ErrorController
>         )
> 
>     [2] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php
>             [line] => 308
>             [function] => dispatch
>             [class] => Zend_Controller_Action
>         )
> 
>     [3] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php
>             [line] => 954
>             [function] => dispatch
>             [class] => Zend_Controller_Dispatcher_Standard
>         )
> 
>     [4] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php
>             [line] => 105
>             [function] => dispatch
>             [class] => Zend_Controller_Front
>         )
> 
>     [5] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application.php
>             [line] => 384
>             [function] => run
>             [class] => Zend_Application_Bootstrap_Bootstrap
>         )
> 
>     [6] => Array
>         (
>             [file] => /srv/ixpmanager/app/Exceptions/Handler.php
>             [line] => 59
>             [function] => run
>             [class] => Zend_Application
>         )
> 
>     [7] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 82
>             [function] => render
>             [class] => IXP\Exceptions\Handler
>         )
> 
>     [8] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 32
>             [function] => handleException
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [9] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
>             [line] => 30
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [10] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
>         )
> 
>     [11] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [12] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
>             [line] => 30
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [13] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
>         )
> 
>     [14] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [15] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
>             [line] => 27
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [16] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\ValidatePostSize
>         )
> 
>     [17] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [18] => Array
>         (
>             [file] => /srv/ixpmanager/app/Http/Middleware/UrlResolver.php
>             [line] => 58
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [19] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => IXP\Http\Middleware\UrlResolver
>         )
> 
>     [20] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [21] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php
>             [line] => 46
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [22] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode
>         )
> 
>     [23] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [24] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 102
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [25] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
>             [line] => 149
>             [function] => then
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [26] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
>             [line] => 116
>             [function] => sendRequestThroughRouter
>             [class] => Illuminate\Foundation\Http\Kernel
>         )
> 
>     [27] => Array
>         (
>             [file] => /srv/ixpmanager/public/index.php
>             [line] => 84
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Kernel
>         )
> 
> )

[ixp-manager-errors-1.txt](https://github.com/inex/IXP-Manager/files/1284307/ixp-manager-errors-1.txt)

**Comment by barryo** [comment]
Hey @kylespencer - looks like we need a better UX here (will keep open to resolve) but looks like the issue is a blank ASN?

**Comment by kylespencer** [comment]
Error still occurs even with ASN.

--
Cell/WhatsApp/Signal: +256790884905

**Comment by kylespencer** [comment]
Here's what I get when I insert an ASN. Appears to be a different error?

> ************************************************************************
> ****************************** EXCEPTIONS *******************************
> ************************************************************************
> 
> --------------------------- EXCEPTION --------------------------
> 
> Message: Invalid controller specified (favicon.ico)
> Line: 248
> File: /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php
> 
> Trace:
> 
> #0 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> #1 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
> #2 /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
> #3 /srv/ixpmanager/app/Exceptions/Handler.php(59): Zend_Application->run()
> #4 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(82): IXP\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
> #5 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
> #6 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #7 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
> #8 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #9 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #10 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
> #11 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #12 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #13 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
> #14 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #15 /srv/ixpmanager/app/Http/Middleware/UrlResolver.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #16 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): IXP\Http\Middleware\UrlResolver->handle(Object(Illuminate\Http\Request), Object(Closure))
> #17 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #18 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #19 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
> #20 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #21 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #22 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #23 /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
> #24 /srv/ixpmanager/public/index.php(84): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #25 {main}
> 
> Array
> (
>     [0] => Array
>         (
>             [file] => /srv/ixpmanager/library/OSS/Controller/Trait/Error.php
>             [line] => 78
>             [function] => compact_debug_backtrace
>             [class] => OSS_Debug
>         )
> 
>     [1] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php
>             [line] => 516
>             [function] => errorAction
>             [class] => ErrorController
>         )
> 
>     [2] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php
>             [line] => 308
>             [function] => dispatch
>             [class] => Zend_Controller_Action
>         )
> 
>     [3] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php
>             [line] => 954
>             [function] => dispatch
>             [class] => Zend_Controller_Dispatcher_Standard
>         )
> 
>     [4] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php
>             [line] => 105
>             [function] => dispatch
>             [class] => Zend_Controller_Front
>         )
> 
>     [5] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/zendframework/zendframework1/library/Zend/Application.php
>             [line] => 384
>             [function] => run
>             [class] => Zend_Application_Bootstrap_Bootstrap
>         )
> 
>     [6] => Array
>         (
>             [file] => /srv/ixpmanager/app/Exceptions/Handler.php
>             [line] => 59
>             [function] => run
>             [class] => Zend_Application
>         )
> 
>     [7] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 82
>             [function] => render
>             [class] => IXP\Exceptions\Handler
>         )
> 
>     [8] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 32
>             [function] => handleException
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [9] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
>             [line] => 30
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [10] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
>         )
> 
>     [11] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [12] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
>             [line] => 30
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [13] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
>         )
> 
>     [14] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [15] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
>             [line] => 27
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [16] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\ValidatePostSize
>         )
> 
>     [17] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [18] => Array
>         (
>             [file] => /srv/ixpmanager/app/Http/Middleware/UrlResolver.php
>             [line] => 58
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [19] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => IXP\Http\Middleware\UrlResolver
>         )
> 
>     [20] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [21] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php
>             [line] => 46
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [22] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 148
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode
>         )
> 
>     [23] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
>             [line] => 53
>             [function] => Illuminate\Pipeline\{closure}
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [24] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
>             [line] => 102
>             [function] => Illuminate\Routing\{closure}
>             [class] => Illuminate\Routing\Pipeline
>         )
> 
>     [25] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
>             [line] => 149
>             [function] => then
>             [class] => Illuminate\Pipeline\Pipeline
>         )
> 
>     [26] => Array
>         (
>             [file] => /srv/ixpmanager/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
>             [line] => 116
>             [function] => sendRequestThroughRouter
>             [class] => Illuminate\Foundation\Http\Kernel
>         )
> 
>     [27] => Array
>         (
>             [file] => /srv/ixpmanager/public/index.php
>             [line] => 84
>             [function] => handle
>             [class] => Illuminate\Foundation\Http\Kernel
>         )
> 
> )
> 
> 
> ------------------------
> 
> HTTP_HOST : 196.49.15.198
> HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
> HTTP_COOKIE: PHPSESSID=0ja1m6e7jc6k7r70m0ca3puit3
> REMOTE_PORT: 49669
> REQUEST_METHOD: GET
> REQUEST_URI: /favicon.ico
>

**Comment by barryo** [comment]
@kylespencer - not sure why the form validation is working but assume you need to put something in every box (that isn't a checkbox!) and see if it works.

**Comment by barryo** [comment]
@kylespencer - or actually, to be more specific, if you fill ASN and max prefixes it should work.

It's critical that Date Left be left blank btw.

**Comment by barryo** [comment]
@yannrobin - I suspect the issue is that ZF is trying to insert an empty string as an empty string rather than as `null`. 

Separately if the customer type is anything but pro-bona, an integer value for autsys should be required and it should be unique in the database.

Can you have a look at this on the inex/IXP-Manager repo (create an issue branch off master).

**Comment by yannrobin** [comment]
@barryo I will have a look an that
