### ISSUE TITLE
Can't add customer join date before 2007

### ISSUE THREAD

**Issue by kylespencer** [inex/IXP-Manager#335]
The "Add Customer" screen only allows join dates after 2007. Many of my IXP customers joined in 2001. Some IXPs in Africa date back to 1996. Need to allow for older dates/years.

**Comment by kylespencer** [comment]
Nevermind. Somehow my interf

**Comment by kylespencer** [comment]
It seems that, initially, the year selection dropdown is limited to 2007 and later. However, if you manually press the "left" button on the calendar to move back to an earlier date, the drop-down list repopulates with older years (i.e. before 2007).

**Comment by barryo** [comment]
As you point out it works and it actually works as expected:

http://api.jqueryui.com/datepicker/#option-yearRange

**Comment by kylespencer** [comment]
It's buggy. The first time you click the dropdown it only goes back to
2007. Subsequent interactions allow earlier years.

--
Cell/WhatsApp/Signal: +256790884905

**Comment by barryo** [comment]
See [link above (or click here)[(http://api.jqueryui.com/datepicker/#option-yearRange). This is how it's meant to work. 

Agree it's not initially intuitive but seems to work for jQuery UI users. What you call bug I'm betting they'll call feature 😜 

I've looked at alternatives and they all have their own quirks.

**Comment by kylespencer** [comment]
Right; perhaps set the initial range so that it goes back to the date of
the first IXP? In Africa we have some old ones. JINX was 96?

--
Cell/WhatsApp/Signal: +256790884905

**Comment by barryo** [comment]
Nah, I tried that and the experience was more naff. We'll revisit when we port to Laravel which uses newer UI libraries.

**Comment by kylespencer** [comment]
Noted :)

--
Cell/WhatsApp/Signal: +256790884905
