### ISSUE TITLE
Allow customers to see each other's graphs

### ISSUE THREAD

**Issue by htrosvik** [inex/IXP-Manager#336]
Would be very useful if there was a way to allow customers to see each other's traffic graphs.

**Comment by kylespencer** [comment]
I also think it would be useful to (optionally) allow customers to see each other's graphs.

In addition, it would be useful to be able to create separate read-only user accounts which can see per-network traffic statistics. My regulator, for example, would like to be able to see that data but I do not want them to have access to any other parts of IXP Manager.

**Comment by rfc1036** [comment]
This would be useful, since in Italy it has always been customary to show the port graphs to all other IX members and I would like to continue in the tradition for MINAP.
But this feature would also needs a blacklist, because a few big networks have strong policies against this and ask to opt-out.

**Comment by barryo** [comment]
> In addition, it would be useful to be able to create separate read-only user accounts which can see 
> per-network traffic statistics. My regulator, for example, would like to be able to see that data but I 
> do not want them to have access to any other parts of IXP Manager.

On this - I have three problems:

1. the actual usefulness of such a feature.
2. the precedence and premise that a regulator should have/need such access.
3. the complication of actually implementing.

If the regulator needs this information, it should be to satisfy some legal requirement. E.g. *the incumbent must peer*. This can be demonstrated with the peering matrix or even just a PDF print of the members graphs.

In any case, due to (3), this won't make the development list I'm afraid.

**Comment by steiostb** [comment]
> On this - I have three problems:
> 
>     the actual usefulness of such a feature.
>     the precedence and premise that a regulator should have/need such access.
>     the complication of actually implementing.
> 
> If the regulator needs this information, it should be to satisfy some legal requirement. E.g. the incumbent must peer. This can be demonstrated with the peering matrix or even just a PDF print of the members graphs.
> 
> In any case, due to (3), this won't make the development list I'm afraid.

Is your comment only for kylespencer`s request? Do you have any thought of htrosvik`s request? Is it possible and do you have any time schedule?

**Comment by barryo** [comment]
@steiostb - that related purely to @kylespencer's request for: *In addition, it would be useful to be able to create separate read-only user accounts*.

@yannrobin is currently working on migrating the statistics graphs from ZendFramework to Laravel and if it's feasible to add this as part of that, we'll do it quickly and release before end of March.

**Comment by steiostb** [comment]
@barryo - Any info on when this feature will be available?

**Comment by steiostb** [comment]
@barryo Do you have any news on this feature? This should have been implemented for some time ago? Our customers are really missing this feature.

**Comment by barryo** [comment]
Hi @steiostb - this will be in v4.8 which - depending on documentation and quality control - should be released by end of May. 

90% of the coding work is finished and most of the documentation.

**Comment by barryo** [comment]
Documentation of this feature is ready here:

https://docs.ixpmanager.org/grapher/api/

Feedback and comments welcome.

**Comment by kylespencer** [comment]
Looks good! Thank you!

--
Cell/WhatsApp/Signal: +256790884905

**Comment by rfc1036** [comment]
I know that some networks are very sensitive about publishing their traffic levels even just to other IX members, so I would be able to use this (and I really want to!) only if it were possible to blacklist some customer's graphs to the "own_graphs_only" level.

**Comment by steiostb** [comment]
@barryo - Thank you for your reply! We have an IX-meeting on May 28, and would be very grateful if this was available by then.

**Comment by barryo** [comment]
Implemented in v4.8.0 which we plan to push later this week.
