### ISSUE TITLE
Junos template as route server?

### ISSUE THREAD

**Issue by vlelin** [inex/IXP-Manager#337]
subj?

**Comment by nickhilliard** [comment]
Junos doesn't support rfc7947, so cannot operate as a proper route server.

**Comment by vlelin** [comment]
Hello,

https://www.juniper.net/documentation/en_US/junos/topics/concept/bgp-route-server-overview.html

**Comment by nickhilliard** [comment]
interesting - we weren't aware of this.  There are no sample configuration on the juniper web site at the moment, but we would be interested in including a template.

**Comment by maelmans** [comment]
Who can I contact to talk about what is needed to get JUNOS supported in IXP Manager?

**Comment by barryo** [comment]
Hey @maelmans 

We've actually looked at this but it's, well, not simple. You can see sample configs here for [ipv4](https://github.com/inex/IXP-Manager/blob/master/data/travis-ci/known-good/ci-apiv4-b2-rc1-lan1-ipv4.conf) and [ipv6](https://github.com/inex/IXP-Manager/blob/master/data/travis-ci/known-good/ci-apiv4-b2-rc1-lan1-ipv6.conf).

We would ideally need to find some way of making feature parity with Bird which means looking glass, querying filtered prefixes and why, etc. Some of our presentations from 2019 would also be a good place to look: https://www.ixpmanager.org/presentations

It would no doubt be possible to get IXP Manager to spit out a basic configuration for JunOS but I think without feature parity it wouldn't be particularly useful. That's just me though.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.
