### ISSUE TITLE
Mailing list API returns duplicate addresses

### ISSUE THREAD

**Issue by kylespencer** [inex/IXP-Manager#339]
Both "subscribed" and "unsubscribed" API outputs give duplicate values for all e-mail addresses.

curl -f "https://www.example.com/ixp/apiv1/mailing-list/get-subscribed/key/$MyKey/list/members" returns

user96@domain.com
user96@domain.com

When the user leaves the same mailing list via IXP manager, it removes both addresses.

**Comment by barryo** [comment]
I suspect mailman is pretty agnostic about having an email presented >1 time? That is to say, I expect the operation is idempotent.

When I look at our own system, I get:

```
# curl -sf "$URL/apiv1/mailing-list/get-subscribed/key/$KEY/list/tech" | sort | wc -l
     161
# curl -sf "$URL/apiv1/mailing-list/get-subscribed/key/$KEY/list/tech" | sort | uniq | wc -l
     148
```

The difference (13 addresses) are people with more than one account (username) but using the same email address. 

Are you sure you don't have the same issue? What do similar commands give you?

**Comment by kylespencer** [comment]
Ah. Yes. That was my issue. Thanks for the tip. I altered my cron script to
remove duplicates anyway so no harm :)

--
Cell/WhatsApp/Signal: +256790884905

On 19 Sep 2017 4:11 p.m., "barryo" <notifications@github.com> wrote:

I suspect mailman is pretty agnostic about having an email presented >1
time? That is to say, I expect the operation is idempotent.

When I look at our own system, I get:

# curl -sf "$URL/apiv1/mailing-list/get-subscribed/key/$KEY/list/tech"
| sort | wc -l
     161
# curl -sf "$URL/apiv1/mailing-list/get-subscribed/key/$KEY/list/tech"
| sort | uniq | wc -l
     148

The difference (13 addresses) are people with more than one account
(username) but using the same email address.

Are you sure you don't have the same issue? What do similar commands give
you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/inex/IXP-Manager/issues/339#issuecomment-330534140>,
or mute
the thread

**Comment by barryo** [comment]
Cool. It's not an ideal situation but, as I mentioned, that functionality comes with some caveats 😉
