### ISSUE TITLE
Customer website URLs break links unless HTTP:// is prepended

### ISSUE THREAD

**Issue by kylespencer** [inex/IXP-Manager#340]
In the customer details screen, there is a field for "Corporate website" that expects a website URL. If "http://" is not prepended, various links in IXP manager break (e.g. /customer/details).

System should add http:// if missing from user entry, or otherwise assume the entry is an absolute URL in all places where it is referenced.

**Comment by yannrobin** [comment]
This issue will be fixed in the next version of ixp-manager.

@barryo managed in dev
