### ISSUE TITLE
Can't delete an interface/vlan-if when l2address is assigned

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#341]
Trying to delete a virtual interface or vlan-if results in the following error as long as there's an l2address assigned to the vlan-if:

An exception occurred while executing 'DELETE FROM vlaninterface WHERE id = ?' with params [61]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ixpng`.`l2address`, CONSTRAINT `FK_B9482E1D6AB5F82` FOREIGN KEY (`vlan_interface_id`) REFERENCES `vlaninterface` (`id`))

**Comment by barryo** [comment]
This is fixed in our dev branch. Can you just manually delete the row? It's not back-portable as it's brand new controllers.

**Comment by rasssta** [comment]
I fixed it by removing the related l2address first and then delete it. Just thought you should know :)

**Comment by barryo** [comment]
Cool @rasssta. We'll be pushing v4.6 shortly.
