### ISSUE TITLE
MAC/L2 Addresses

### ISSUE THREAD

**Issue by apolyr** [inex/IXP-Manager#344]
The "MAC/L2 Addresses" menu is confusing. 

MAC addresses and L2 addresses are the same thing in our context, but they are used to distinguish between configured and discovered mac addresses.

I propose that the menu is renamed to "MAC Addresses", with submenus "Configured MACs" and "Discovered MACs".

**Comment by barryo** [comment]
Sounds good, will do.

Are you aware of this by the way: http://docs.ixpmanager.org/features/layer2-addresses/

**Comment by apolyr** [comment]
Nope, I was not. Thanks.
