### ISSUE TITLE
Contact group / role that user can change?

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#345]
Hello,

Is it possible to add a type of contact group similar to the existing ROLE function that the user is allowed to change from their account (currently only the admin account can change the roles for a contact, users cannot change these in their profile, they are greyed out.)

Rob

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.
