### ISSUE TITLE
No Patch Panel auto-select for Duplex partner in 4.6.0

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#347]
In 4.6.0 it doesn't automatically select the most likely partner port automatically as it did in 4.5.0. I.e. if I try to allocate port 7 I want it to auto-select port 8 as partner port when I check "duplex".

Quite annoying since I have 98% duplex ports.

Also, possibly related, I can't select port 8 straight away. I need to check another port first, then I can select port 8. Otherwise it will just keep on showing "Choose a partner port".

Also, "Physical Interface Status" is impossible to set to "Connected" directly when allocating a port. If I select "Disabled" I can then select "Connected".

**Comment by barryo** [comment]
Main issue fixed in 3a8fff1461066980378f8b23580cabf18c38aa36 which should also fix the secondary issue.
