### ISSUE TITLE
Login Passwords are stored and can be browsed in plaintext

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#35]
The passwords are not hashed in any way during use, or in the database. This is problematic for two reasons:
- The superuser can browse all of the users' login passwords.
- If there is a vulnerability (e.g. sql-injection) in any of IXP-Manager's code it would then require no extra work to access/expose all login details.

**Comment by nickhilliard** [comment]
you don't. It hasn't been present in IXP Manager since version 4.x
