### ISSUE TITLE
euro-ix json schema export [mac_addresses field]

### ISSUE THREAD

**Issue by robertjakub** [inex/IXP-Manager#352]
the field mac_addresses is wrong spelled in the export file (app/Utils/Export/JsonSchema.php) according to the euroix-json-schema. 

also: the format of the mac_address should be: lowercase string xx:xx:xx:xx:xx:xx) (but this is cosmetic, the both formats can/should be allowed in the schema)

**Comment by barryo** [comment]
Thanks again @robertjakub

**Comment by robertjakub** [comment]
but still - what about the format of the mac address ? there is a lowercase string with delimiter ':' between. I found, that IXPManager exports this without the delimiters. so - we should allow both formats in the schema.

**Comment by barryo** [comment]
Sorry, missed the formatting bit completely.

It's best to be prescriptive about what goes into the schema and the schema says: *(format: lowercase string xx:xx:xx:xx:xx:xx)*. 

I've fixed IXP Manager now and - as you say - anyone who needs it otherwise can just normalise it.

**Comment by robertjakub** [comment]
((-; thank you. 

It comes from the quick dirty work on the json schema I found on the ml.ix-f database.
I think - we should flag this change. This change can broke the others scripts.

**Comment by barryo** [comment]
> I think - we should flag this change

Yip, we'll add it to the release notes once we stamp the next version of IXP Manager.

I think it's less of a headache when fixing to conform to the standard rather than working against it ;-)
