### ISSUE TITLE
Feature request: Error message when requesting password for non-existing account

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#353]
At STHIX we've started to see a trend where people forget the username/e-mail they registered with, which mean that they will request a password reset.

The issue is that if they do the request for a non-existing e-mail/username (many customers have noc@ / peering@ / admin@ / etc. and forget which one they use for our portal) they don't get an error message, which makes them believe it's an e-mail related issue causing some troubleshooting on both their and our end.

Would it be possible to add an error message instead of "If your email matches user(s) on the system, then an email listing those users has been sent to you."?

I guess it's designed like this with security in mind. But I don't think this is a security issue. If that's the reason, please elaborate to convince me :-)

**Comment by barryo** [comment]
> I guess it's designed like this with security in mind. But I don't think this is a security issue. If that's the reason, please elaborate to convince me :-)

That was (is) certainly the reasoning here. Less on IXP Manager but more that it comes up from the underlying framework (OSS_Framework) we have been using which is also used in other applications where they did not want to leak whether an email address is or is not subscribed to the service. 

Looking at the code, this protection is only skin deep (user's can be exposed by *limit of password reset tokens has been reached* error message or timing attacks).

As you say - and I agree - this is not important for IXP Manager.

The underlying framework is well past end of life and is being removed along with Zend Framework (4.7 will remove a huge chunk!). So, I won't fix it in this but, during Q1 2018 we will be migrating all the auth code to Laravel (including looking at OAuth with PeeringDB in #322 ) and I'll ensure to give the correct feedback then.

Incidentally - the overall **draft** ideas here are:

* remove usernames altogether in favour of email addresses
* allow an email address to be linked to >=1 customer (single login like the current RIPE LIR portal for example)
* remove the CUSTADMIN user and instead make all existing users CUSTADMINs which will mean read/write access and make the new CUSTUSER class read only.
