### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by nzurku** [inex/IXP-Manager#355]
Hello, I've tried both the automated install and the manual install, and I'm coming across a few errors.
OS: Fresh Ubuntu 16.04

php-yaml and php-ds are not installable.

- php-yaml can be installed doing the following: https://github.com/xy2z/PineDocs/wiki/Install-YAML-extension-for-PHP-7.0-(Windows---Ubuntu) or `pecl install yaml`
- php-ds can be installed with: `pecl install ds`

Now, the real breaker bug is seen here:

> root@portal:/srv/ixpmanager# php artisan doctrine:schema:create
> Mailing list functionality is disabled. See: http://docs.ixpmanager.org/features/mailing-lists/

`php artisan doctrine:schema:create` will run, but it won't do anything from what I can see. It posts the unrelated mailinglist warning.

This breaks the automated script and also the manual install, as the mysql DB will not have any tables.

Are these known issues with the installer, and are any of them related?

**Comment by barryo** [comment]
> php artisan doctrine:schema:create will run, but it won't do anything from what I can see. It posts the unrelated mailinglist warning.

ack, apologies for this. It snuck in due to a conflation of two issues:

1. In our test environment, we have mailing list functionality enabled 
2. we recently upgraded to Laravel 5.5 which has Artisan command autodiscovery which hits the constructor.

**Comment by barryo** [comment]
As for the php-yaml and php-ds issues, I'll sort those in the script shortly.

**Comment by barryo** [comment]
sorry @nzurku - I should have said, simply rerunning the script *should* get you up and running. I'm going through the process now to test though.

**Comment by nzurku** [comment]
No problem, so on a fresh system the installer dies here:

> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package php-yaml

...but that's expected right now I assume.

To resolve, I ran these: 

`apt install libyaml-dev php-pear php7.0-dev`
`pecl install ds`
`pecl install yaml` <-- required "autodetect" default used, had to press Enter

I removed php-yaml from the apt-get in the installer script.

At this point, the installer has appeared to complete and I'm up and running!

Thanks for your help! Let me know if you need any more details.

**Comment by barryo** [comment]
Thanks again for bringing these to our attention @nzurku 

I fixed the php-ds and php-yaml issues using the semi-official PHP ppa as per the above commit. Gets around having to compile them.

Works cleanly for me now.
