### ISSUE TITLE
sflow-to-rrd-handler 

### ISSUE THREAD

**Issue by openbsod** [inex/IXP-Manager#357]
Hello.

Met some problems during initial configuration of IXP-Manager. One of them is dealing with sflow-to-rrd-handler.

![sflow-rrd-handler](https://user-images.githubusercontent.com/19532554/32804450-257f9980-c998-11e7-9ff3-7b9921ab9f48.png)

Digging with wiki/Peering-Matrix and wiki/Installing-Sflow-Support but still no luck. 

IXP Manager V4.7.0

**Comment by barryo** [comment]
Hi! 

Could we please ask you to take this to the mailing list? 

Details on [support in general can be found here](https://www.ixpmanager.org/support.php) and a direct link to the mailing list is: https://www.inex.ie/mailman/listinfo/ixpmanager

The reason for this is that GitHub Issues is for bugs and feature requests and is mostly only seen by the developers and a smaller circle of people interested in the development side. The mailing list has a wider subscription of users of IXP Manager and you will find assistance quicker on that forum.

Thanks for your understanding!

Barry [@barryo]
