### ISSUE TITLE
FR: Customer want to see their aggregated IPv4 vs IPv6 traffic

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#358]
I have many customers who have asked me if it's possible to see their aggregated IPv4 vs IPv6 traffic. The data is there (sflow individual RRDs), so it's "only" a matter of presentation.

**Comment by rasssta** [comment]
And also a summary of v4 vs v6 for the total IXP traffic.

**Comment by barryo** [comment]
Hey @rasssta - this is all on the development plans for 2018 as part of the p2p graphs and member login portal overhaul.

I'm going to close this as it's coming and planned for!

I'm not 100% sure about exact delivery times, but it's definitely 2018 and most likely by end of Q2.

Please follow up if you have any questions.

Barry
