### ISSUE TITLE
Can't delete configured MAC address

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#361]
After adding another MAC address for a VLAN interface I tried to remove the old MAC but got the following error message:

"Could add MAC address. API / AJAX / network error"

That's a quite odd message...

Running 4.6.1.

**Comment by rasssta** [comment]
Nevermind. Seems to be fixed in 4.7.0.

**Comment by nickhilliard** [comment]
the error message needs to be made clearer here
