### ISSUE TITLE
The "routeserver" type customer appears as "unknown" in customer list.

### ISSUE THREAD

**Issue by digitalandrei** [inex/IXP-Manager#364]
Hello,

In the documentation related to "Route Servers" added as "Customers" it is specified the customer should be added as type "Internal", but we see there is also the type "Routeserver" available. When using that type we see it as "Unknown" type in customer listing page (/customer/list). In customer overview page it is displayed properly.

This is "/customer/overview/id/#" page:

<img width="480" alt="screen shot 2017-12-12 at 11 41 15" src="https://user-images.githubusercontent.com/33927769/33877691-d332b34c-df31-11e7-9b45-f99a56eaa3f1.png">

And this is "/customer/list" page:

<img width="137" alt="screen shot 2017-12-12 at 11 41 10" src="https://user-images.githubusercontent.com/33927769/33877756-fa77a372-df31-11e7-9c5c-0af59f64e7e5.png">

Thank you

**Comment by nickhilliard** [comment]
@digitalandrei you need to use ``Internal`` rather than ``Route Server`` for the Customer Type.

@yannrobin can you remove TYPE_ROUTESERVER? It appears in:

database/Entities/Customer.php
app/Utils/Export/JsonSchema.php

**Comment by digitalandrei** [comment]
Alright, thank you.

**Comment by yannrobin** [comment]
@nickhilliard Files deleted

**Comment by nickhilliard** [comment]
@yannrobin ok, cool thx!

@digitalandrei this fix will be pushed in v4.8.
