### ISSUE TITLE
Login credentials not working following a fresh setup

### ISSUE THREAD

**Issue by eliehani** [inex/IXP-Manager#366]
Dears,
I have finished a fresh setup for IXPmanager on Ubuntu, i have followed the below steps:
USERNAME=admin
USEREMAIL=your@email.address
IXPM_ADMIN_PW="$( openssl rand -base64 12 )"
ADMIN_PW_SALT="$( openssl rand -base64 16 )"
HASH_PW=$( php -r "echo escapeshellarg( crypt( '${IXPM_ADMIN_PW}', sprintf( '\$2a\$%02d\$%s', 10, substr( '${ADMIN_PW_SALT}', 0, 22 ) ) ) );" )
echo Your password is: $IXPM_ADMIN_PW

When i type the server IP address in the browser, it is asking for username and password.
I am using the ones above but it is always stating that those credentials are wrong.

Please advise.
Thanks

**Comment by barryo** [comment]
Have you tried a password reset on the UI?

**Comment by eliehani** [comment]
Dears,

I have dropped the DB and recreated it again. Then restarted all services and it worked after that.

Thanks
Elie Hani

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Dec 22, 2017 at 7:31 PM +0200, "barryo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried a password reset on the UI?

**Comment by nickhilliard** [comment]
Hi Elie!  Wiping the db will work too, but you lose everything.  If you lose the admin password after you've populated the DB, it's better just to do a simple password reset from the UI because you won't lose anything then.

**Comment by eliehani** [comment]
Hello Nick,

First of all i want to wish you a Merry Christmas and Happy New Year.

I did this step since it is a fresh new installation. No data was stored on the machine yet.

Thank you.
Elie Hani

Get Outlook for Android<https://aka.ms/ghei36>




On Sat, Dec 23, 2017 at 7:40 PM +0200, "Nick Hilliard" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #366<https://github.com/inex/IXP-Manager/issues/366>.
