### ISSUE TITLE
Broken graphs for not connected customers

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#376]
.../statistics/members shows broken images for the missing graphs of customers in state "not connected" (which never had a port provisioned).

**Comment by rfc1036** [comment]
I have cherry-picked this commit and it works, but I still get broken images for the ports in "Awaiting X-Connect" status. FWIW I think that it would be more useful to just generate the graphs for ports in this state too.

**Comment by rfc1036** [comment]
Or maybe this is also a semantics issue? I see that the ports in the "Awaiting X-Connect" state are supposed to be shut down, but then how will the colocation operator be able to verify that the circuit is up and e.g. RX/TX are not swapped?

**Comment by barryo** [comment]
Just reopening until I ensure I got all the cases @rfc1036  mentions above.

**Comment by barryo** [comment]
I think this is all fixed.
