### ISSUE TITLE
Euro-IX member list export: empty as-set fields filled with the aut-num

### ISSUE THREAD

**Issue by pierky** [inex/IXP-Manager#379]
If I'm not mistaken, it seems that when a member is configured with empty as-set fields, the `as_macro` fields in the Euro-IX JSON export file are automatically set to its aut-num object  (ASxxx).

Wouldn't it be better if they were left empty? If so, consumer tools could understand that an info is missing there and could fetch it in other ways or handle the exception. Moreover, if they mandatorily need at least one object to expand they could easily use the ASN themselves to build one.

Contrarily it's impossible to understand whether the use of the aut-num object is forced by the IXP operator or simply exported by default.

**Comment by barryo** [comment]
This was unintentional - more a hangover of the way we gather prefixes for filtering.

This commit does not include the AS macro is IX-F export if none is configured.
