### ISSUE TITLE
Password Length

### ISSUE THREAD

**Issue by MHammett** [inex/IXP-Manager#380]
When creating a customer login:

`'FZEx&ECup9l5W2mU5cAf$PBJw6tN9y9Ntmj%LDdNo$iyHZ5aUjLt3mzM%0qRNi6@JPk&f^f$N%mMaWPMT#B*sWe!0fJGNwjBt7x&' is more than 30 characters long`

Please increase that length.  :-)

**Comment by barryo** [comment]
Noted for #354.
