### ISSUE TITLE
Piwik / Google Analytics integration

### ISSUE THREAD

**Issue by kylespencer** [inex/IXP-Manager#389]
It would be nice to be able to track utilization of IXP Manager by the public and internal users via Google Analytics, Piwik, etc.

**Comment by barryo** [comment]
Stick what you need in the footer:

http://docs.ixpmanager.org/features/skinning/

**Comment by barryo** [comment]
Better answer:

Both of the examples you gave work by placing a snippet of code at the end of the html file. This means to implement what you want here just means skinning the appropriate template.

In IXP Manager <= 4.7.2, this means these two files:

* https://github.com/inex/IXP-Manager/blob/v4.7.2/application/views/footer.phtml (ZF)
* https://github.com/inex/IXP-Manager/blob/v4.7.2/resources/views/layouts/ixpv4.foil.php (Laravel)

With instructions at: http://docs.ixpmanager.org/features/skinning/

We will have nearly migrated all content from ZF when we release 4.8 and the above commit creates a new file in that:

* https://github.com/inex/IXP-Manager/blob/master/resources/views/footer-custom.foil.php

From >=4.8 you should be able to just skin this dedicated file for this purpose.

**Comment by kylespencer** [comment]
Cheers :)

--
Cell/WhatsApp/Signal: +256790884905
