### ISSUE TITLE
DB migration for rcvrfname missing

### ISSUE THREAD

**Issue by 9er** [inex/IXP-Manager#390]
Hi all,

in the migrations from version 3 to 4, there seems to be a issue with a view on the `vlan` table.

In the DB schema, the column `rcvrfname` seems to have been removed. It has also been removed from the view `view_vlaninterface_details_by_custid` but in our case (migration from 3 to 4.5.0 then to 4.7.3) the view has not been updated and still uses the field `rcvrfname`.

I'm not entirely sure how the migrations work and if they just reinstall all views from `tools/sql/views.sql`, where the view is correct, but in our case it still had the old content.

**Comment by nickhilliard** [comment]
every upgrade, you need to refresh views.sql. 

`mysql -u ixp -p ixp < $IXPROOT/tools/sql/views.sql`

This isn't in the upgrade script, so needs to be done manually.

**Comment by 9er** [comment]
In this case, it should not be mentioned in the last line of "fixing database issues", but in the "Upgrading IXP-Manager" manual.

http://docs.ixpmanager.org/install/upgrading/

Probably near number 7, "Update the database schema".

**Comment by nickhilliard** [comment]
you're right - now moved to the main upgrade procedure. This will be updated on the web site next time it's rebuilt.
