### ISSUE TITLE
Change / Audit trail

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#395]
##### ISSUE TYPE

  - Feature Idea

##### SUMMARY

Keep a record / note every time a change happens to an account, for example the following events:
- Adding a new user / changing key details (email/user/password reset etc.)
- Adding a new port
- Deleting / Moving a port
- Change port state (Quarantine/Connected/Not Connected/Disabled)
- Marking a member active / suspended / account closed
- New cable added in patch panel records etc.

This would help us greatly with tasks such as billing and management reporting.

- Automated reports for example generate a report of all changes between two given dates.

Currently we add manual notes for port add/removes. Have considered scripting more to put automated notes in when changes are detected, for example, do a periodic extract of member and port states, diff with previous, note any changes in the customer notes.

**Comment by shahabv** [comment]
Hello Guys, we need this user audit logs and we use them alot in our system as we have different operators.

**Comment by barryo** [comment]
Database change logging implemented in v6.
