### ISSUE TITLE
public/member-details not working 

### ISSUE THREAD

**Issue by steiostb** [inex/IXP-Manager#401]
##### ISSUE TYPE
 - Bug Report

##### OS
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"

##### VERSION
define( 'APPLICATION_VERSION', '4.7.999' );
define( 'APPLICATION_VERDATE', '2018031400' );

##### ENVIRONMENT 
php -v
PHP 7.2.3-1ubuntu1 (cli) (built: Mar 14 2018 22:03:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1ubuntu1, Copyright (c) 1999-2018, by Zend Technologies

dpkg -l | grep php   (or equivalent for your OS - list of php packages installed)

ii  libapache2-mod-php                  1:7.2+60ubuntu1                    all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
rc  libapache2-mod-php7.0               7.0.22-0ubuntu0.16.04.1            amd64        server-side, HTML-embedded scripting language (Apache 2 module)
rc  libapache2-mod-php7.1               7.1.11-0ubuntu2                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-php7.2               7.2.3-1ubuntu1                     amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libphp7.2-embed                     7.2.3-1ubuntu1                     amd64        HTML-embedded scripting language (Embedded SAPI library)
ii  php                                 1:7.2+60ubuntu1                    all          server-side, HTML-embedded scripting language (default)
ii  php-cli-prompt                      1.0.3+dfsg-1                       all          tiny helper prompting for user input
ii  php-common                          1:60ubuntu1                        all          Common files for PHP packages
ii  php-composer-ca-bundle              1.1.0-1                            all          utility library to find a path to the system CA bundle
ii  php-composer-semver                 1.4.2-1                            all          utilities, version constraint parsing and validation
ii  php-composer-spdx-licenses          1.3.0-1                            all          SPDX licenses list and validation library
ii  php-gettext                         1.0.12-0.1                         all          transitional dummy package for php-php-gettext
ii  php-igbinary                        2.0.5-1build1                      amd64        igbinary PHP serializer
ii  php-json-schema                     5.2.6-1                            all          implementation of JSON schema
ii  php-mcrypt                          1:7.1+54ubuntu1                    all          libmcrypt module for PHP [default]
ii  php-memcache                        3.0.9~20160311.4991c2f-5build2     amd64        memcache extension module for PHP
ii  php-memcached                       3.0.1+2.2.0-1build2                amd64        memcached extension module for PHP, uses libmemcached
ii  php-msgpack                         2.0.2+0.5.7-2build1                amd64        PHP extension for interfacing with MessagePack
ii  php-pear                            1:1.10.5+submodules+notgz-1ubuntu1 all          PEAR Base System
ii  php-php-gettext                     1.0.12-0.1                         all          read gettext MO files directly, without requiring anything other than PHP
ii  php-psr-log                         1.0.2-1                            all          common interface for logging libraries
ii  php-remctl                          3.13-1build5                       amd64        PECL module for Kerberos-authenticated command execution
ii  php-rrd                             2.0.1+1.1.3-4build1                amd64        PHP bindings to rrd tool system
ii  php-symfony-console                 3.4.3+dfsg-1ubuntu4                all          run tasks from the command line
ii  php-symfony-debug                   3.4.3+dfsg-1ubuntu4                all          tools to make debugging of PHP code easier
ii  php-symfony-filesystem              3.4.3+dfsg-1ubuntu4                all          basic filesystem utilities
ii  php-symfony-finder                  3.4.3+dfsg-1ubuntu4                all          find files and directories
ii  php-symfony-polyfill-mbstring       1.6.0-2                            all          Symfony polyfill for the Mbstring extension
ii  php-symfony-process                 3.4.3+dfsg-1ubuntu4                all          execute commands in sub-processes
ii  php-symfony-yaml                    3.4.3+dfsg-1ubuntu4                all          convert YAML to PHP arrays and the other way around
rc  php7.0-bcmath                       7.0.22-0ubuntu0.16.04.1            amd64        Bcmath module for PHP
rc  php7.0-cgi                          7.0.22-0ubuntu0.16.04.1            amd64        server-side, HTML-embedded scripting language (CGI binary)
rc  php7.0-cli                          7.0.22-0ubuntu0.16.04.1            amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                       7.0.22-0ubuntu0.16.04.1            amd64        documentation, examples and common module for PHP
rc  php7.0-curl                         7.0.22-0ubuntu0.16.04.1            amd64        CURL module for PHP
rc  php7.0-gd                           7.0.22-0ubuntu0.16.04.1            amd64        GD module for PHP
rc  php7.0-intl                         7.0.22-0ubuntu0.16.04.1            amd64        Internationalisation module for PHP
rc  php7.0-json                         7.0.22-0ubuntu0.16.04.1            amd64        JSON module for PHP
ii  php7.0-mbstring                     7.0.22-0ubuntu0.16.04.1            amd64        MBSTRING module for PHP
rc  php7.0-mcrypt                       7.0.22-0ubuntu0.16.04.1            amd64        libmcrypt module for PHP
rc  php7.0-mysql                        7.0.22-0ubuntu0.16.04.1            amd64        MySQL module for PHP
rc  php7.0-opcache                      7.0.22-0ubuntu0.16.04.1            amd64        Zend OpCache module for PHP
rc  php7.0-readline                     7.0.22-0ubuntu0.16.04.1            amd64        readline module for PHP
rc  php7.0-snmp                         7.0.22-0ubuntu0.16.04.1            amd64        SNMP module for PHP
ii  php7.0-xml                          7.0.22-0ubuntu0.16.04.1            amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
rc  php7.0-zip                          7.0.22-0ubuntu0.16.04.1            amd64        Zip module for PHP
rc  php7.1-bcmath                       7.1.11-0ubuntu2                    amd64        Bcmath module for PHP
rc  php7.1-cgi                          7.1.11-0ubuntu2                    amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.1-cli                          7.1.11-0ubuntu2                    amd64        command-line interpreter for the PHP scripting language
ii  php7.1-common                       7.1.11-0ubuntu2                    amd64        documentation, examples and common module for PHP
rc  php7.1-curl                         7.1.11-0ubuntu2                    amd64        CURL module for PHP
rc  php7.1-gd                           7.1.11-0ubuntu2                    amd64        GD module for PHP
rc  php7.1-intl                         7.1.11-0ubuntu2                    amd64        Internationalisation module for PHP
ii  php7.1-json                         7.1.11-0ubuntu2                    amd64        JSON module for PHP
ii  php7.1-mbstring                     7.1.11-0ubuntu2                    amd64        MBSTRING module for PHP
ii  php7.1-mcrypt                       7.1.11-0ubuntu2                    amd64        libmcrypt module for PHP
rc  php7.1-mysql                        7.1.11-0ubuntu2                    amd64        MySQL module for PHP
ii  php7.1-opcache                      7.1.11-0ubuntu2                    amd64        Zend OpCache module for PHP
rc  php7.1-phpdbg                       7.1.11-0ubuntu2                    amd64        server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php7.1-readline                     7.1.11-0ubuntu2                    amd64        readline module for PHP
rc  php7.1-snmp                         7.1.11-0ubuntu2                    amd64        SNMP module for PHP
ii  php7.1-xml                          7.1.11-0ubuntu2                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.1-zip                          7.1.11-0ubuntu2                    amd64        Zip module for PHP
ii  php7.2                              7.2.3-1ubuntu1                     all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.2-bcmath                       7.2.3-1ubuntu1                     amd64        Bcmath module for PHP
ii  php7.2-cgi                          7.2.3-1ubuntu1                     amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.2-cli                          7.2.3-1ubuntu1                     amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common                       7.2.3-1ubuntu1                     amd64        documentation, examples and common module for PHP
ii  php7.2-curl                         7.2.3-1ubuntu1                     amd64        CURL module for PHP
ii  php7.2-gd                           7.2.3-1ubuntu1                     amd64        GD module for PHP
ii  php7.2-intl                         7.2.3-1ubuntu1                     amd64        Internationalisation module for PHP
ii  php7.2-json                         7.2.3-1ubuntu1                     amd64        JSON module for PHP
ii  php7.2-mbstring                     7.2.3-1ubuntu1                     amd64        MBSTRING module for PHP
ii  php7.2-mysql                        7.2.3-1ubuntu1                     amd64        MySQL module for PHP
ii  php7.2-opcache                      7.2.3-1ubuntu1                     amd64        Zend OpCache module for PHP
ii  php7.2-phpdbg                       7.2.3-1ubuntu1                     amd64        server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php7.2-readline                     7.2.3-1ubuntu1                     amd64        readline module for PHP
ii  php7.2-snmp                         7.2.3-1ubuntu1                     amd64        SNMP module for PHP
ii  php7.2-xml                          7.2.3-1ubuntu1                     amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.2-zip                          7.2.3-1ubuntu1                     amd64        Zip module for PHP

##### CONFIGURATION
cat .env | egrep -v '(^#|^\s*$|^DB_|^APP_KEY|^HELPDESK|^IDENTITY|^MAIL_|^IXP_API_RIR_PASSWORD|^IXP_API_PEERING_DB_)'
|^IXP_API_RIR_PASSWORD|^IXP_API_PEERING_DB_)'
APP_DEBUG=false
APP_URL="xxx"
APP_TIMEZONE="CET"
APP_LOG="single"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=true
GRAPHER_BACKENDS="mrtg"
GRAPHER_BACKEND_MRTG_DBTYPE="log"
GRAPHER_BACKEND_MRTG_WORKDIR="/usr/local/ixp/data/grapher/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/usr/local/ixp/data/grapher/mrtg"
VIEW_SKIN="xxx"
VIEW_SMARTY_SKIN="xxx"
AUTH_ZF1_PWHASH="bcrypt"
SESSION_DRIVER=file
CACHE_DRIVER=file
DOCTRINE_PROXY_AUTOGENERATE=true
IXP_FE_FRONTEND_DISABLED_CONSOLE=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=true

##### SUMMARY
public/member-details will not load - instead a get a error 404 page. There is no difference if I delete  ixp/application/views/_skins/xx/public/member-details.phtml. We updated from v4.7.3 to master branch  last week. But this was not an issue before today. I am running the default member-details-phtml (copied from _skins/example/public)

##### STEPS TO REPRODUCE
1. Make sure you have your file in ixp/application/views/_skins/xx/public/member-details.phtml.
2. Access yourdomain/public/member-details from a browser.

##### EXPECTED RESULTS
public/member-details should have loaded.

##### ACTUAL RESULTS
An error 404 message appears.

From the storage/logs/laravel.log:
Message: Invalid controller specified (public)
Line: 248
File: /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php

Trace:

#0 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#2 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#3 /usr/local/ixp/app/Exceptions/Handler.php(62): Zend_Application->run()
#4 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): IXP\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 /usr/local/ixp/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /usr/local/ixp/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#27 /usr/local/ixp/public/index.php(85): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#28 {main}

Array
(
    [0] => Array
        (
            [file] => /usr/local/ixp/library/OSS/Controller/Trait/Error.php
            [line] => 78
            [function] => compact_debug_backtrace
            [class] => OSS_Debug
        )

    [1] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php
            [line] => 516
            [function] => errorAction
            [class] => ErrorController
        )

    [2] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php
            [line] => 308
            [function] => dispatch
            [class] => Zend_Controller_Action
        )

    [3] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php
            [line] => 954
            [function] => dispatch
            [class] => Zend_Controller_Dispatcher_Standard
        )

    [4] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php
            [line] => 105
            [function] => dispatch
            [class] => Zend_Controller_Front
        )

    [5] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application.php
            [line] => 384
            [function] => run
            [class] => Zend_Application_Bootstrap_Bootstrap
        )

    [6] => Array
        (
            [file] => /usr/local/ixp/app/Exceptions/Handler.php
            [line] => 62
            [function] => run
            [class] => Zend_Application
        )

    [7] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 83
            [function] => render
            [class] => IXP\Exceptions\Handler
        )

    [8] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 32
            [function] => handleException
            [class] => Illuminate\Routing\Pipeline
        )

    [9] => Array
        (
            [file] => /usr/local/ixp/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php
            [line] => 58
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [10] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Barryvdh\Debugbar\Middleware\InjectDebugbar
        )

    [11] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [12] => Array
        (
            [file] => /usr/local/ixp/vendor/fideloper/proxy/src/TrustProxies.php
            [line] => 56
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [13] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Fideloper\Proxy\TrustProxies
        )

    [14] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [15] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
            [line] => 30
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [16] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
        )

    [17] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [18] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
            [line] => 30
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [19] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
        )

    [20] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [21] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
            [line] => 27
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [22] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\ValidatePostSize
        )

    [23] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [24] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php
            [line] => 46
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [25] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode
        )

    [26] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [27] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 102
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [28] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
            [line] => 151
            [function] => then
            [class] => Illuminate\Pipeline\Pipeline
        )

    [29] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
            [line] => 116
            [function] => sendRequestThroughRouter
            [class] => Illuminate\Foundation\Http\Kernel
        )

    [30] => Array
        (
            [file] => /usr/local/ixp/public/index.php
            [line] => 85
            [function] => handle
            [class] => Illuminate\Foundation\Http\Kernel
        )

)

##### IMPORTANCE
Minor fault

**Comment by barryo** [comment]
Hey @steiostb 

Thanks for the detailed bug report.

To be honest, I didn't expect people to risk using IXP Manager from master 😉 

The release notes are in draft form as once they are published GitHub tags the branch. 

Here's some pertinent bits which also explains the above:

## Pre-Upgrade Database Schema Changes

The following may be null-ops for most users. At INEX, some of our database entries date back >10 years so there is a little bit of crud in there from older tools and from times when MySQL was less strict on certain formats.

```sql
UPDATE `contact` SET `created` = NULL WHERE CAST(`created` AS CHAR(20)) = '0000-00-00 00:00:00';
UPDATE `contact` SET `lastupdated` = NULL WHERE CAST(`lastupdated` AS CHAR(20)) = '0000-00-00 00:00:00';
DELETE FROM `user_pref` WHERE `user_pref`.`user_id` NOT IN ( SELECT `id` FROM `user`);
UPDATE `irrdb_asn` SET `last_seen` = NULL WHERE CAST(`last_seen` AS CHAR(20)) = '0000-00-00 00:00:00';
```


## Post-Upgrade Database Schema Changes

Make sure you have completed all  schema updates as per  [the official upgrade documentation](http://docs.ixpmanager.org/install/upgrading/). These include:

```sql
ALTER TABLE vlaninterface ADD rsmorespecifics TINYINT(1) DEFAULT '0' NOT NULL;
```

## Route Server Template Updates

If you are generating your route server configurations via IXP Manager with IRRDB filtering, then please make sure you add the following option to your local `.env` file:

```
# Absolute path to run the bgpq3 utility
# e.g. IXP_IRRDB_BGPQ3_PATH=/usr/local/bin/bgpq3
IXP_IRRDB_BGPQ3_PATH=/path/to/your/bgpq3
```

**DEPRECATION:** the former setting for the bgpq3 path in `config/ixp_tools.php` is no longer used and the entire `irrdb` section can be removed.

The route servers in their default configuration filter all IPv4 prefixes >/24. This version of IXP Manager now makes that configurable as well as adding the same restriction for IPv6 (at >/48). If you want to change these, add and set the following options to your `.env` (default values shown):

```
IXP_IRRDB_MIN_V4_SUBNET_SIZE=24
IXP_IRRDB_MIN_V6_SUBNET_SIZE=48
```

The IRRDB database update process now also honours these by passing `bgpq3` the `-m` option (2ebcdc74a862ec148ec60e726fb77da96f818295).

We have extended BGP NEXT_HOP hijacking detection and prevention to v6 also (28931031eda866e1921504b32adf95fba788f2e3).

We now allow more specifics in route server inbound prefix filtering. This means, for example, if someone has a IRRDB entry for `a.b.0.0/16` but advertises this as 2 /17's, these will be accepted **if** the user's VLAN interface is configured to allow this. This implements a feature as discussed in inex/IXP-Manager#281 and requested a number of times by others including @listerr (9f146d6215e9aaa161080b1cbfede62128f1bc66).

## Exporting Member Details

The [older Zend Framework method of exporting member details](https://github.com/inex/IXP-Manager/wiki/Exporting-Member-Details) has been deprecated for sometime and is now removed in this release. If you were using this, please migrate to the new methods:

1. IX-F Member Export: http://docs.ixpmanager.org/features/ixf-export/
2. New Member Export: http://docs.ixpmanager.org/features/member-export/
