### ISSUE TITLE
IX-F export of members with non-connected ports

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#409]
As far as I can see, currently IXP manager exports in the IX-F data feed only customers which have at least one port in the "connected" state.

I believe that this is highly suboptimal and that at least members with ports in the "awaiting x-connect" and "quarantine" state should be listed as well.

This change should not cause troubles for IX-F consumers since the schema has a "state" field for each connection, would represent the actual configured status of the port.

An obvious argument for listing quarantined ports is that customers should not be removed from the members listing (and maybe deconfigured by other customers, etc...) just because their port is being quarantined after their router has been replaced.

I think that it would also be useful to export connections in the "awaiting x-connect" state, but even if you believe that they should not then such members could be listed with 0 connections.

**Comment by barryo** [comment]
Hi @rfc1036 - can you bring this to an issue at https://github.com/euro-ix/json-schemas/ please?

We'll follow whatever the consensus is there. For now, it is not possible to peer with a member with a non-connected port and so I don't fell they belong in the export.
