### ISSUE TITLE
Semantics of the "awaiting cross connect" status

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#410]
I am trying to use the "awaiting cross connect" status, but I am experiencing a lot of little issues and I am not sure that its semantics are defined well enough.

My idea is that this status should represent ports which have been configured but have not been connected yet to the customer device.

This means that these ports should be at least partially configured and need to be up, to allow the data centre staff and/or customers to debug the physical layer. Currently they are marked as shutdown in the switch provisioning API, which I do not think is useful.

This is also related to https://github.com/inex/IXP-Manager/issues/377: broken graphs are shown for these ports (they should either be generated or just suppressed).

Another related issue is https://github.com/inex/IXP-Manager/issues/409: members with no active ports are not listed in the IX-F feed, but I do not think that this is useful.

**Comment by barryo** [comment]
Some definitions are at: http://docs.ixpmanager.org/usage/interfaces/#physical-interface-settings

Ports can be *awaiting cross connect* for hours to months (and in extreme cases more than a year). It is not appropriate to have ports in an up state for these periods of time - especially optics.

Our expectation (and work flow) is that all debugging - physical, later 2 and layer 3 is done in quarantine.

**Comment by rfc1036** [comment]
Fair enough, so the fix for #377 should be extended to cover this state as well.

**Comment by barryo** [comment]
> Fair enough, so the fix for #377 should be extended to cover this state as well.

Yes, in fact that's already done in master as well 🍻
