### ISSUE TITLE
Feature request - report generation

### ISSUE THREAD

**Issue by unioslonet** [inex/IXP-Manager#411]
We would like to be able to generate a report containing data related but not
limited to billing.

Examples of the type of data we want in the report:

* Subscribed ports
* Speed of connections
* Billing information
* Notes
* Changes done on "Ports" 
* Timestamps, date etc. on everything

Essentially typical data that would impact pricing.

We would also like to be able to do this per customer.

This would simplify the billing process.

University of Oslo
Computer Networks Group

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.
