### ISSUE TITLE
Switch configuration gives error 404

### ISSUE THREAD

**Issue by steiostb** [inex/IXP-Manager#412]
##### ISSUE TYPE
 - Bug Report

##### OS
Ubuntu 18.04 LTS Bionic Beaver

##### VERSION
define( 'APPLICATION_VERSION', '4.7.999' );
define( 'APPLICATION_VERDATE', '2018031400' );

##### ENVIRONMENT 
php -v
PHP 7.2.3-1ubuntu1 (cli) (built: Mar 14 2018 22:03:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1ubuntu1, Copyright (c) 1999-2018, by Zend Technologies

dpkg -l | grep php  
ii  libapache2-mod-php                  1:7.2+60ubuntu1                    all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
rc  libapache2-mod-php7.0               7.0.22-0ubuntu0.16.04.1            amd64        server-side, HTML-embedded scripting language (Apache 2 module)
rc  libapache2-mod-php7.1               7.1.11-0ubuntu2                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-php7.2               7.2.3-1ubuntu1                     amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libphp7.2-embed                     7.2.3-1ubuntu1                     amd64        HTML-embedded scripting language (Embedded SAPI library)
ii  php                                 1:7.2+60ubuntu1                    all          server-side, HTML-embedded scripting language (default)
ii  php-cli-prompt                      1.0.3+dfsg-1                       all          tiny helper prompting for user input
ii  php-common                          1:60ubuntu1                        all          Common files for PHP packages
ii  php-composer-ca-bundle              1.1.0-1                            all          utility library to find a path to the system CA bundle
ii  php-composer-semver                 1.4.2-1                            all          utilities, version constraint parsing and validation
ii  php-composer-spdx-licenses          1.3.0-1                            all          SPDX licenses list and validation library
ii  php-gettext                         1.0.12-0.1                         all          transitional dummy package for php-php-gettext
ii  php-igbinary                        2.0.5-1build1                      amd64        igbinary PHP serializer
ii  php-json-schema                     5.2.6-1                            all          implementation of JSON schema
ii  php-mcrypt                          1:7.1+54ubuntu1                    all          libmcrypt module for PHP [default]
ii  php-memcache                        3.0.9~20160311.4991c2f-5build2     amd64        memcache extension module for PHP
ii  php-memcached                       3.0.1+2.2.0-1build2                amd64        memcached extension module for PHP, uses libmemcached
ii  php-msgpack                         2.0.2+0.5.7-2build1                amd64        PHP extension for interfacing with MessagePack
ii  php-pear                            1:1.10.5+submodules+notgz-1ubuntu1 all          PEAR Base System
ii  php-php-gettext                     1.0.12-0.1                         all          read gettext MO files directly, without requiring anything other than PHP
ii  php-psr-log                         1.0.2-1                            all          common interface for logging libraries
ii  php-remctl                          3.13-1+deb9u1                      amd64        PECL module for Kerberos-authenticated command execution
ii  php-rrd                             2.0.1+1.1.3-4build1                amd64        PHP bindings to rrd tool system
ii  php-symfony-console                 3.4.6+dfsg-1                       all          run tasks from the command line
ii  php-symfony-debug                   3.4.6+dfsg-1                       all          tools to make debugging of PHP code easier
ii  php-symfony-filesystem              3.4.6+dfsg-1                       all          basic filesystem utilities
ii  php-symfony-finder                  3.4.6+dfsg-1                       all          find files and directories
ii  php-symfony-polyfill-mbstring       1.6.0-2                            all          Symfony polyfill for the Mbstring extension
ii  php-symfony-process                 3.4.6+dfsg-1                       all          execute commands in sub-processes
ii  php-symfony-yaml                    3.4.6+dfsg-1                       all          convert YAML to PHP arrays and the other way around
rc  php7.0-bcmath                       7.0.22-0ubuntu0.16.04.1            amd64        Bcmath module for PHP
rc  php7.0-cgi                          7.0.22-0ubuntu0.16.04.1            amd64        server-side, HTML-embedded scripting language (CGI binary)
rc  php7.0-cli                          7.0.22-0ubuntu0.16.04.1            amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                       7.0.22-0ubuntu0.16.04.1            amd64        documentation, examples and common module for PHP
rc  php7.0-curl                         7.0.22-0ubuntu0.16.04.1            amd64        CURL module for PHP
rc  php7.0-gd                           7.0.22-0ubuntu0.16.04.1            amd64        GD module for PHP
rc  php7.0-intl                         7.0.22-0ubuntu0.16.04.1            amd64        Internationalisation module for PHP
rc  php7.0-json                         7.0.22-0ubuntu0.16.04.1            amd64        JSON module for PHP
ii  php7.0-mbstring                     7.0.22-0ubuntu0.16.04.1            amd64        MBSTRING module for PHP
rc  php7.0-mcrypt                       7.0.22-0ubuntu0.16.04.1            amd64        libmcrypt module for PHP
rc  php7.0-mysql                        7.0.22-0ubuntu0.16.04.1            amd64        MySQL module for PHP
rc  php7.0-opcache                      7.0.22-0ubuntu0.16.04.1            amd64        Zend OpCache module for PHP
rc  php7.0-readline                     7.0.22-0ubuntu0.16.04.1            amd64        readline module for PHP
rc  php7.0-snmp                         7.0.22-0ubuntu0.16.04.1            amd64        SNMP module for PHP
ii  php7.0-xml                          7.0.22-0ubuntu0.16.04.1            amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
rc  php7.0-zip                          7.0.22-0ubuntu0.16.04.1            amd64        Zip module for PHP
rc  php7.1-bcmath                       7.1.11-0ubuntu2                    amd64        Bcmath module for PHP
rc  php7.1-cgi                          7.1.11-0ubuntu2                    amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.1-cli                          7.1.11-0ubuntu2                    amd64        command-line interpreter for the PHP scripting language
ii  php7.1-common                       7.1.11-0ubuntu2                    amd64        documentation, examples and common module for PHP
rc  php7.1-curl                         7.1.11-0ubuntu2                    amd64        CURL module for PHP
rc  php7.1-gd                           7.1.11-0ubuntu2                    amd64        GD module for PHP
rc  php7.1-intl                         7.1.11-0ubuntu2                    amd64        Internationalisation module for PHP
ii  php7.1-json                         7.1.11-0ubuntu2                    amd64        JSON module for PHP
ii  php7.1-mbstring                     7.1.11-0ubuntu2                    amd64        MBSTRING module for PHP
ii  php7.1-mcrypt                       7.1.11-0ubuntu2                    amd64        libmcrypt module for PHP
rc  php7.1-mysql                        7.1.11-0ubuntu2                    amd64        MySQL module for PHP
ii  php7.1-opcache                      7.1.11-0ubuntu2                    amd64        Zend OpCache module for PHP
rc  php7.1-phpdbg                       7.1.11-0ubuntu2                    amd64        server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php7.1-readline                     7.1.11-0ubuntu2                    amd64        readline module for PHP
rc  php7.1-snmp                         7.1.11-0ubuntu2                    amd64        SNMP module for PHP
ii  php7.1-xml                          7.1.11-0ubuntu2                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.1-zip                          7.1.11-0ubuntu2                    amd64        Zip module for PHP
ii  php7.2                              7.2.3-1ubuntu1                     all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.2-bcmath                       7.2.3-1ubuntu1                     amd64        Bcmath module for PHP
ii  php7.2-cgi                          7.2.3-1ubuntu1                     amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.2-cli                          7.2.3-1ubuntu1                     amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common                       7.2.3-1ubuntu1                     amd64        documentation, examples and common module for PHP
ii  php7.2-curl                         7.2.3-1ubuntu1                     amd64        CURL module for PHP
ii  php7.2-gd                           7.2.3-1ubuntu1                     amd64        GD module for PHP
ii  php7.2-intl                         7.2.3-1ubuntu1                     amd64        Internationalisation module for PHP
ii  php7.2-json                         7.2.3-1ubuntu1                     amd64        JSON module for PHP
ii  php7.2-mbstring                     7.2.3-1ubuntu1                     amd64        MBSTRING module for PHP
ii  php7.2-mysql                        7.2.3-1ubuntu1                     amd64        MySQL module for PHP
ii  php7.2-opcache                      7.2.3-1ubuntu1                     amd64        Zend OpCache module for PHP
ii  php7.2-phpdbg                       7.2.3-1ubuntu1                     amd64        server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php7.2-readline                     7.2.3-1ubuntu1                     amd64        readline module for PHP
ii  php7.2-snmp                         7.2.3-1ubuntu1                     amd64        SNMP module for PHP
ii  php7.2-xml                          7.2.3-1ubuntu1                     amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.2-zip                          7.2.3-1ubuntu1                     amd64        Zip module for PHP

##### CONFIGURATION
cat .env | egrep -v '(^#|^\s*$|^DB_|^APP_KEY|^HELPDESK|^IDENTITY|^MAIL_|^IXP_API_RIR_PASSWORD|^IXP_API_PEERING_DB_)'

L_|^IXP_API_RIR_PASSWORD|^IXP_API_PEERING_DB_)'
APP_DEBUG=false
APP_URL="https://xx"
APP_TIMEZONE="CET"
APP_LOG="single"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=true
GRAPHER_BACKENDS="mrtg"
GRAPHER_BACKEND_MRTG_DBTYPE="log"
GRAPHER_BACKEND_MRTG_WORKDIR="/usr/local/ixp/data/grapher/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/usr/local/ixp/data/grapher/mrtg"
VIEW_SKIN="x"
VIEW_SMARTY_SKIN="x"
AUTH_ZF1_PWHASH="bcrypt"
SESSION_DRIVER=file
CACHE_DRIVER=array
CACHE_EXPIRE=-1
DOCTRINE_PROXY_AUTOGENERATE=true
DOCTRINE_CACHE=array
IXP_FE_FRONTEND_DISABLED_CONSOLE=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=true
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq3

##### SUMMARY
When I click on Member Information - Switch Configuration  - click on one of the customers name, I got an error 404 page not found. Same for all customers.

##### STEPS TO REPRODUCE
Click on Member Information - Switch Configuration  - click on one of the customers name,

##### EXPECTED RESULTS
 A page with switch configuration for each customer.

##### ACTUAL RESULTS
From laravel.log:

--------------------------- EXCEPTION --------------------------

Message: Invalid controller specified (customer)
Line: 248
File: /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php

Trace:

#0 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#2 /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#3 /usr/local/ixp/app/Exceptions/Handler.php(62): Zend_Application->run()
#4 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): IXP\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 /usr/local/ixp/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /usr/local/ixp/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#27 /usr/local/ixp/public/index.php(85): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#28 {main}

Array
(
    [0] => Array
        (
            [file] => /usr/local/ixp/library/OSS/Controller/Trait/Error.php
            [line] => 78
            [function] => compact_debug_backtrace
            [class] => OSS_Debug
        )

    [1] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php
            [line] => 516
            [function] => errorAction
            [class] => ErrorController
        )

    [2] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php
            [line] => 308
            [function] => dispatch
            [class] => Zend_Controller_Action
        )

    [3] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php
            [line] => 954
            [function] => dispatch
            [class] => Zend_Controller_Dispatcher_Standard
        )

    [4] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php
            [line] => 105
            [function] => dispatch
            [class] => Zend_Controller_Front
        )

    [5] => Array
        (
            [file] => /usr/local/ixp/vendor/zendframework/zendframework1/library/Zend/Application.php
            [line] => 384
            [function] => run
            [class] => Zend_Application_Bootstrap_Bootstrap
        )

    [6] => Array
        (
            [file] => /usr/local/ixp/app/Exceptions/Handler.php
            [line] => 62
            [function] => run
            [class] => Zend_Application
        )

    [7] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 83
            [function] => render
            [class] => IXP\Exceptions\Handler
        )

    [8] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 32
            [function] => handleException
            [class] => Illuminate\Routing\Pipeline
        )

    [9] => Array
        (
            [file] => /usr/local/ixp/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php
            [line] => 58
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [10] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Barryvdh\Debugbar\Middleware\InjectDebugbar
        )

    [11] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [12] => Array
        (
            [file] => /usr/local/ixp/vendor/fideloper/proxy/src/TrustProxies.php
            [line] => 56
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [13] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Fideloper\Proxy\TrustProxies
        )

    [14] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [15] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
            [line] => 30
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [16] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
        )

    [17] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [18] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
            [line] => 30
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [19] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\TransformsRequest
        )

    [20] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [21] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
            [line] => 27
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [22] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\ValidatePostSize
        )

    [23] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [24] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php
            [line] => 46
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [25] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 149
            [function] => handle
            [class] => Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode
        )

    [26] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php
            [line] => 53
            [function] => Illuminate\Pipeline\{closure}
            [class] => Illuminate\Pipeline\Pipeline
        )

    [27] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
            [line] => 102
            [function] => Illuminate\Routing\{closure}
            [class] => Illuminate\Routing\Pipeline
        )

    [28] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
            [line] => 151
            [function] => then
            [class] => Illuminate\Pipeline\Pipeline
        )

    [29] => Array
        (
            [file] => /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
            [line] => 116
            [function] => sendRequestThroughRouter
            [class] => Illuminate\Foundation\Http\Kernel
        )

    [30] => Array
        (
            [file] => /usr/local/ixp/public/index.php
            [line] => 85
            [function] => handle
            [class] => Illuminate\Foundation\Http\Kernel
        )

)

##### IMPORTANCE
Minor

**Comment by yannrobin** [comment]
Hello,

Its a bad link the customer management has been rebuilt on Laravel.

I will fix that bug.

If you want to access to the customer information you can use the following url instead : customer/overview/{id}
