### ISSUE TITLE
Feature request: Aggregate peer-to-peer graphs by peer

### ISSUE THREAD

**Issue by emjemj** [inex/IXP-Manager#416]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I would like to aggregate the graphs for peers with multiple L3 interfaces in the peering LAN to a single graph which would show the total traffic exchanged between the two networks. Of course you should be able to display the current view also, perhaps with a checkbox in the form at the top of the page.

##### STEPS TO REPRODUCE
Peer with someone who has multiple L3 interfaces in the same peering LAN.

##### EXPECTED RESULTS
Ability to see a nice graph with all traffic exchanged between my network and my peer regardless of how many L3 interfaces either of us has.

##### ACTUAL RESULTS
One graph is rendered per L3 interface in the peering LAN.

##### IMPORTANCE
This is mostly a nice to have feature.

**Comment by barryo** [comment]
@emjemj - yes, this is a badly needed feature. 

This is on our internal development plan so I'm going to close off the issue here. Should be available by end of 2018.
