### ISSUE TITLE
MRTG INSTALL

### ISSUE THREAD

**Issue by beleamare** [inex/IXP-Manager#418]
Hi,
On newly installed ixpmanager server  im trying to install mrtg from documentation given on site. https://docs.ixpmanager.org/grapher/mrtg/. 
In .env file here is configuration 
In my .env file it looks like this:
GRAPHER_BACKENDS="mrtg"
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"

GRAPHER_CACHE_ENABLED=true

also php artisan grapher:generate-configuration -B mrtg 
       php artisan grapher:gerenate-configuraton -B mrtg -O /tmp/cfg/mrtg.cfg.candidate they work too
But i see on web page i see blank pages for graph and when i try to type command 
/etc/init.d/mrtg start  it gives FAILED 
and with systemctl status mrtg.service it gives me output :

May 24 11:27:27 root systemd[1]: Starting LSB: mrtg init script...
May 24 11:27:27 root mrtg[12836]:  * Starting mrtg
May 24 11:27:27 root mrtg[12836]: cannot write to /etc/mrtg/mrtg.pid: No such file or directory
May 24 11:27:27 root mrtg[12836]: ERROR: unable to open config file: /etc/mrtg/mrtg.cfg
May 24 11:27:27 root systemd[1]: mrtg.service: Control process exited, code=exited status=2
May 24 11:27:27 root systemd[1]: Failed to start LSB: mrtg init script.
May 24 11:27:27 root systemd[1]: mrtg.service: Unit entered failed state.
May 24 11:27:27 root systemd[1]: mrtg.service: Failed with result 'exit-code'.

Any help? :) Thanks .

**Comment by nickhilliard** [comment]
not a bug
