### ISSUE TITLE
Feature Request - Port status (SNMP poll) for customers

### ISSUE THREAD

**Issue by steiostb** [inex/IXP-Manager#419]
Customers should be allowed to see live port status (SNMP) for their connnections and at least who they peer with. This is already available for superusers (Switches - More... - View Live Ports States (with SNMP-poll)).

Customers are allowed to view a similar view from Member Information - Switch Configuration, but the Status field is not obtained with a SNMP-poll, but static from the DB.

 A field for Admin stats and Operation state would be great. Is it possible that the Operation state can differentiate between err-disable and link down? This would make troubleshooting easier for the customers.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: on our medium-term development plan and so open issue required to support it.*
