### ISSUE TITLE
Missing folders while installing IXP-Manager through automated script

### ISSUE THREAD

**Issue by zaziz01** [inex/IXP-Manager#420]
##### ISSUE TYPE

 - Bug Report

##### OS

Ubuntu 16.04 LTS 
##### VERSION
xenial

```

```

##### ENVIRONMENT 

```

```

##### CONFIGURATION

```

```

##### SUMMARY

Hi! I wanted to report an issue regarding missing folders while installing IXP-Manager v4 using automated script. In the following path **App/Http/Controllers** we have two missing folders named **ConsoleServer**, **Customer** in it. Also some files in the view of the customer are also missing. Kindly resolve this issue as soon as possible.

**Comment by barryo** [comment]
Hi @zaziz01 - how are these issues manifesting themselves?

If you are using the automated script it should [be checking out](https://github.com/inex/IXP-Manager/blob/master/tools/installers/ubuntu-lts-1604-ixp-manager-v4.sh#L340) [v4.7.3](https://github.com/inex/IXP-Manager/blob/master/tools/installers/ubuntu-lts-1604-ixp-manager-v4.sh#L38) where there should be no issue.

**Comment by barryo** [comment]
I'm going to close this now pending an update from you as I don't believe there's an issue here.

**Comment by zaziz01** [comment]
Hi barry!I have re-installed IXP-Manager on a separate vm(ubuntu 16.04)using automated script in order to check all the files are cloned from the git using version 4.7.3. But the result remains the same. Customer and ConsoleServer folders are missing on the path App/Http/Controllers and customer files are missing in the resources/views folder as well. I dont know why it is happening?

Sent from Yahoo Mail on Android 
 
  On Wed, 30 May 2018 at 1:47 pm, barryo<notifications@github.com> wrote:   
Hi @zaziz01 - how are these issues manifesting themselves?

If you are using the automated script it should be checking out v4.7.3 where there should be no issue.

**Comment by barryo** [comment]
> Customer and ConsoleServer folders are missing on the path App/Http/Controllers and customer 
> files are missing in the resources/views folder as well. I dont know why it is happening?

Maybe you missed it but what I also asked was how are these issues manifesting themselves?

Those folders / files are not part of v4.7.3 but in master and will be released over the next few days as v4.8.0.

**Comment by zaziz01** [comment]
Hi Barry!Thanks for the reply. I don't know why it's happening.  When I added the user interface for faucet controller, then click on customer button in the dashboard it says in the logs CustomerController doesn't exists. When I copy pasted the two missing folder this error is removed but then it says Views (Customer.views) not found. Then I added the missing files in it this error gets removed. Then this error comes. And I am still unable to access the customer panel.
 production.ERROR: Undefined method 'getAllForFeList'. The method name must start with either findBy or findOneBy! {"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'getAllForFeList'. The method name must start with either findBy or findOneBy! at /srv/ixpmanager/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:226)



| 

 | 


 |


    On Thursday, May 31, 2018, 12:58:44 PM GMT+5, barryo <notifications@github.com> wrote:  
 
 

Customer and ConsoleServer folders are missing on the path App/Http/Controllers and customer
files are missing in the resources/views folder as well. I dont know why it is happening?


Maybe you missed it but what I also asked was how are these issues manifesting themselves?

Those folders / files are not part of v4.7.3 but in master and will be released over the next few days as v4.8.0.
