### ISSUE TITLE
update-l2database.pl inserts multiple copies of a mac address into the macaddress table

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#422]
if a MAC is learned from several interfaces, update-l2database.pl will attempt to insert multiple copies of the same mac into the macaddress database, e.g.

```
INSERT: c01e2f23ffff -> switch1:Port-Channel101
INSERT: c01e2f23ffff -> switch1:Port-Channel101
INSERT: c01e2f23ffff -> switch1:Port-Channel101
INSERT: c01e2f23ffff -> switch1:Port-Channel101
INSERT: c01e2f23ffff -> switch1:Port-Channel101
INSERT: c01e2f23ffff -> switch1:Port-Channel101
```

this needs to be fixed to eliminate duplicates.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.
