### ISSUE TITLE
sflow-detect-ixp-bgp-sessions is not vlan aware

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#427]
##### SUMMARY

`sflow-detect-ixp-bgp-sessions` is not vlan aware.  This means that if there are multiple vlans with the same IP address mappings, then it's pot luck as to which ip address mapping will be used.

##### STEPS TO REPRODUCE

e.g. quarantine vlan with the same IP addresses as a production VLAN.

**Comment by barryo** [comment]
@nickhilliard  - see [this change](https://github.com/islandbridgenetworks/IXP-Manager/blob/b2da2f5992f7d57c46f2e07263cebf111379e3ad/tools/runtime/sflow/sflow-detect-ixp-bgp-sessions#L216) which limits ip mappings to vlans enabled for the peering matrix only.

I think it's okay to ignore the edge case of multiple vlans with same IPs enabled for the peering matrix and just document it?

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.
