### ISSUE TITLE
bgpsessiondata table uses vlan instead of vlanid

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#428]
##### ISSUE TYPE

Design issue / feature request

##### SUMMARY

The `bgpsessiondata` table should use vlanid instead of the vlan 802.1q tag number.  This is to support multiple infrastructures using overlapping 802.1q tags.

This will need:
- [ ] some work in the bgpsessiondata controller too
- [ ] a migration script to update the db from 802.1q tag to vlanid
- [ ] a CLI option to specify the infrastructure ID
- [ ] support for API which emits vlanid

**Comment by barryo** [comment]
Closing because we have replaced this table with `bgp_sessions` which is more efficient and does not contain a vlan tag/id as this is determined from the ip address id. A separate issue exists to rewrite the sflow detector to use the new table.
