### ISSUE TITLE
Cancel button in contact/user edit goes to 404

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#432]
##### ISSUE TYPE

Bug Report

##### VERSION

```
V4.8.0
```

##### SUMMARY
Cancel button in contact edit page goes to 404.

##### STEPS TO REPRODUCE
Edit a contact.
Click cancel button.

##### EXPECTED RESULTS
Return to contacts overview page

Tries to go to: `https://servername/customer/overview/id/<id>/tab/contacts`

Should go to: `https://servername/customer/overview/<id>/contacts`

##### ACTUAL RESULTS
404 Error

**Comment by barryo** [comment]
Closing -> this is currently being rewritten with an internal pull request.
