### ISSUE TITLE
Deleting a customer note throws an error

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#435]
##### ISSUE TYPE

Bug Report

##### VERSION

```
4.8.0
```

##### SUMMARY
Deleting a customer note throws an error.

##### STEPS TO REPRODUCE
Access customer page.
Click notes tab
Click delete on a note in the list.

##### EXPECTED RESULTS
Note should be deleted and disappear from the list.

##### ACTUAL RESULTS
Pop up: `Error running ajax query for https://servername/api/v4/customer-note/delete/101`

- When refreshing the page, The note appears to have then been deleted anyway.

##### IMPORTANCE
Minor

**Comment by yannrobin** [comment]
Hello,

Does it work when you add a new note ? Do you receive the email of notification ?

IXP manager send notification emails when you add/delete/modify a customer note. It might come from that.

Thanks

**Comment by yannrobin** [comment]
Mark as deprecated this page :

https://github.com/inex/IXP-Manager/wiki/Multi-IXP-Functionality

**Comment by listerr** [comment]
Okay - just to update: There was a superadmin user with a blank email address. I've since added an address to this profile and opted the user out of note notifications.
