### ISSUE TITLE
Customer with no country defaults to "Afghanistan"

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#437]
##### ISSUE TYPE

Bug Report

##### VERSION

```
4.8.0
```

##### CONFIGURATION
```
APP_ENV=production
APP_DEBUG=false
APP_URL="https://portal.lonap.net"
APP_TIMEZONE="Europe/London"
APP_LOG="single"
APP_LOG_LEVEL=debug
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=true
IXP_AS112_UI_ACTIVE=false
GRAPHER_BACKENDS="mrtg|sflow"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"
GRAPHER_BACKEND_SFLOW_ENABLED=true
GRAPHER_BACKEND_SFLOW_ROOT="http://sflow.lonap.net/grapher-sflow"
GRAPHER_BACKEND_SMOKEPING_ENABLED=false
GRAPHER_CACHE_ENABLED=false
VIEW_SKIN="lonap"
VIEW_SMARTY_SKIN="lonap"
AUTH_ZF1_PWHASH="bcrypt"
CACHE_DRIVER=array
SESSION_DRIVER=file
DOCTRINE_PROXY_AUTOGENERATE=false
DOCTRINE_CACHE=array
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_FE_FRONTEND_DISABLED_RS_PREFIXES=true
IXP_FE_FRONTEND_DISABLED_NETINFO=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=false
IXP_FE_FRONTEND_DISABLED_CONSOLE=false
IXP_FE_FRONTEND_DISABLED_LOGO=false
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
IXP_IRRDB_BGPQ3_PATH=/usr/local/bin/bgpq3
IXP_IRRDB_MIN_V4_SUBNET_SIZE=24
IXP_IRRDB_MIN_V6_SUBNET_SIZE=48
```
##### SUMMARY
When editing existing customer Billing and Registration Details, if the customer has no country, the drop-down list defaults to "Afghanistan". This is then saved to the database along with any other changes.

##### STEPS TO REPRODUCE

1. Edit a customer with no country. Change some other field like Invoice E-Mail.
2. Fail to notice the country has now been set to Afghanistan.
3. Click save.

##### EXPECTED RESULTS

Either:

- Default in the list should be blank country.

or

- As there appears to be no way to delete the country back to blank, seems we've now decided that "Country" is mandatory. Trying to save a blank country should result an an error, not just picking the first thing in the drop-down list.

##### ACTUAL RESULTS
Woohoo! We just gained another customer in Afghanistan and confused our billing.

##### IMPORTANCE
Medium important.

**Comment by barryo** [comment]
@yannrobin - this needs to have an empty default.
