### ISSUE TITLE
Contact groups not appearing correctly in 4.8.0 interface

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#439]
##### ISSUE TYPE

Bug Report

##### VERSION

```
4.8.0
```

##### SUMMARY
Contact groups drop-down list not appearing.

We have the following defined in application.ini:

```
contact.group.types.ROLE = "Role"
contact.group.types.CONTACTFLAGS = "Contact Flags"
contact.group.types.CAMPAIGNS = "Campaigns"
contact.group.types.MAIL= "Mail Prefs"
```
The types show up in the interface, however, the groups defined for each type do not show up in the drop-down list.

##### ACTUAL RESULTS
Contact groups drop-down does not appear.

##### IMPORTANCE
We are using contact groups for things inc. our GDPR compliance recording so this is important feature for us.

**Comment by barryo** [comment]
@yannrobin  - looks like a Javascript issue:

![2015-04-05 17 41 06](https://user-images.githubusercontent.com/804649/45361778-fa2bdd00-b5ca-11e8-80d2-7e1380672ce3.jpg)

Read: https://github.com/inex/IXP-Manager/wiki/Contact-Groups

See: https://www.inex.ie/ixpdev/contact/edit/id/701  and select something from the groups dropdown.
