### ISSUE TITLE
Option to set cross connect info date fields to YYYY-MM-DD instead of dd/mm/yyyy

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#444]
**Is your feature request related to a problem? Please describe.**

I am populating the cross-connect information, and part of this involves copying and pasting the dates into the form, for example:

- Assigned At:
- Connected At:
- Ceased At: 

These date input fields are in `DD/MM/YYYY` format.

I'm pasting the dates from the customer notes, which is where we keep a note of when we connected/moved a port. The customer note date format is ISO8601 type `YYYY-MM-DD hh:mm`

**Describe the solution you'd like**
Option to change the date input fields in cross-connect info to same format as customer notes, which are` YYYY-MM-DD hh:mm` - this would reduce the amount of re-keying we need to do when pasting between the two, and present a more consistent date format in the interface.

(All dates everywhere should really be in `YYYY-MM-DD hh:mm` format, or at least input and displayed in the same format everywhere.)

**Describe alternatives you've considered**
Because the customer notes are freeform text, it is not really feasible to automate customer notes to patch panel info population. We have various sources for the patch panel info and would like to preserve the connected date information.

**Comment by barryo** [comment]
@yannrobin - pause this until we have a think about it.

The patch panel entries are HTML5 date form fields and respond to the locale of the user's own browser, which I think is correct and more standards compliant.

We should probably display the other dates using the same locale assuming it's in the HTTP request header.

**Comment by listerr** [comment]
My thoughts:-

- Make all dates ISO8601 `YYYY-MM-DD hh:mm`  format, then they are not locale-specific.
- Make the date input fields copy/paste friendly so that I can just type/paste the dates without a bunch of clicking when populating the fields from other sources. (i.e, make the calendar input an option)

I've done one site and it was an awful lot of clicking in these date fields and slowed things down somewhat. It took several hours and was a bit error-prone.

I'll hold off on adding the bigger sites for now.

**Comment by barryo** [comment]
Hey @listerr - just for expectation setting: we won't be able to look at this for a couple months at least because it's fiddly, not simple and needs a bit of thought on an overall approach.

**Comment by listerr** [comment]
Thanks. Realised now this can of worms went from: "This form is a bit awkward to use" to:
"think about the way all dates should be displayed and entered."

**Comment by listerr** [comment]
... Is there a way to relax the date input fields here so that I can paste the dates in rather than having to click and select each one?

Still an outstanding task of mine to enter all of these, and I still have a couple of hundred ports to input, so anything that can make this task a bit less tedious would be appreciated.

With the current COVID-19 situation, we're having to add the panel information for all of the Telehouse sites so that, where possible, we can direct patching to be done with by remote hands.

I've added every single sub-panel as a panel in IXPM, This amounts to a total of 54 panels of 6 or 12 ports. Not all of these are currently populated, but it's something like 230 ports in total.

**Comment by barryo** [comment]
I'm not sure if it's possible for you @listerr but if I had this kind of data population issue I'd try and script it into a bunch of SQL UPDATEs. Granted, easier said than done.

We're not going to actually change the input type from `type="date"` to `type="text"` - that would be a regression in my mind. These are dates, the correct input type is date.

That's not to say I don't have a solution for you :wink:

There's a great Firefox plugin called [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) that lets you run bits of Javascript on specific pages. You just need that to run the following:

```js
document.getElementById('connected_at').type = 'text';
document.getElementById('assigned_at').type = 'text';
document.getElementById('ceased_at').type = 'text';
document.getElementById('ceased_requested_at').type = 'text';
```

and you'll have input text fields instead. You could also add this to a skinned version of the appropriate view file but it's better not to change those unless absolutely necessary.

**Comment by listerr** [comment]
Agree making the date a text field not good.

I see that the date picker is optional - you can either just type the date in the box, or used the date picker to populate it. IXPM supports typing in the date, but not _pasting_ in a date. Hmmm.

I'll see if I can write something import into the database directly rather than fight the interface.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: headache level++++++ - we can enter dates, not broken, no planned changes.*
