### ISSUE TITLE
NIXA is not listed in ixpmanager.org ixps list 

### ISSUE THREAD

**Issue by mujibhabibi** [inex/IXP-Manager#457]
as we are also using IXP Manger in our IXP but we are not able to see the NIXA (National internet exchange of afghanistan) in the list any help will be appreciate

**Comment by barryo** [comment]
Hi @mujibhabibi 

Please provide the following details and we will add it - your IXP's: full name, short name, city / region / country, GPS co-ordinates and website URL.

**Comment by nickhilliard** [comment]
great thanks - now added.

**Comment by nickhilliard** [comment]
+added to ixpdb:

https://www.ixpdb.net/en/ixpdb/provider/749/
