### ISSUE TITLE
Querying the signal level in optical modules

### ISSUE THREAD

**Issue by ericandrei** [inex/IXP-Manager#465]
**Is your feature request related to a problem? Please describe.**
We recently had a small disruption to the Interlan-IX infrastructure, which was manifested by the attenuation of optical signal in some inter-POP links.

**Describe the solution you'd like**
I asked our tech for a history of signal levels between inter-POP links (graph or table), but they told me that did not have such data. Then I thought that a feature could be implemented in Switches section of IXP Manager, by which the signal level received by the optical modules could be queried and showed. And thinking further,  it would be helpful to have a history of these signal levels as graphs.

**Describe alternatives you've considered**

**Additional context**

**Comment by barryo** [comment]
Hoi @ericandrei - this is definitely on our list of things to do.

**Comment by ericandrei** [comment]
Hi,

Any news with this?

**Comment by barryo** [comment]
Quick look around indicates every switch seems to have its own (or no) way of doing this via SNMP which would mean per-platform support via OSS_SNMP.

Arista example:

```
Using SNMP server, you can poll the TX/RX power of the transceivers using the below OID’s:

OID RX Power: .1.3.6.1.2.1.99.1.1.1.4.1003XX21Y (Y=3)
OID TX Power: .1.3.6.1.2.1.99.1.1.1.4.1003XX21Y (Y=2)

1003XX21Y

XX = Port Number.
Y = 1,2 & 3.
if, Y=1 means TX Bias Sensor for that port
    Y=2 means TX Power Sensor for that port
    Y=3 means RX Power Sensor for that port

 

For instance, to fetch TX  power for a interface ethernet5.

#sh snmp mib get 1.3.6.1.2.1.47.1.1.1.1.2.100305212

ENTITY-MIB::entPhysicalDescr[100305212] = STRING: DOM TX Power Sensor for Ethernet5

#sh snmp mib get 1.3.6.1.2.1.47.1.1.1.1.2.100305212

ENTITY-MIB::entPhysicalDescr[100305212] = STRING: DOM TX Power Sensor for Ethernet5
```

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues.

Where appropriate, will:

* Relocate to the IDEAS file.
* Add additional information below.
* No relocation / additional information for uber-stale issues.

*Additional information: this has been relocated to IDEAs. NB: Ideas is not where things go to die (check the history of the file). It's where I house keep things that have no short term prospects of implementation. We will need to (re)consider the architecture we use to poll switches to implement this as it is so vendor specific. It is definitely something on our plans and a languishing open issue is not required to keep this on the planning list.*
