### ISSUE TITLE
compare-route-server-prefixes.pl broken if allow more specifics enabled

### ISSUE THREAD

**Issue by Edrichdelange** [inex/IXP-Manager#466]
##### ISSUE TYPE

Bug Report

##### OS
Ubuntu

##### VERSION

define( 'APPLICATION_VERSION', '4.8.999' );
define( 'APPLICATION_VERDATE', '201807060000' );

```

```

##### ENVIRONMENT 

```

```

##### CONFIGURATION

```

```

##### SUMMARY
compare-route-server-prefiex.pl breaks for the entire peer if more specifics enabled
##### EXPECTED RESULTS
To have some accepted routes for the peer in question

##### ACTUAL RESULTS
No routes are displayed

##### IMPORTANCE
Medium, as helps having route filters correct

**Comment by AleksBelytskyi** [comment]
Hello,

Is there some fix for this problem?

**Comment by AleksBelytskyi** [comment]
thank you for the fast response.
will wait for a solution

**Comment by barryo** [comment]
From the [v5.0.0 release notes](https://github.com/inex/IXP-Manager/tree/v5.0.0):

> The Route Server Prefix Analysis tool has been deprecated (but not removed). It has been replaced 
> with a new tool that queries all Bird v2 route servers live to give a complete and accurate report on 
> filtered prefixes.

As @nickhilliard mentioned above, *we can't fix this problem within the scope of the existing perl code, so the entire mechanism needs to be rethought*. This has happened and a new tool is now available for Bird v2. 

See: https://docs.ixpmanager.org/features/route-servers/#displaying-filtered-prefixes
