### ISSUE TITLE
Error when Deleting customer v4.8

### ISSUE THREAD

**Issue by webbyenterprises** [inex/IXP-Manager#469]
Bug Report

OS: Ubuntu 16.04.4 LTS

Version: define( 'APPLICATION_VERSION', '4.8.0' );
define( 'APPLICATION_VERDATE', '201807030000' );

Environment:
PHP 7.0.29-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:34:50) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.29-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

ii  libapache2-mod-php7.0               7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                          1:60+ubuntu16.04.1+deb.sury.org+1                        all          Common files for PHP packages
ii  php-ds                              1.2.5-1+ubuntu16.04.1+deb.sury.org+1                     amd64        PHP extension providing efficient data structures for PHP 7
ii  php-gettext                         1.0.11-2+deb.sury.org~xenial+1                           all          read gettext MO files directly, without requiring anything other than PHP
ii  php-igbinary                        2.0.6~rc1-1+ubuntu16.04.1+deb.sury.org+1                 amd64        igbinary PHP serializer
ii  php-memcache                        3.0.9~20160311.4991c2f-7+ubuntu16.04.1+deb.sury.org+1    amd64        memcache extension module for PHP
ii  php-memcached                       3.0.4+2.2.0-1+ubuntu16.04.1+deb.sury.org+1               amd64        memcached extension module for PHP, uses libmemcached
ii  php-msgpack                         2.0.2+0.5.7-3+ubuntu16.04.1+deb.sury.org+1               amd64        PHP extension for interfacing with MessagePack
ii  php-pear                            1:1.10.5+submodules+notgz-1+ubuntu16.04.1+deb.sury.org+1 all          PEAR Base System
ii  php-rrd                             2.0.1+1.1.3-4+ubuntu16.04.1+deb.sury.org+1               amd64        PHP bindings to rrd tool system
ii  php-yaml                            2.0.2+1.3.1-1+ubuntu16.04.1+deb.sury.org+1               amd64        YAML-1.1 parser and emitter for PHP
ii  php7.0                              7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.0-bcmath                       7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Bcmath module for PHP
ii  php7.0-cgi                          7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.0-cli                          7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                       7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        documentation, examples and common module for PHP
ii  php7.0-curl                         7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        CURL module for PHP
ii  php7.0-gd                           7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        GD module for PHP
ii  php7.0-intl                         7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Internationalisation module for PHP
ii  php7.0-json                         7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        JSON module for PHP
ii  php7.0-mbstring                     7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        MBSTRING module for PHP
ii  php7.0-mcrypt                       7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        libmcrypt module for PHP
ii  php7.0-mysql                        7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        MySQL module for PHP
ii  php7.0-opcache                      7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Zend OpCache module for PHP
ii  php7.0-readline                     7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        readline module for PHP
ii  php7.0-snmp                         7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        SNMP module for PHP
ii  php7.0-xml                          7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.0-zip                          7.0.29-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Zip module for PHP

##### CONFIGURATION
APP_DEBUG=true
APP_URL="http://manage.cf-ix.org"
APP_TIMEZONE="America/New_York"
APP_LOG="single"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=true
GRAPHER_BACKENDS="mrtg"
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"
VIEW_SKIN="cfix"
CACHE_DRIVER=memcached
SESSION_DRIVER=file
DOCTRINE_PROXY_AUTOGENERATE=true
DOCTRINE_CACHE=memcached
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_IRRDB_BGPQ3_PATH="/usr/bin/bgpq3"
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false

##### SUMMARY
When deleting a customer, error message occurs of:
The page has expired due to inactivity. 

Please refresh and try again.

**Comment by yannrobin** [comment]
@barryo this bug have already been fixed on inex master. It was because there was no CSRF token sent with the form.

Its seems that the V4.8 have not been updated with that fix.

Previous GitHub Issue : https://github.com/inex/IXP-Manager/issues/433

Commit : https://github.com/inex/IXP-Manager/commit/d023e786158de2aad1e70f0da65501442b181f0d

Thanks

**Comment by webbyenterprises** [comment]
I can confirm adding that line to 143 of delete.foil.php corrects the issue.

**Comment by barryo** [comment]
Thanks @yannrobin  - merged into the v4.8 branch now.
