### ISSUE TITLE
Please kindly advise step-by-step to turn-on slow feature on Ubuntu.

### ISSUE THREAD

**Issue by chantalay** [inex/IXP-Manager#470]
Hello,

I try to turn-on sflowtool on IXPMANAGER but I got some error about API as below result. Please kindly advise step-by-step to turn-on slow feature on Ubuntu.

OS: Ubuntu 16
 more /usr/local/etc/ixpmanager.conf
<sql>
        dbase_type      = mysql
        dbase_database  = ixpmanager
        dbase_username  = ixpxxx
        dbase_password  = xxxxxx
        dbase_hostname  = 127.0.0.1
</sql>

<ixp>
        sflowtool = /usr/bin/sflowtool
        sflowtool_opts = -4 -p 6343 -l
        sflow_rrdcached = 1
        sflow_rrddir = /data/ixpmatrix
        sflow_macdbtype = configured
        apikey = OWWl1wL1pVbcgBkICpqNwgbvlBQ0l40
        apibaseurl = http://x.x.x.x/api/v4
</ixp>

./tools/runtime/sflow/sflow-to-rrd-handler --debug
FATAL: could not read IXP Manager API call on http://x.x.x.x/api/v4/sflow-db-mapper/learned-macs

**Comment by nickhilliard** [comment]
Can you post this to the ixpmanager mailing list? The github issue tracker is for handling bugs rather than dealing with support / misconfig.

The mailing list details are on: https://www.ixpmanager.org/support

**Comment by yabuqi** [comment]
请问，后续是怎么解决的，遇到同样的问题
./tools/runtime/sflow/sflow-to-rrd-handler --debug
FATAL: could not read IXP Manager API call on http://x.x.x.x/api/v4/sflow-db-mapper/learned-macs

**Comment by yabuqi** [comment]
请问，后续是怎么解决的，have the same question as follow:
./tools/runtime/sflow/sflow-to-rrd-handler --debug
FATAL: could not read IXP Manager API call on http://x.x.x.x/api/v4/sflow-db-mapper/learned-macs

**Comment by yabuqi** [comment]
solution information：https://www.inex.ie/pipermail/ixpmanager/2019-March/thread.html
