### ISSUE TITLE
Searchable LOA ref. / Add ticket ref to LOA

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#471]
**Is your feature request related to a problem? Please describe.**
Cannot see a way to search for LOAs by the automated reference number (PPP-xxxx) or via ticket reference.

**Describe the solution you'd like**
A way to insert the ticket reference (if present) into the LOA template.
Patch panel ports searchable by reference number and/or ticket reference.

**Comment by listerr** [comment]
Okay, Have just discovered that I can use <?= $t->ppp->getTicketRef() ?> to put the ticket ref into the LoA template.

Have also found that the internal PPP-xxxx number is searchable from the box in the top left, but not in the search box in the patch panel ports page. This only seems to accept name/colo ID among others?

**Comment by nickhilliard** [comment]
if you need the PPP-xxxx number to be searchable, can you create a separate ticket?  I.e. one issue per ticket, thx! :-)
