### ISSUE TITLE
Display reseller name on resold customer overview in admin page

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#478]
**Describe the solution you'd like**

When displaying a resold customer in the admin customer overview page, it shows a box with "Resold Customer" but I can't see anywhere in the interface where it displays which reseller is providing the resold customer.

Please can the name of the reseller be shown for resold customers (or make the "Resold Customer" box clickable so it goes to the reseller?)

**Describe alternatives you've considered**
Currently the only way to to see which reseller a resold customer relates to is by going to Edit Customer Details and then scrolling down to the Reseller drop-down list.

It also shows in Ports -> Edit -> See Fanout Port -> Return to Customer Overview

Would be handy if the reseller was displayed at the top level page.

**Comment by listerr** [comment]
Hello,

Either I'm going crazy or this change seems to have disappeared in latest update?

Rob

**Comment by barryo** [comment]
eh, it did. opps. fixed in v5.1.0.
