### ISSUE TITLE
Interface speed sort order

### ISSUE THREAD

**Issue by michaelkennedy** [inex/IXP-Manager#482]
Sort order on switch configuration speed is alphabetical, rather than by interface speed. Similar to #21 and #230. 

Sorting by Speed gives the following order:
```
80 Gbps
40 Gbps
30 Gbps
200 Gbps
20 Gbps
2 Gbps
100 Gbps
```

Rather than largest to smallest as expected:
```
200 Gbps
100 Gbps
80 Gbps
40 Gbps
...
1 Gbps
```

Entirely cosmetic bug observed on 4.8.999.

**Comment by barryo** [comment]
Thanks @michaelkennedy  - fixed and live @ INEX
