### ISSUE TITLE
SHA384 is not supported by your openssl extension

### ISSUE THREAD

**Issue by mhiconsult** [inex/IXP-Manager#483]
Hello,

I tried installing IXP-Manager on a fresh Ubuntu 16.04 LTS several times and keep getting : 

[RuntimeExecption]
SHA384 is not supported by your openssl extension, could not verify the phar file intergrity 

Please note that it's a VM on ESXi

##### ISSUE TYPE

Bug Report

##### VERSION

```

```

##### ENVIRONMENT 

```

```

##### CONFIGURATION

```

```

**Comment by barryo** [comment]
Hi @mhiconsult 

This looks like a known (and fixed) issue in composer: https://github.com/composer/composer/issues/7669

Their solution requires a manual upgrade of composer however.

In  the above commit, I have changed the version of composer we use by default which should solve this -> just get the latest version of the install script and try to run it again.
