### ISSUE TITLE
Closed accounts are still visible in the list marked "connected".

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#498]
Peers which already left our IXP are visible in the list at "https://manager.example.com/switch/configuration" marked "connected". We are using Version 4.9.0.

**Comment by barryo** [comment]
I'm in two minds about this - the feature is reflects the switch configuration and the correct way to remove it would be to remove the interfaces from the customer (de-provision).  But I think on balance, you are right - if the customer is marked as closed, don't show the ports. I'll commit a fix for this now...

**Comment by nickhilliard** [comment]
the difficulty with this is that ports associated with closed customers disappear off the radar.  There needs to be some mechanism to notify the operator about all the associated assets of a customer when they are marked as closed.

**Comment by barryo** [comment]
Switch config isn't that mechanism (or at least it's not meant to be) - it's the public / member view of the ports.
