### ISSUE TITLE
Reverse DNS fields sanity check

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#499]
**Is your feature request related to a problem? Please describe.**
Invalid characters in Reverse DNS fields result in invalid zone being generated.

**Describe the solution you'd like**
Sanity check the reverse DNS fields so there can't be any spaces or other invalid characters, strip any trailing "." etc.

**Additional context**
Any accidental spaces in the DNS fields results in the whole zone failing to load:

```
zone 81.57.5.in-addr.arpa/IN: loading from master file /home/scripts/db.rev.5.57.81 failed: extra input text
zone 81.57.5.in-addr.arpa/IN: not loaded due to errors.
```

**Comment by nickhilliard** [comment]
we've opened up an internal issue to look at this. Sanity-checking hostnames is a lot less fun than it sounds.
