### ISSUE TITLE
Qustion: Route Server Prefix Filtering Analysis Tool does not show any prefixes

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#502]
We have configured route servers, birdseye api, etc.  We can query our route servers via the built-in lookingglass within ixp manager. We also have a few RS peers exchaning prefixes, although no profixes are shown in the Route Server Prefix Filtering Analysis Tool.

Where should the rs prefix analysis tool normally generally get it's data from? via the birdseye api? any way to debug this?  thanks

**Comment by barryo** [comment]
Hi @schadom - if this is a new exchange, could you register it on https://www.ixpmanager.org/users as per the instructions there (if you're happy to be listed that is).

The system you're asking about is quite old and due for replacement using Birdseye in 2019. In the meantime, see: [the old docs here](https://github.com/inex/IXP-Manager/wiki/Route-Server-Prefix-Analysis-Tool).

I'm going to close this ticket as the best place to ask for help [is the mailing list](https://www.ixpmanager.org/support) - we do not provide support via GitHub issues. This [Google query](https://www.google.com/search?q=site%3Awww.inex.ie+compare-route-server-prefix.pl) will show some threads where this came up.
