### ISSUE TITLE
Login history not working after upgrading to v4.9.x

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#504]
After upgrading to v4.9.x the user login history at `/login-history/list` does not show correct timestamps for the last logins anymore. It looks like the timestamps are not getting updated inside the database anymore. Applied v4.9.2 patch but the problem still exists. Thanks

**Comment by barryo** [comment]
Thanks @schadom - I can confirm this as I'm already aware of it. Got dropped in the move to Laravel auth system. We'll get it sorted.

**Comment by listerr** [comment]
Not sure if this is related - login history works when clicked on, however in the logins summary page, it always shows as "Never".

![image](https://user-images.githubusercontent.com/3037635/54352818-6ce54600-464a-11e9-9333-113d3c7ac1e1.png)

**Comment by barryo** [comment]
@yannrobin - can you have a look at this in the `release-v4` branch please? It's obviously separate to the new user/customer stuff you're working on in the IBN repository.

**Comment by yannrobin** [comment]
Yes I fixed it on the user/customer branch, I will push the fix on release-v4

**Comment by rasssta** [comment]
Started to work again in 5.0.0 for me.

**Comment by barryo** [comment]
Should all be fixed in v5.
