### ISSUE TITLE
Can't issue bgp session query in 4.9

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#508]
##### ISSUE TYPE

Bug Report

##### OS

Ubuntu 18.04.1 LTS

##### VERSION

```
define( 'APPLICATION_VERSION', '4.9.2' );
define( 'APPLICATION_VERDATE', '201901210000' );
```

##### ENVIRONMENT 

```
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
# dpkg -l | grep php
rc  libapache2-mod-php7.0                 7.0.32-0ubuntu0.16.04.1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-php7.2                 7.2.10-0ubuntu0.18.04.1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                            1:60ubuntu1                                all          Common files for PHP packages
ii  php-gettext                           1.0.12-0.1                                 all          transitional dummy package for php-php-gettext
ii  php-igbinary                          2.0.5-1build1                              amd64        igbinary PHP serializer
ii  php-memcache                          3.0.9~20160311.4991c2f-5build2             amd64        memcache extension module for PHP
ii  php-memcached                         3.0.1+2.2.0-1build2                        amd64        memcached extension module for PHP, uses libmemcached
ii  php-msgpack                           2.0.2+0.5.7-2build1                        amd64        PHP extension for interfacing with MessagePack
ii  php-mysql                             1:7.2+60ubuntu1                            all          MySQL module for PHP [default]
ii  php-pear                              1:1.10.5+submodules+notgz-1ubuntu1.18.04.1 all          PEAR Base System
ii  php-php-gettext                       1.0.12-0.1                                 all          read gettext MO files directly, without requiring anything other than PHP
ii  php-rrd                               2.0.1+1.1.3-4build1                        amd64        PHP bindings to rrd tool system
ii  php-zip                               1:7.2+60ubuntu1                            all          Zip module for PHP [default]
rc  php7.0-bcmath                         7.0.32-0ubuntu0.16.04.1                    amd64        Bcmath module for PHP
ii  php7.0-common                         7.0.32-0ubuntu0.16.04.1                    amd64        documentation, examples and common module for PHP
rc  php7.0-curl                           7.0.32-0ubuntu0.16.04.1                    amd64        CURL module for PHP
rc  php7.0-intl                           7.0.32-0ubuntu0.16.04.1                    amd64        Internationalisation module for PHP
rc  php7.0-json                           7.0.32-0ubuntu0.16.04.1                    amd64        JSON module for PHP
ii  php7.0-mbstring                       7.0.32-0ubuntu0.16.04.1                    amd64        MBSTRING module for PHP
rc  php7.0-mcrypt                         7.0.32-0ubuntu0.16.04.1                    amd64        libmcrypt module for PHP
rc  php7.0-mysql                          7.0.32-0ubuntu0.16.04.1                    amd64        MySQL module for PHP
rc  php7.0-opcache                        7.0.32-0ubuntu0.16.04.1                    amd64        Zend OpCache module for PHP
rc  php7.0-readline                       7.0.32-0ubuntu0.16.04.1                    amd64        readline module for PHP
rc  php7.0-snmp                           7.0.32-0ubuntu0.16.04.1                    amd64        SNMP module for PHP
ii  php7.0-xml                            7.0.32-0ubuntu0.16.04.1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
rc  php7.0-zip                            7.0.32-0ubuntu0.16.04.1                    amd64        Zip module for PHP
ii  php7.2                                7.2.10-0ubuntu0.18.04.1                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.2-bcmath                         7.2.10-0ubuntu0.18.04.1                    amd64        Bcmath module for PHP
ii  php7.2-cli                            7.2.10-0ubuntu0.18.04.1                    amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common                         7.2.10-0ubuntu0.18.04.1                    amd64        documentation, examples and common module for PHP
ii  php7.2-curl                           7.2.10-0ubuntu0.18.04.1                    amd64        CURL module for PHP
ii  php7.2-intl                           7.2.10-0ubuntu0.18.04.1                    amd64        Internationalisation module for PHP
ii  php7.2-json                           7.2.10-0ubuntu0.18.04.1                    amd64        JSON module for PHP
ii  php7.2-mbstring                       7.2.10-0ubuntu0.18.04.1                    amd64        MBSTRING module for PHP
ii  php7.2-mysql                          7.2.10-0ubuntu0.18.04.1                    amd64        MySQL module for PHP
ii  php7.2-opcache                        7.2.10-0ubuntu0.18.04.1                    amd64        Zend OpCache module for PHP
ii  php7.2-phpdbg                         7.2.10-0ubuntu0.18.04.1                    amd64        server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php7.2-readline                       7.2.10-0ubuntu0.18.04.1                    amd64        readline module for PHP
ii  php7.2-snmp                           7.2.10-0ubuntu0.18.04.1                    amd64        SNMP module for PHP
ii  php7.2-xml                            7.2.10-0ubuntu0.18.04.1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.2-zip                            7.2.10-0ubuntu0.18.04.1                    amd64        Zip module for PHP

```

##### CONFIGURATION

```
I don't think it's relevant in this case. Contact me off github if you need it :)
```

##### SUMMARY

After upgrading to 4.9 I executed the following query and got an ERROR:

MariaDB [ixpng]> INSERT INTO bgp_sessions (srcipaddressid, dstipaddressid, protocol, packetcount, last_seen, source)
    ->     SELECT
    ->         srcipaddressid, dstipaddressid, protocol, count(packetcount) AS packetcount, max(timestamp) AS last_seen, any_value (source) AS source
    ->     FROM
    ->         bgpsessiondata
    ->     GROUP BY
    ->         srcipaddressid, dstipaddressid, protocol;
ERROR 1305 (42000): FUNCTION ixpng.any_value does not exist

MySQL client:
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

MySQL server:
$ dpkg -l |grep mariadb-se
ii  mariadb-server-10.1             10.1.26-0+deb9u1               amd64        MariaDB database server binaries
ii  mariadb-server-core-10.1        10.1.26-0+deb9u1               amd64        MariaDB database core server files

**Comment by barryo** [comment]
Here's the issue:

>  ERROR 1305 (42000): FUNCTION ixpng.any_value does not exist

and further reading on this at:

https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

There's a potential solution at:

https://jira.mariadb.org/browse/MDEV-10426?focusedCommentId=115278&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-115278

Some years ago (I'm talking >4 I think), we allowed for MySQL/MariaDB support. That's when there was the promise of binary compatibility. This didn't last unfortunately and now we only support MySQL >= 5.7 and it's been like this for the entirety of v4 I think.

I've been able to dump MariaDB tables and with some regex's allow them to be imported into MySQL successfully (non IXP Manager related but the point is it's possible).

**Comment by rasssta** [comment]
Ok. Thanks for the info!

**Comment by rasssta** [comment]
Re-opening since I found another issue that might be somewhat related to this problem with mariadb(?).

The column "remember_token" in the user table was *not* created when I upgraded from 4.8.0 -> 4.9.0 -> 4.9.1 -> 4.9.2 so I had to create it manually based on the information from another installation to get it working again.

Initially this didn't cause any issues but all of a sudden (1 day later) after logging in I got the "whoops" error and it started to complain about remember_token not existing when looking in laravel.log. All API calls started to fail as well.

**Comment by barryo** [comment]
Hey @rasssta 
> The column "remember_token" in the user table was not created when I upgraded from 4.8.0 -> 4.9.0 -> 4.9.1 -> 4.9.2 so I had to create it manually based on the information from another installation to get it working again.

There was an additional command added to the upgrade instructions and it was also highlighted in the [v4.9.0 release notes](https://github.com/inex/IXP-Manager/releases/tag/v4.9.0) under the *Upgrade Instructions* section:

> 3. if you missed it in the updated upgrade instructions, run this command: ${IXPROOT}/artisan migrate

In retrospect, I shouldn't have done it this way (Laravel migration) but it seemed like the right thing to do at the time. Should have stuck with Doctrine2 only migrations 😢

**Comment by rasssta** [comment]
I didn't miss it in the instructions! :) So I only ran it once (not twice).

From shell history:
chmod -R u+rwX $IXPROOT/public/bower_components ${IXPROOT}/bower.json             ${IXPROOT}/storage $IXPROOT/vendor $IXPROOT/var $IXPROOT/bootstrap/cache
${IXPROOT}/artisan migrate
${IXPROOT}/artisan cache:clear

**Comment by barryo** [comment]
> I didn't miss it in the instructions! :) 

Sorry for second guessing you! A couple of people did miss it on the mailing list.

> So I only ran it once (not twice).

Hmmm... once should have been enough ☹️ 

I don't know why it didn't work for you. It worked on all my dev runs and three prod boxes I upgraded.

**Comment by barryo** [comment]
> Some years ago (I'm talking >4 I think), we allowed for MySQL/MariaDB support. That's when there 
> was the promise of binary compatibility. This didn't last unfortunately and now we only support 
> MySQL >= 5.7 and it's been like this for the entirety of v4 I think.

This came up again from another user. The MySQL `ANY_VALUE()` isn't used from what I can see in the production code so if the upgrade halts on @rasssta 's original issue, the following pre-5.7 MySQL command should work (untested):

```mysql
INSERT INTO bgp_sessions (srcipaddressid, dstipaddressid, protocol, packetcount, last_seen, source)

    SELECT srcipaddressid, dstipaddressid, protocol, count(packetcount) AS packetcount, max(timestamp) AS last_seen, source

    FROM bgpsessiondata

    GROUP BY srcipaddressid, dstipaddressid, protocol; 
```

However, if you're running MariaDB or an older version of MySQL, you should plan to migrate to MySQL >= 5.7.
