### ISSUE TITLE
Hide infrastructures, in peering manager, that the customer is not connected to

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#511]
**Is your feature request related to a problem? Please describe.**
We have 3 infrastructures, 1 for each city where we're running an IX. When a customer, who is only present on 1 of these IXs (and therefore only 1 of the infrastructures) log in to IXP Manager and checks out the Peering Manager the user will get a list of all potential peers on *all* our 3 infrastructures.

This causes a lot of confusion and some customers have asked us how to set up peering with ASNs on the other infras as it appear to be possible in the peering manager.

**Describe the solution you'd like**
Hide the infrastructures, in peering manager, that the customer does not have a connection to. And a bonus solution: sort the infras based on name and not VLAN ID :-)

**Describe alternatives you've considered**
I've considered adding a text describing how all of this is intended to work, but it just seems to be a bad work-around to the actual problem...

**Additional context**
Customer's view when connected to only 1, out of our 3, infrastructures:
<img width="855" alt="untitled" src="https://user-images.githubusercontent.com/4455235/53157698-59ead300-35c2-11e9-80f5-fc32494e3151.png">

**Comment by rasssta** [comment]
This was related to that we were previously running the same VLAN tag on all 3 infrastructures. The problem fixed itself when we changed that. However, the code should perhaps (anyway) be changed to look at which infrastructure the customer is connected to instead of the VLAN tag?

**Comment by barryo** [comment]
Thanks @rasssta - that explains why we couldn't reproduce. Noted the issue and should we rewrite that could, we will bear this in mind.
