### ISSUE TITLE
Can't Add New Switches

### ISSUE THREAD

**Issue by devinweaverr** [inex/IXP-Manager#514]
-->

##### ISSUE TYPE

Hello I can't seem to add new switches to IXP Manager by SNMP or manually. SNMP communication is working. IXP Manager is able to poll the switch and prefills the Vendor and Model after entering the hostname and community, but after clicking add an error occurs. My web browser is forwarded to a generic "Error" page at /switch/store. I've attached the laravel logs if that helps. This is Ubuntu 16.0.4. IXP Manager was installed using the automated method provided.

##### VERSION

define( 'APPLICATION_VERSION', '4.9.3' );
define( 'APPLICATION_VERDATE', '201903080000' );
[laravel log.txt](https://github.com/inex/IXP-Manager/files/2950608/laravel.log.txt)

**Comment by barryo** [comment]
Hi @devinweaverr - this looks like we were expecting a non-null value back from the [OSS_SNMP](https://github.com/opensolutions/OSS_SNMP) (a library we use for SNMP polling).

@yannrobin has pushed a fix now (0c2c48784d101222dcd7fd0b6b4702c53a1750eb) - you can just change that one line until we release v4.9.4 in a few weeks.

**Comment by devinweaverr** [comment]
Hi @barryo and @yannrobin Thank you! I've made the additions to that line, however the error still occurs. I've restarted apache2 as well as rebooted the machine just in case.

**Comment by barryo** [comment]
What make and model of switch are you using @devinweaverr? I'll need to see what OSS_SNMP is sending back for you.

**Comment by devinweaverr** [comment]
@barryo It's a Cisco Nexus 9K. 92160YC-X.

Thank you for your help also!

**Comment by barryo** [comment]
Hi @devinweaverr - apologies, we committed an incorrect fix earlier.

If you replace the line in the question with the following it should work:


```php
             $this->object->setOsDate(       $platform->getOsDate() ?? null ); 
```

**Comment by devinweaverr** [comment]
That did it, @barryo ! Thank you so much!

**Comment by devinweaverr** [comment]
Unrelated issue that isn't as much of a big deal. I added them manually, but the switch ports were not automatically populated under the switch after it was added.

**Comment by barryo** [comment]
They should have been but I don't have any experience trying to add Nexus 9K's to IXP  Manager. If we gave you an IP could you allow remote access to snmp? If you could, can you email barry.odonovan (at) inex (dot) ie ?
