### ISSUE TITLE
Route Server LG doesn't work properly for BIRD 1.6.3

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#525]
I've briefly discussed this issue with @barryo off-github.

We're using birdseye in combination with bird 2.0.4 without any issues. However, our old bird 1.6.3 installations doesn't work properly with IXP Manager since it gives a 500 as soon as it comes to the first established state/pfx column. I've followed all the debugging steps on https://docs.ixpmanager.org/features/looking-glass/#debugging and it all works fine. No errors under router live status either.

I've tested the following change after input from Barry and after this change I can view the list of BGP peers for the specific RS, but I can't click on Details and if I click on the table link i get a 500 error.

```
diff /srv/ixpmanager/resources/views/services/lg/bgp-summary.foil.php bgp-summary.foil.php 
81c81
<                         <?php else: ?>
---
> 			<?php elseif( isset( $p->routes ) ): ?>
92c92
<                         <?php if( $p->state == 'up' ): ?>
---
> 			<?php if( $p->state == 'up' && isset($p->routes ) ): ?>
```

**Comment by rasssta** [comment]
I removed "import keep filtered on;" under protocol bgp pb_[...] in neighbors.foil.php and it fixed the problem fully.

**Comment by barryo** [comment]
Cool, thanks @rasssta. `import keep filtered on` isn't necessary anymore as all routes are accepted (but tagged as appropriate) into the per-member table.
