### ISSUE TITLE
Representation of never logged in users

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#531]
##### ISSUE TYPE

Bug Report

##### VERSION

```
define( 'APPLICATION_VERSION', '5.0.0' );
define( 'APPLICATION_VERDATE', '2019052100' );
```

##### SUMMARY

Older never-logged-in users show epoch(0) "1970-01-01 01:00:00" as their "last login" time instead of "Never" like newer users. Maybe the upgrade procedure can fix them?

**Comment by barryo** [comment]
The next release notes will include a request to run the following which is safe to do now also @rfc1036:

```mysql
UPDATE `customer_to_users` 
    SET last_login_date = NULL 
    WHERE last_login_date = '1970-01-01 00:00:00';
```

**Comment by rasssta** [comment]
@barryo Should be 01:00:00 instead of 00:00:00 :)

Same typo in release docs.

**Comment by barryo** [comment]
Don't think so. Not for me anyway.

**Comment by rasssta** [comment]
The initial post here states 01:00:00, and it was the same for me.

**Comment by rasssta** [comment]
I'm using CEST timezone, if that matters.

**Comment by rfc1036** [comment]
I had noticed the same thing and assumed that it was timezone-dependent.
