### ISSUE TITLE
CSS styling in Welcome E-mail preview (v5.0.0)

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#533]
##### ISSUE TYPE

Bug Report

##### OS

Ubuntu 18 LTS

##### VERSION

```
define( 'APPLICATION_VERSION', '5.0.0' );
define( 'APPLICATION_VERDATE', '2019052100' );
```

##### SUMMARY

The CSS styling in the Welcome E-mail suffers from the CSS "bug", that is present in some other places as well in v5.0.0, with lack of margin space.

With help from @barryo I fixed it in the other places (templates) with the following:
`s/<p>/<p class="tw-mb-6">`

However the Welcome e-mail seem to use .blade.php instead of .foil.php so I can't apply the same workaround there.

##### STEPS TO REPRODUCE

Create Welcome E-mail
Click on the Preview tab

**Comment by barryo** [comment]
Fixed via a505441e39bcddd4e8bab28cd31a937b9da57b2b
