### ISSUE TITLE
Summary/combined p2p-graphs for v4 *plus* v6 

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#534]
**Describe the solution you'd like**
We have had multiple customers that want to see a total graph of v4 and v6 traffic under the p2p section.

A couple of years back when there weren't much v6 traffic it was a cool feature to separate v6 from v4 just to follow the trend of the small amount of v6 traffic. Now when v6 is gaining more interest (hurray!) and traffic is starting to split more and more between v4 and v6 it gets a bit annoying for customers to look at their p2p graphs 2 times, for every peering partner.

**Describe alternatives you've considered**
Ideally a combined graph named "Total" or similar would be default for each peer. Then you can choose between v4 and v6 in the drop down instead of today's solution, which defaults to v4 and giving an option to select v6 in the drop down.

**Comment by barryo** [comment]
Ack'd @rasssta and we have this covered in a number of tickets / dev plans already. Closing as it's a duplicate - will be actioned though.
