### ISSUE TITLE
Customer views shows MMR ODF with cabinet position for patch-panel demarc

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#535]
**Is your feature request related to a problem? Please describe.**
Normally you have the same position, i.e fib 1-2, on both ends of the ODF. Let's say ODF 1.2.3 / fib 1-2 in your cabinet and ODF 4.5.6 / fib 1-2 in MMR. 

But in cases where this differs, let's say ODF 1.2.3 / fib 43-44 in your cabinet and ODF 4.5.6 / fib 7-8 in MMR, this will show inaccurate information under the customer port view as it will state: ODF 1.2.3 / fib 7-8.

**Describe the solution you'd like**
Show cabinet ODF name instead of MMR ODF name under customer port view.

FYI: The cross connect tab *does* show the cabinet ODF name.

**Describe alternatives you've considered**
https://gist.github.com/rasssta/7f203a945528f57fdd24efaa42c39d98

**Comment by barryo** [comment]
I'm not sure this is wrong. The description for these fields is:

* Name: The name / reference for the patch panel, displayed throughout IXP Manager. Using the co-location provider's reference is probably the sanest / least confusing option.
* Colo Ref: The reference the facility/co-location provider has assigned to this patch panel.

Your member should only see the colo ref.

Am I misunderstanding the issue?

**Comment by rasssta** [comment]
Correct way to handle it
* MMR ODF name + port number(s) in MMR ODF (fib 1-2 for example)
...or...
* Cabinet ODF name + port number(s) in Cabinet ODF

Incorrect way (which is the case here):
* MMR ODF name + port number(s) in Cabinet ODF

**Comment by rasssta** [comment]
Seems like you have to set "Patch Panel Name" and "Colocation Circuit Ref" to the same thing for it to be properly viewed in the UI right now, so I don't really understand why there are 2 fields instead of just 1?

Anyhow, I still think "Overview Tabs -> Ports" and "Overview Tabs -> Cross Connects" should use the same data for the cross connects instead of mixing getColoReference and getName.

Either:
`<?= $t->ee( $pi->getSwitchPort()->getPatchPanelPort()->getPatchPanel()->getColoReference() ) ?> -
`
or
`<?= $t->ee( $pi->getSwitchPort()->getPatchPanelPort()->getPatchPanel()->getName() ) ?> -`

I can show you some screenshots that "clarifies the confusion" for this issue if you contact me off github :-)

**Comment by barryo** [comment]
@listerr also has some good suggestions on the naming which I'm going to add here:

> Also, We have one data centre either rejecting LoAs or installing cables on
> the wrong ports, because they find the numbering in our LoAs ambiguous 
> because of the way the panels are numbered.
> 
> For example, if we send them a request to install to "Port 33/34 (17) 
> (duplex pair)" then they would install it at 17/18 (9), or if pair 9 was 
> already in use, they reject the LoA. Or not, if the installer understands
> what the thing in brackets means. Their system also doesn't allow for 
> ports > 24, so I need to convey to them that "33/34" means "Port 17" 
> on their system, as a request for "install to port 33/34" is rejected as 
> being > 24 and not a port on their system.
> 
> The panel is numbered by individual strands and not in pairs, so
> 
> Labelled: 1+2 is:  "Port 1"
> Labelled: 3+4 is:  "Port 2"
> ...
> Labelled: 19+20 is: "Port 10"
> 
> etc.
> 
> To them, and order to "Port x" means a duplex port or pair.
> 
> I had to make a local hack to:
> 
> /srv/ixpmanager/database/Entities/PatchPanelPort.php
> 
> To add a new function, to provide a port description that is hopefully 
> acceptable to them, so it now reads:
> 
> "Port: 8 (Fibre Pair, Positions 15/16) (duplex port)"
> "
>      /**
>       * Get better description for LoA:
>       *
>       * @return integer
>       */
>      public function getNameForLoa()
>      {
> 
>          if( $this->hasSlavePort() ) {
>              $name = ( $this->getNumber() % 2 ? ( floor( 
> $this->getNumber() / 2 ) ) + 1 : $this->getNumber() / 2 ) . ' ';
>              $name .= '(Fibre Pair, Positions ' . 
> $this->getPatchPanel()->getPortPrefix() . $this->getNumber();
>              $name .= '/' . $this->getDuplexSlavePortName() . ')';
> 
>          } else {
> 
>              $name = $this->getPatchPanel()->getPortPrefix() . 
> $this->getNumber();
> 
>          }
> 
>          return $name;
>      }
> 
> "
> 
> Then in the LoA template:
> 
> <?= $t->ee( $t->ppp->getNameForLoa() ) ?> <?php if( 
> $t->ppp->hasSlavePort() ){ ?><em>(duplex port)</em><?php } ?>

**Comment by barryo** [comment]
In the coming weeks / (maybe months but I'm thinking before end of the summer) I'll sit down with @nickhilliard and @yannrobin and we'll try and come up with a workable (and maybe flexible) solution that solves all issues and propose it here.

@listerr @nickhilliard

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues.

Where appropriate, will:

* Relocate to the IDEAS file.
* Add additional information below.
* No relocation / additional information for uber-stale issues.

*Additional information: this has been relocated to IDEAs. NB: Ideas is not where things go to die (check the history of the file). It's where I house keep things that have no short term prospects of implementation. This file now has a bunch of things for consideration when we review patch panels.*
