### ISSUE TITLE
Documenting the purpose of API keys

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#536]
It is hard to keep track of what API keys are used for and where.

I think that it would be useful to add to each entry of the table in /api-key/list an editable free text field to allow to document that.

**Comment by barryo** [comment]
This is a good idea.

On face value, it's simple. In reality, it's actually a non-trivial piece of work. As it stands, you can create API keys. Just hit the button and it's done. To fully implement this, we need a fuller CRUD type controller to add with the ability to set a description and then one will want to edit said description.

We'll get it done - just not sure when yet.

**Comment by rfc1036** [comment]
I suggest to start with something simple: hit the button, answer the "what is this for?" question in a modal window and store the answer forever. You can always add later a more complex UI. :-)

**Comment by barryo** [comment]
@yannrobin - can you:

- [ ] turn controller into Doctrine2Frontend
- [ ] key remains read only once created
- [ ] on adding and editing, allow to set/edit the description and (optionally) the expiration datetime
- [ ] most applications only show the key once in the UI when created and does not display it again. Can you create a `ixp_fe.security.show_api_keys` config option and default to false (with env option `IXP_FE_SECURITY_SHOW_API_KEYS`). If this is false, only show the first 6 characters of the key following by ellipses (`...`)
- [ ] show description as `<em></em>` under the key (via `<br>`)  
- [ ] update the auth API check to examine the expiration datetime
- [ ] add to artisan command `utils:expunge-logs` to remove API keys with non-null expiration >3 months ago

**Comment by barryo** [comment]
Documentation also updated @ https://docs.ixpmanager.org/features/api/
