### ISSUE TITLE
RS Looking Glass sort order

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#544]
##### SUMMARY
Not sure if this should be in IXP Manager or Looking glass project - it includes a sort option at the top for "State/PfxRcd" but this sorts lexical order rather than numerically. Other columns (asn etc.) sort correctly in numerical order.

##### STEPS TO REPRODUCE

Click sort option on the "State/PfxRcd" column.

![image](https://user-images.githubusercontent.com/3037635/61442456-8faca180-a93f-11e9-88c6-09861f63e48c.png)

**Comment by barryo** [comment]
Should be here - @yannrobin can you add invisible sorting columns for these with -1 for any non-numeric value?

**Comment by yannrobin** [comment]
Sure I will
