### ISSUE TITLE
500 server error changing patch panel port

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#545]
##### ISSUE TYPE

Bug Report

##### VERSION
```
define( 'APPLICATION_VERSION', '5.0.0' );
define( 'APPLICATION_VERDATE', '2019052100' );
```

##### CONFIGURATION

```
APP_ENV=production
APP_DEBUG=false
APP_URL="https://portal.lonap.net"
APP_TIMEZONE="Europe/London"
APP_LOG="single"
APP_LOG_LEVEL=debug
IXP_FE_FRONTEND_DISABLED_LOGO=false
IXP_FE_CUSTOMER_BILLING_UPDATES_NOTIFY="....."
IXP_FE_FRONTEND_DISABLED_RS_PREFIXES=true
IXP_FE_FRONTEND_DISABLED_NETINFO=true
IXP_FE_FRONTEND_DISABLED_CUSTKIT=false
IXP_FE_FRONTEND_DISABLED_CONSOLE=true
IXP_FE_FRONTEND_DISABLED_LOGO=false
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
IXP_MULTIIXP_ENABLED=false
IXP_RESELLER_ENABLED=true
IXP_RESELLER_RESOLD_BILLING=false
IXP_AS112_UI_ACTIVE=false
GRAPHER_BACKENDS="mrtg|sflow"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"
GRAPHER_BACKEND_SFLOW_ENABLED=true
GRAPHER_BACKEND_SFLOW_ROOT="http://sflow.lonap.net/grapher-sflow"
GRAPHER_BACKEND_SMOKEPING_ENABLED=false
GRAPHER_CACHE_ENABLED=false
VIEW_SKIN="lonap"
VIEW_SMARTY_SKIN="lonap"
AUTH_ZF1_PWHASH="bcrypt"
CACHE_DRIVER=array
SESSION_DRIVER=file
DOCTRINE_PROXY_AUTOGENERATE=false
DOCTRINE_CACHE=array
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_IRRDB_BGPQ3_PATH=/usr/local/bin/bgpq3
IXP_IRRDB_MIN_V4_SUBNET_SIZE=24
IXP_IRRDB_MIN_V6_SUBNET_SIZE=48

```

##### SUMMARY
When changing certain patch panel ports, IXP Manager dies with 500 server error.
I'm trying to edit the reference number on a circuit but it's falling over with server error 500.
https://portal.lonap.net/patch-panel-port/edit/23

(from barry earlier):

String data, right truncated: 1406 Data too long for column 'colo_circuit_ref' at row 1
8 10:18	looks like we'll need to make that wider?

##### STEPS TO REPRODUCE

Add some text to colo circuit reference in
https://portal.lonap.net/patch-panel-port/edit/23

**Comment by barryo** [comment]
@yannrobin - when you're ready to look at this let's run through the column sizes on this table to see if they all make sense. And you'll need to set max length on validation afterwards to match so it gives the real reason rather than throwing a 500.

**Comment by yannrobin** [comment]
I will no problem
