### ISSUE TITLE
Looking Glass shows RPKI unknown for non-RS-ASN communities

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#560]
Seems like the LG displays "RPKI UNKNOWN" for *:1000:2 instead of only for your own RS ASN, in this case AS57151.

In this case AS8674 announce a prefix with LC 52005:1000:2 and the LG shows it as RPKI UNKNOWN. Not sure if this is a feature or a bug ;) 

![image](https://user-images.githubusercontent.com/4455235/65373806-94187200-dc82-11e9-94b2-a0ae941955d1.png)

**Comment by barryo** [comment]
We'll call it a bug :wink:

I suspect on the frontend looking glass code, I'm only looking at the second and third elements of the large community. They're pretty rare in the wild 😉 

Will sort for next release.
