### ISSUE TITLE
Error 500 Server Error on Forgot Password

### ISSUE THREAD

**Issue by vixp-org** [inex/IXP-Manager#564]
We installed IXP-manager with script and want to reset password for the created user:
/password/forgot
we always get 500 Server Error and in apache2 error.log nothing logged about this.

**Comment by barryo** [comment]
This feels like an installation issue. 

Please use the mailing list ( https://www.ixpmanager.org/support ) and please follow the tips in [The Best Way to Ask for Help](https://www.ixpmanager.org/support#asking-for-help) section. Thanks.
