### ISSUE TITLE
Fix HTTP(S) issues

### ISSUE THREAD

**Issue by vixp-org** [inex/IXP-Manager#565]
Some elements was loaded via http when website loaded via https.

Use Folders and Files without urls (domain) will solve this:
was loaded over HTTPS, but requested an insecure image `'http://ixpmanager.example.com/images/ixp-manager-white.png'. This content should also be served over HTTPS.`

**Comment by barryo** [comment]
This is loaded via `<?= asset( "images/ixp-manager-white.png" ) ?>` in the code. 

The issue will most likely be your settings in `.env` that lead to `http://ixpmanager.example.com`. Without a copy of your `.env` in the manner requested in the issue template I'm afraid I can't be of much more help. Feel free to reopen with your `.env`.
