### ISSUE TITLE
Question - Route Server Prefix Filtering Analysis Tool

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#575]
Hi,

we are running latest `IXP Manager release-v5` branch from Github. We have multiple `bird2 v2.0.6` routeservers running at our IXP, which all provide the latest `birdseye v1.2.2` as API-endpoint to our IXP Manager installation. The frontend looking glass within IXP Manager works perfectly fine and displays all info's including received BGP communities, appended LCs, IRR an RPKI ROV validation states, etc.

Except for the Route Server Prefix Filtering Analysis Tool, which currently displays just nothing at all for both admin users as well as logged-in customers/peers. Is there any special configuration or script needed for this to work?

Thanks in advance and best wishes
Dominic

**Comment by barryo** [comment]
> The frontend looking glass within IXP Manager works perfectly fine and displays all info's including received BGP communities, appended LCs, IRR an RPKI ROV validation states, etc.

🎉 

> Except for the Route Server Prefix Filtering Analysis Tool, which currently displays just nothing at all for both admin users as well as logged-in customers/peers. Is there any special configuration or script needed for this to work?

I'm guessing you're using the older version which is only there for legacy support. See [this documentaion](https://docs.ixpmanager.org/features/route-servers/#displaying-filtered-prefixes).

Enable the new one with the following in `.env`:

```
IXP_FE_FRONTEND_DISABLED_FILTERED_PREFIXES=false
```

and disable the old one by **removing** this if set:

```
IXP_FE_FRONTEND_DISABLED_RS_PREFIXES=false
```

If this isn't the issue, can you share a sanitised version of the `.env` file?

**Comment by schadom** [comment]
Oh, we had both of the variables above in the .env file...   @barryo I owe you a beer or coffee! Thanks a lot!
