### ISSUE TITLE
Error500 on User Mgmt

### ISSUE THREAD

**Issue by jjaritsch** [inex/IXP-Manager#579]
Hi,

on a fresh install of 5.2.0 (on a new Ubuntu 18.04 VM) we do have several issues with Error500 produced by the app itself.

First issue where caused by an file permission problem under /srv/ixpmanager/storage/framework/cache/data (many of the sub-dirs where owned by root:root instead of www-data:www-data). Using ./artisan cache:clear did not fix the issue - we got rid of this by: chown www-data: /srv/ixpmanager/storage/framework/cache/data -R

Second issue: Logged in as SuperUser => klick on User in the left menu => edit a User => klick on Plus to add a member to this user (or add this user to a member ...) => application Error500

PHP-Log doesn't show anything. After enabling debug mode in .env I do see the below details. 

Is this caused by some wrong config I applied to our installation?

thansk & best regards
Jürgen

Debug details: 

Too few arguments to function IXP\Http\Controllers\User\CustomerToUserController::add(), 0 passed and exactly 1 expected

(1/1) ArgumentCountErrorToo few arguments to function IXP\Http\Controllers\User\CustomerToUserController::add(), 0 passed and exactly 1 expected
--
in CustomerToUserController.php line 76
at CustomerToUserController->add()
at call_user_func_array(array(object(CustomerToUserController), 'add'), array())in Controller.php line 54
at Controller->callAction('add', array())in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(CustomerToUserController), 'add')in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 680
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ControllerEnabled.php line 96
at ControllerEnabled->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authenticate.php line 78
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 76
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 682
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 657
at Router->runRoute(object(Request), object(Route))in Router.php line 623
at Router->dispatchToRoute(object(Request))in Router.php line 612
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 62
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 85

**Comment by barryo** [comment]
Hi @jjaritsch 

thanks for this report. @yannrobin  has fixed the bug you found and pushed it to master and will be in the next release.

Regarding:

> First issue where caused by an file permission problem under /srv/ixpmanager/storage/framework/cache/data (many of the sub-dirs where owned by root:root instead of www-data:www-data). Using ./artisan cache:clear did not fix the issue - we got rid of this by: chown www-data: /srv/ixpmanager/storage/framework/cache/data -R

Yes, file permissions are an issue when people use root / non-web user. Both the [automatic installer](https://docs.ixpmanager.org/install/automated-script/) and the [manual instructions](https://docs.ixpmanager.org/install/manually/) set the permissions correctly on completion. 

In the [upgrade instructions](https://docs.ixpmanager.org/install/upgrading/), we have tried to encourage the operstor to use the correct user and have written the commands with this in mind. It's definitely something to be mindful of and we're working on operational notes to include this also.
