### ISSUE TITLE
Additions to default bogons/martians list

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#589]
Just updating our documentation, and IXP Manager default BIRD2 template does not include 100.64.0.0/10 (RFC 6598) and 192.88.99.0/24 (RFC 3068)

As suggested by various other bogon lists e.g. https://tools.ietf.org/html/rfc5735 
and: https://bgpfilterguide.nlnog.net/guides/bogon_prefixes/

Just for sake of completeness - and assuming it doesn't break anything, is it worth adding these, and also putting a comment next to each one describing what they are?

**Comment by barryo** [comment]
Hey @listerr 

Answer: yes and no 😉 

Absolutely for 100.64.0.0/10 (RFC 6598) and it was just an omision on our part.

RFC 3068 allows for this to be signalled via eBGP (section 4.3). As an example, it is advertised by AS-HURRICANE and part of their IRRDB entries. It is a bit of a mess:

http://irrexplorer.nlnog.net/search/192.88.99.0/24

but it doesn't belong on a bogon list. It would have to be handled by standard route server filtering policies and for IXP Manager that means: no ROA so RPKI unknown, fall back to IRRDB.

I'll keep this open until I add 100.64.0.0/10.

**Comment by barryo** [comment]
@listerr - this is now complete and added as part of an overall review in 282fe109e48a90e94211c51a88a2d43f44458c35
