### ISSUE TITLE
FR: "Return to customer" link from "Vlan Interface / Configured MAC Address Management" view

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#591]
**Describe the solution you'd like**
A link, similar to "Return to customer overview" @ "(Virtual) Interfaces / Add/Edit Virtual Interface", to get back to the previous page / cust overview when you're done editing MAC addresses for a Vlan Interface at https://<host>/layer2-address/vlan-interface/<n>

**Comment by barryo** [comment]
![Screenshot 2021-09-17 at 14 48 59](https://user-images.githubusercontent.com/804649/133793734-7d1e37f5-c1e8-4604-845c-9b731ad790aa.png)

This has always been there but I agree it's not obvious. Will review on the next UI/UX pass.
