### ISSUE TITLE
Broken grapher stats for ixp id=1 when all switches are down in one infrastructure

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#598]
##### ISSUE TYPE

Bug Report

##### OS

Ubuntu 18.04.3 LTS

##### VERSION

```
define( 'APPLICATION_VERSION', '5.2.0' );
define( 'APPLICATION_VERDATE', '2019093000' );

```

##### SUMMARY

At STHIX we have 4 infrastructures. At the moment our management connection to the newest infrastructure is down due to a transport issue so all of our switches in that infrastructure are down. This has the effect that MRTG can't produce any new data for that specific infrastructure and that also has the effect that the aggregated graph for all IXPs ( => grapher/ixp?id=1&type=json) does not show any updated data. The data shown is from the time when we lost the management connection to one of the infras.

Not sure if this is fixable but thought I'd report it anyway.

##### STEPS TO REPRODUCE

Disable management connection to all switches in one infrastructure. (followed by MRTG config update?)

##### IMPORTANCE
Low

##### Graphs

![grapher-mrtg-bits-day-all](https://user-images.githubusercontent.com/4455235/71194826-f63a4080-228c-11ea-960f-2cd8979a6a44.png)

**Comment by nickhilliard** [comment]
yeah, we're aware of this.  It's an MRTG problem rather than an IXP Manager problem, so it's not fixable by us unfortunately.
