### ISSUE TITLE
Mark patch panels as unavailable or closed for new cables

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#609]
**Is your feature request related to a problem? Please describe.**
We need to be able to have existing patch panels documented in IXP Manager, however, also a way to prevent new cable assignments to them.

This can be for a number of reasons e.g. we're running down the old patch panel and all new connections go on new panels, or the installation is not yet completed, or the panel is not for customer cables, or there is some problem with the panel which means the remaining ports can't be used (the d/c has no spare capacity at the ODF the panel runs to, the connectors are not the type used for new installs etc.)

**Describe the solution you'd like**
Flag in the Patch Panel properties to mark the patch panel as "closed" for new cable assignments.

Prevent new assignments and/or a warning message when a new assignment is created if the panel is closed.

**Comment by barryo** [comment]
Hey @listerr  - we run down patch panels too and we mark the port as either *reserved* or *other* (or leave as *prewired* if it is in fact wired to a port) and then add to the description:

> Mothballing this patch panel - do not use

It's the description that conveys the meaning to us.

I can see why you're suggesting *Closed* but honestly Rob, if you [look at the code for patch panels it's already too complex](https://github.com/inex/IXP-Manager/blob/master/app/Http/Controllers/PatchPanel/PatchPanelPortController.php) with the options we do have and I'm breaking out in hives here at the thoughts of adding more 😢  This can be handled in a number of other ways so the cost/benefit of adding more complication doesn't work for you here. Sorry.

**Comment by listerr** [comment]
Hi Barry,

I can't see where description is used in the patch panels pages? Only a notes field.
(I think something was there, but it doesn't show up anywhere else useful, like when you edit the patch panel ports.)

I notice that the patch panels list has a "Show Active / Show Inactive" filter which is possibly useful, but I don't see a way to mark patch panels as Active / Inactive.

We're up to 71 patch panels now, so something that can help quickly identify panels that should/should not be used would be helpful. I'll do a bit of a db update that marks the ports on panels to not use as "Other" as they then don't show up as green / available in the summary list.

It's also a cost/benefit of the consequences of a cable being ordered to an incorrect location or a wrong connector type which then causes delays and/or cost to rectify. We've had more than a few "whoopsie - didn't know this cable shouldn't have gone in to that location/connector type" which is a hassle to sort out.

I considered also changing the panel names to something like "DONOTUSE...." to make it double obvious but then I think this shows up in the customer crossconnect view, so that might look a bit strange.
