### ISSUE TITLE
Honor PeeringDB 'info_never_via_route_servers' flag

### ISSUE THREAD

**Issue by job** [inex/IXP-Manager#610]
Recently PeeringDB was extended to have a special informational flag `info_never_via_route_servers` that network operators can toggle to indicate that any route announcements containing their ASN anywhere in the `AS_PATH` are not expected to propagated via route servers. This can be implemented by rejecting routes, both by route server operators and on the Ingress EBGP policy attachment point in ISP's routing policies.

PeeringDB feature description: https://github.com/peeringdb/peeringdb#394

Example of an ASN that marked itself as 'never via route servers' https://www.peeringdb.com/api/net?asn=2914

All ASNs that marked themselves as `info_never_via_route_servers = True` can perhaps automatically be added to the `TRANSIT_ANS` data structure https://github.com/inex/IXP-Manager/blob/7cd28f8a331ddee38c1e568056121b481890ddc2/resources/views/api/v4/router/server/bird2/filter-transit-networks.foil.php#L14-L30

I believe this feature to be beneficial to the internet community at large, it can help prevent some potentially contentious discussions about who should or shouldn't be on the `TRANSIT_ASNS` list.

**Comment by barryo** [comment]
Thanks @job - we'll have a look.

**Comment by barryo** [comment]
Just having a quick look:

https://www.peeringdb.com/api/net?info_never_via_route_servers=1

So ~7 results - how new is this feature and any idea when it may have some parity with your @job original list that you quoted in the issue above?

**Comment by job** [comment]
This feature is roughly two weeks old.

I am not sure when it will have parity - or if it ever will have full parity, for now I'd recommend that the 'original list' is and the `info_never_via_route_servers=1` data are treated as a union set. "original list" U "peeringdb never_via_rs"

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues.

Where appropriate, will:

* Relocate to the IDEAS file.
* Add additional information below.
* No relocation / additional information for uber-stale issues.

*Additional information: this has been relocated to IDEAs. NB: Ideas is not where things go to die (check the history of the file). It's where I house keep things that have no short term prospects of implementation. We have plans for OpenBGPd support, etc and all this requires big revisions to how we generate route server configs in IXP Manager. We'll include this in that process.*
