### ISSUE TITLE
HTTP 500 error on Switch -> View/Edit Ports

### ISSUE THREAD

**Issue by barryo** [inex/IXP-Manager#614]
From the mailing list: 

> We are trying to add our Arista switches to the IXP Manager system, but
> we are facing issues when trying to add them via SNMP. I tried a
> snmpwalk -v 2c from the console of the IXP Manager server and it works,
> and when I add the switch manually, it looks like it kind of works
> because it recognizes the OS version. That being said, when I click on
> the SNMP actions (in the switch) and select "view / edit ports", the
> system redirects me to an error 500, and nothing happens.

* Here is the log https://pastebin.ibn.ie/?8ea5132fb985c614#FhTJPkqVcwQh8avtR4osdgt1mWHjDJqvZGto2cio3wkH
* Here is a 20-second video showing the issue: https://www.youtube.com/watch?v=FqGqbiduoEc&feature=youtu.be

**Comment by dorkmatt** [comment]
We (@sfmix) also see this v5.2.0 against Arista 4.23.2F. Oddly, 2 of our 5 switches work fine with the "edit/view" page, while the others error 500 for this page - but still end up fetching the individual interfaces.

**Comment by barryo** [comment]
Hi @dorkmatt  - this was fixed in [v5.3.0](https://github.com/inex/IXP-Manager/releases/tag/v5.3.0) along with some other related issues. If upgrading, note that we recently released [v5.4.1](https://github.com/inex/IXP-Manager/releases/tag/v5.4.1).

**Comment by dorkmatt** [comment]
Hey @barryo seems to be fixed in 5.4.1 - thanks. Of note when following the upgrade instructions (refresh caches, check permissions, etc) our install still shows 5.4.0 - is that normal?

**Comment by barryo** [comment]
Opps, I just updated the release notes with:

**Boo-boo Update:** I (@barryo) tagged v5.4.1 before updating the `version.php` file so after upgrading you'll still see `v.5.4.0` in the footer. 

Sorry 😢
