### ISSUE TITLE
Logo alignment in public member details page

### ISSUE THREAD

**Issue by barryo** [inex/IXP-Manager#616]
Looks like there is a CSS issue in different window width break points - e.g. at time of issue report on https://www.inex.ie/ixp/customer/detail/181 -

Small:

![Screenshot 2020-02-07 at 14 25 04](https://user-images.githubusercontent.com/804649/74037624-89067a00-49b6-11ea-9f12-bf80cd0b5c00.png)

Medium:

![Screenshot 2020-02-07 at 14 25 15](https://user-images.githubusercontent.com/804649/74037628-8e63c480-49b6-11ea-8e45-95fac60ff916.png)

Large:

![Screenshot 2020-02-07 at 14 25 23](https://user-images.githubusercontent.com/804649/74037635-9459a580-49b6-11ea-9fed-de8a29282be0.png)

X-Large:

![Screenshot 2020-02-07 at 14 25 32](https://user-images.githubusercontent.com/804649/74037649-99b6f000-49b6-11ea-9697-578e90feb6a6.png)

**Comment by listerr** [comment]
I noticed similar in the admin pages. Some members seem to upload a logo (which is too big?? and it doesn't line up correctly, but making the window wider doesn't change the position.

![image](https://user-images.githubusercontent.com/3037635/74071227-31d6c880-49fb-11ea-8739-a8c80575d227.png)
