### ISSUE TITLE
systemd configuration for MRTG

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#627]
You asked for a systemd configuration for MRTG, so here it is. I am using it on a Debian 10 system, but probably Ubuntu will be identical.

```
# disable the default cron job by renaming the default configuration
root@server1:~# mv /etc/mrtg.cfg /etc/mrtg.cfg.dpkg-dist

root@server1:~# cat /etc/systemd/system/mrtg.service 
[Unit]
Description=Multi-router Traffic Grapher
After=syslog.target

[Service]
User=mrtg
#Environment=RRDCACHED_ADDRESS=unix:/run/rrdcached/rrdcached.sock
Environment=LANG=C
ExecStart=/usr/bin/mrtg --daemon /var/lib/mrtg/ixpmanager.cfg --logging /var/log/mrtg/mrtg.log --pid-file=/run/mrtg/mrtg.pid --lock-file /var/lock/mrtg/mrtg_l --confcache-file /var/lib/mrtg/mrtg.ok
Type=forking
SuccessExitStatus=0 1
RuntimeDirectory=mrtg
PIDFile=/run/mrtg/mrtg.pid
StandardOutput=syslog

[Install]
WantedBy=multi-user.target
root@server1:~# systemctl start mrtg
root@server1:~# systemctl enable mrtg
root@server1:~# 
```

```
root@manager:~# grep mrtg /etc/cron.d/ixpmanager 
19 */4  * * *   root            update-mrtg
root@manager:~# cat /usr/local/sbin/update-mrtg
#!/bin/sh -e

export LANG=C

MRTG_CFG=/var/lib/mrtg/ixpmanager.cfg

APPLICATION_PATH=/srv/ixpmanager

# Synchronise configuration files
${APPLICATION_PATH}/artisan grapher:generate-configuration -B mrtg -O $MRTG_CFG.NEW

cat $MRTG_CFG     | egrep -v '^#' | egrep -v '^[ ]+Based on configuration last generated by' >$MRTG_CFG.OLD.filtered
cat $MRTG_CFG.NEW | egrep -v '^#' | egrep -v '^[ ]+Based on configuration last generated by' >$MRTG_CFG.NEW.filtered
DIFF=
diff $MRTG_CFG.OLD.filtered $MRTG_CFG.NEW.filtered >/dev/null || DIFF=$?

rm $MRTG_CFG.OLD.filtered $MRTG_CFG.NEW.filtered

if [ -z "$DIFF" ]; then
    rm $MRTG_CFG.NEW
    exit 0
fi

if ! mrtg --check $MRTG_CFG.NEW; then
  echo "mrtg --check $MRTG_CFG.NEW has failed!" >&2
  echo 1
fi

mv $MRTG_CFG.NEW $MRTG_CFG

systemctl --quiet reload-or-restart mrtg

root@manager:~#
```

And now something fancier: I run the mrtg poller in a different container from ixp-manager, and they share /var/lib/mrtg/. If you want to do the same then comment the systemctl line in the previous script and install these systemd units in the container running mrtg:

```
root@server1:~# cat /etc/systemd/system/mrtg-cfg.service 
[Unit]
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/systemctl reload-or-restart mrtg.service

[Install]
WantedBy=multi-user.target
root@server1:~#  cat /etc/systemd/system/mrtg-cfg.path 
[Path]
PathChanged=/var/lib/mrtg/ixpmanager.cfg

[Install]
WantedBy=multi-user.target
root@server1:~# systemctl start mrtg-cfg.path
root@server1:~# systemctl enable mrtg-cfg.path
root@server1:~#
```

**Comment by barryo** [comment]
@rfc1036  - Marco, I've added a link to this into the official documentation.

To add this systemd script to the codebase, we'd need you to sign the CLA - see [this document](https://github.com/inex/IXP-Manager/blob/master/CONTRIBUTING.md). If you do decide to do this, can you let us know which keyserver you are registered with? Thanks, Barry

**Comment by pashdown** [comment]
Found that the above systemd file refused to go because of /run restrictions and permissions on other directories that may or may not exist.  I modified to ignore PID file creation, because systemd doesn't really need that, and create the needed directories with the required permissions.  Use if you wish.

```
[Unit]
Description=Multi-router Traffic Grapher
After=syslog.target

[Service]
User=mrtg
Environment=LANG=C
ExecStart=/usr/bin/mrtg --daemon /var/lib/mrtg/ixpmanager.cfg --logging /var/log/mrtg/mrtg.log --lock-file /var/lock/mrtg/mrtg_l --confcache
-file /var/lib/mrtg/mrtg.ok
RuntimeDirectory=mrtg
Type=forking
SuccessExitStatus=0 1
StandardOutput=syslog
ExecStartPre=-/bin/mkdir -p /var/lock/mrtg
ExecStartPre=-/bin/mkdir -p /var/log/mrtg
ExecStartPre=/bin/chown mrtg.mrtg /var/lock/mrtg
ExecStartPre=/bin/chown mrtg.mrtg /var/log/mrtg
ExecStartPre=/bin/chown mrtg.mrtg /var/lib/mrtg

[Install]
WantedBy=multi-user.target
```

**Comment by rfc1036** [comment]
This is terrible. If you want systemd to create the directories (do you really have stateless systems shipped with an empty /var/?) instead of creating them at install time then you should use instead something like this instead:

```
LogsDirectory=mrtg
StateDirectory=mrtg
```

And just use /var/lib/mrtg/ for the lock file (/var/lock/ is actually supposed to be more about serial devices and nothing will clean up after you in there).

**Comment by pashdown** [comment]
The /var directory exists, yes.  Your specified  /var/log/mrtg, /run/mrtg/, and /var/lock/mrtg do not on a Ubuntu 20.04 mrtg install, this is why your systemd service file fails as-is after reboot.

**Comment by rfc1036** [comment]
```
root@manager:~# dpkg -S /var/lib/mrtg /var/log/mrtg
mrtg: /var/lib/mrtg
mrtg: /var/log/mrtg
```

/run/mrtg/ is created by systemd and /var/lock/mrtg/ indeed should not be used.

**Comment by pashdown** [comment]
>  /var/lock/mrtg/ indeed should not be used.

How can we contact the author of the original systemd service file to let them know?
