### ISSUE TITLE
Upgrade from v5.3.0 to v5.4.0 not working for us. 

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#631]
Hi,

we currently trying to upgrade our manager version from version 5.3.0 to 5.4.0. Unfortunately the manager doesn't work anymore after the upgrade

In the laravel.log I can see the following:

```[2020-04-08 23:03:37] production.ERROR: content is not defined. {"exception":"[object] (RuntimeException(code: 0): content is not defined. at /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php:343)
[stacktrace]
#0 /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php(365): Foil\\Extensions\\Helpers->getIn(Array, Array, true)
#1 /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php(240): Foil\\Extensions\\Helpers->get('content')
#2 /srv/ixpmanager/vendor/foil/foil/src/Extensions/Helpers.php(121): Foil\\Extensions\\Helpers->raw('content', '', NULL)
[...]
```
Can you help us here please?
Thanks!

//
Ubuntu 18.04 LTS
Apache2 + PHP 7.3

**Comment by barryo** [comment]
Hi @netfreak98 

The mailing list is the ideal place for installation / upgrade issues.

Please clear the log file, try again and then post the entire log (error and stack) tp https://pastebin.ibn.ie/ 

Thanks.
