### ISSUE TITLE
Option to create new patch panel ports as duplex pairs by default

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#632]
**Is your feature request related to a problem? Please describe.**

Since 99% of all our connections are duplex pairs, when adding new patch panels, I set them all up as duplex by default. This eliminates confusion. People less familiar with the patch panels page were selecting the wrong thing and mixing up pairs/ports, so we had to correct all these errors, then set every unused port on every panel to be duplex. This makes it easier to assign and work with them in pairs.

**Describe the solution you'd like**

Option when creating a new patch panel, to automatically set all the new ports as duplex by default.

**Describe alternatives you've considered**

I already wrote a script to update the duplex pairs in the database, because duplex ports are the norm 99% of the time, we only have a handful of simplex ports. 

When I set up new panels, I now set them all as duplex pairs by default. 

I rapidly got bored of clicking every port on every new panel to set them in duplex pairs, and I was making mistakes, so I worked out how to update the table directly, which was a relatively simple calculation + table update.

This is possibly a useful feature to have in the IXP Manager interface, however.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: the patch panel code is complex and we'll do a thorough review of the feature set at /some point/ in the future and consider UX/UI elements like this then.*
