### ISSUE TITLE
FR: Summarized graphs per facility

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#635]
**Is your feature request related to a problem? Please describe.**
We currently use an in-house script to build graphs from another source than IXP Manager and would, of course, prefer to use IXP Manager as the source (and get rid of the other system) to limit the amount of SNMP polling (and systems) to the switches. In our system (https://www.sthix.net/stats/switches-day.php) we organize the graphs per PoP in one phase/step, and that is not currently possible via the grapher API as I understand it(?). The closest thing I can get is per switch, but it becomes a bit tricky (impossible?) to merge multiple switches to get the graphs (RRD file, etc.) as you cannot output the raw RRD data per switch via the API as I understand it (to be able to merge it).

**Describe the solution you'd like**
An addition to MRTG's infras/ixp/members/switches called "facilities" or similar that merges all customer traffic on the switches within each facility.

**Describe alternatives you've considered**
It should not be very hard to add this to the MRTG configuration, but it might be somewhat tricky to generate a backlog/history of data, which would be preferable but isn't a deal breaker.

**Comment by nickhilliard** [comment]
are you talking here about:

- an aggregate graph of all ingress + egress ixp participant traffic in a cluster of switches
- the aggregate graph of traffic to/from that cluster of switches to the rest of the network
- the aggregate graph of all switch traffic in the cluster of switches

**Comment by rasssta** [comment]
* an aggregate graph of all ingress + egress ixp participant traffic in a cluster of switches

**Comment by barryo** [comment]
> an aggregate graph of all ingress + egress ixp participant traffic in a cluster of switches

For the avoidance of doubt - what's being coded is the aggregate of all traffic originating and / or terminating in a cluster of switches in a PoP *but not simply passing through that PoP*. I.e. core ports are excluded.

**Comment by barryo** [comment]
Completed via b54df92c55156641b92213cc618ac7337d895260, d646bc73525d527e84f3c67ce75742781115da94, d74c1dc3405e1065c9eae55e86d15e1277c2c7b3 and documented via inex/ixp-manager-docs-md@cb441cac38947866c28da41291f0752199510d9d

**Comment by barryo** [comment]
also:

> but it might be somewhat tricky to generate a backlog/history of data, which would be preferable but isn't a deal breaker

yeah, this is neither done nor necessary really. it'll build up.
