### ISSUE TITLE
Reset sort order in patch panel ports view

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#639]
##### ISSUE TYPE

Bug Report

##### SUMMARY
I accidentally clicked on a sort column in the patch panel ports view, and can't see a way to "remove" this sort as it was before.

##### STEPS TO REPRODUCE
Open a patch panel view
Sort by something. Now it must be sorted on one of the columns, but can't be unset as it was before.

The default before sorting was right, sorting by ports, now I have to select between a variety of weird sort orders. Presumably there's some cookie which set this that can be cleared?

Oddly, refreshing an empty panel seems to do the right thing and sort it back again, but I think this might not be sorting correctly where we have a mix of duplex + simplex ports on the panel?

##### RELEVANT LOGS

Screen cast showing problem here: https://www.youtube.com/watch?v=XUlkbuAzyV8

**Comment by barryo** [comment]
@yannrobin  - it's probably sorting on a hidden column like ID? probably best to have the Name column sort by that hidden data rather than itself. I think this would work better is most circumstances. Also, no need for sorting option on the actions column.

**Comment by barryo** [comment]
Fixed via 22aaf61a87565d0ddef9161c4ca2bc86ac8e5040
