### ISSUE TITLE
Customers of type 'routeserver' are displayed as "UNKNOWN MEMBER TYPE"

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#646]
In current v5.5.0 master when a 'customer' is set to  type=routeserver, the customer is falsely displayed as "UNKNOWN MEMBER TYPE" in  or "UNKNOWN CUSTOMER STATUS" within the customers overview (/customer/list) or detail (/customer/overview/n) views.

This customer type is basically used for internal routeserver infrastructure.

**Comment by barryo** [comment]
Closing via 22d574ebee2f0e6784b704e02208f0967358a898
