### ISSUE TITLE
Customer Notes - 'Watch' button

### ISSUE THREAD

**Issue by barryo** [inex/IXP-Manager#655]
The buttons to watch all notes for a member or to watch a specific note do not seem to work:

![Screenshot 2020-06-20 at 16 25 18](https://user-images.githubusercontent.com/804649/85205921-5ed6a880-b316-11ea-9d2f-dc2f4dabfe6d.png)

When clicked, there is no visual indication to indicate it it is 'on' or 'off' and it's not clear it actually works.

Could you also make the note title clickable and have it work in the same way as the 'view note' icon.

Lastly, in an admin users profile page, none of the three note watching options are selected by default. There needs to be a default setting and this needs to be indicated (even if just by default without a user pref) on the profile page.

Thanks,
Barry

**Comment by yannrobin** [comment]
This has been fixed in the V6
