### ISSUE TITLE
FR: Distinguish between IPv4/IPv6 for Max Prefixes in Members>Customer and Members>Customers>Ports

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#657]
It should be possible to specify max-prefix-limit for IPv4 and IPv6 independently. PR incoming.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: this is very much on the development plan and a ticket is not required to support that.*
