### ISSUE TITLE
FR: Peering Manager - honor rejected/ignored peers in bird/bird2 route server configs

### ISSUE THREAD

**Issue by schadom** [inex/IXP-Manager#659]
If a customer chooses to reject/ignore a peer, a discard import- and export-filter should be added to the routeserver config for both of the affected networks. This will be a step towards some kind of selective peering functionality within IXP manager where a customer could be able to selectively choose his desired peers via the RS or apply a global policy (like peer with all RS peers / reject all RS-peers except x,y,z).

**Comment by schadom** [comment]
In the future we could add an environment-option to set the default preference for new RS-peers - like for example: `IXP_PEER_DEFAULT="peer_with_everyone"` or `IXP_PEER_DEFAULT="reject_all_peers"`. The customer will then be able to control his RS-Peerings within IXP Manager. In my opinion we should also remove the current dependency on sflow.

**Comment by barryo** [comment]
Hi @schadom - we already have a UI complete in internal development for this. It's pending review and Bird configuration implementation.

We wouldn't do this via the peering manager but instead have a dedicated controller for. It will also support as path prepending.

Closing as already in progress. Thanks!

**Comment by schadom** [comment]
Hello @barryo, I'm wondering if there is any update on this FR or how we could help? Thanks in advance

**Comment by barryo** [comment]
We've got it about 90% done at this stage. Just need to complete the Bird config elements and then release. Should be able to get it out the door this month.

**Comment by schadom** [comment]
That's cool - thank you very much! If we can help with testing, please just ping me.
