### ISSUE TITLE
Filter available ports dropdown when provisioning

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#660]
**Is your feature request related to a problem? Please describe.**
When provisioning or assigning a new member port, a big dropdown of empty ports is shown when the switch is selected.

If using the patch panels feature however, the choice of which port to select in this dropdown might be "A prewired port" not "Any available port on the switch."

**Describe the solution you'd like**
An option in this page to limit the list of available ports in the Provisioning pages to only prewired ports on the selected switch, e.g. "[  ] Show prewired ports"

This would considerably speed up this process and make it easier for any staff to correctly select a prewired port without requiring a lot of knowledge where the prewired ports in a given site are, first having to rummage through the patch panels in a given site to find a port on a panel which is prewired to the appropriate switch, then determine the port it's prewired to, copy this port, then go back to the member provisioning page and paste this port here.  At present it's quite long-winded to do, assuming you have knowledge of the site and how to search through IXPM's patch panel ports to find a suitable port.

The only slight wrinkle in this is that some ports might be prewired to 1G and others to 10G or 100G ports. 

When I set up prewired ports, At the moment I put in the description in the patch panel port something like "VACANT 10G" or "VACANT 1G" to make it easier to select the correct port speed, so possibly displaying this text alongside the port would make that selection clearer, so when "[  ] Show prewired ports" filter is ticked, it lists only prewired ports that are not already allocated to a member, with the text beside it:

Ethernet1/2 (VACANT 10G)
Ethernet8/1 (VACANT 1G)
Ethernet51/1 (VACANT 100G)

But perhaps there could be a concept of "Compatible media/speed" tickboxes for a patch panel port so that only prewired ports of the correct type will appear. (Although this info might already be available from the switchports or physical interfaces tables?)

![image](https://user-images.githubusercontent.com/3037635/87532559-3fb80600-c68b-11ea-9118-73fc8261a5eb.png)

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues.

Where appropriate, will:

* Relocate to the IDEAS file.
* Add additional information below.
* No relocation / additional information for uber-stale issues.

*Additional information: this has been relocated to IDEAs. NB: Ideas is not where things go to die (check the history of the file). It's where I house keep things that have no short term prospects of implementation. On this one @listerr I completely get where you're coming from and I have two windows side by side (or tabs) to achieve the same thing. What you're suggesting would be a big improvement but it's a **big** task.*
