### ISSUE TITLE
Moving existing port doesn't update patch panel port record

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#661]
**Is your feature request related to a problem? Please describe.**
When a port is re-assigned to a new port (e.g. member is doing a hot-cut using the existing crossconnect from 10G to 100G)
and we move the port, the corresponding patch panel port info does not get updated.

**Describe the solution you'd like**
After updating a port, if it has a patch panel port associated, update this record.
Add a history entry or make a note that the port was changed in the patch panel records.

**Additional context**
Short screencast here: https://youtu.be/D5BjeV8X_xo

**Comment by barryo** [comment]
Hey @listerr - is it the data that's not updating? If so this is expected behavior from my view. The date represents the cross connect delivery and connection. A port move shouldn't change that in my view. We'd really need a different way to track port connections (which I would agree with).

**Comment by listerr** [comment]
If you move an existing port in the customer ports view (as in the screen cast), then this change is not reflected in the associated crossconnect, it still refers to the old port. It also gets a bit tangled if you then try to reallocate this crossconnect -> port to another customer as it does not show up as available.

**Comment by listerr** [comment]
We've done a few switch upgrades and again we have to go back after moving the ports to the new switch, to update the corresponding patch panel info. Can this be fixed as it's causing our PP records to get into a confused state. Thanks.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

Hey @listerr - pretty much the same comments as inex/IXP-Manager#632 here. The patch panel code is complex and we'll do a thorough review of the feature set at /some point/ in the future and consider UX/UI elements like this then.

For now I've recorded both of these in the IDEAS file so they will not be forgotten and considered when we have the time and resources to take a more thorough swing back at the patch panel functionality. Until then, like us, keeping these in sync needs to be part of your operational procedures.
