### ISSUE TITLE
Untagged dot1q interface can be configure with multi VLAN

### ISSUE THREAD

**Issue by mbruyere** [inex/IXP-Manager#668]
##### ISSUE TYPE

Configuration policy missing

##### OS
 
```
Ubuntu 20.04
```

##### VERSION

```
define( ‘APPLICATION_VERSION’, ‘5.6.0’ );
define( ‘APPLICATION_VERDATE’, ‘2020052300’ );
```

##### SUMMARY

When an Interface is dot1q untagged we should not be able to configure more than one VLAN/Subnet on this interface. 

and 

the API output should give a single VLAN too. Not like below 

    "layer2interfaces": [
        {
            "type": "edge",
            "description": "Beta",
            "dot1q": false,
            "virtualinterfaceid": 3,
            "lagframing": false,
            "vlans": [
                {
                    "number": 100,
                    "macaddresses": [
                        "00:00:00:00:00:03"
                    ],
                    "ipaddresses": {
                        "ipv4": "10.0.0.3",
                        "ipv6": "fd00::3"
                    }
                },
                {
                    "number": 300,
                    "macaddresses": [
                        "00:00:00:00:00:03"
                    ],
                    "ipaddresses": {
                        "ipv4": "10.0.2.1",
                        "ipv6": "2001:db8:2::1"
                    }
                }
            ],
            "shutdown": false,
            "status": "connected",
            "name": "port1.0.1",
            "speed": 1000,
            "autoneg": true
        }

##### EXPECTED RESULTS

If the box dot1q frame is not checked, we should be able to configure only one VLAN/IPs. 

##### IMPORTANCE

Medium

**Comment by barryo** [comment]
I skipped ahead of you @mbruyere and opened this as #667 and sorted it yesterday 👍
