### ISSUE TITLE
Custom LookingGlass Community definition

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#673]
Hi,

is it possible to modify the variables in the file "/srv/ixpmanager/resources/skins/kleyrex/app/Utils/Foil/Extensions/Bird.php" (Community values)?
It's not possible to do this via "/srv/ixpmanager/config/custom.php".

As note in the config I can see:
````
    // FIXME: need to find a place for this that allows end users to customise it
````

// Manager Version 5.7.0

Thank you! :)

Best regards,
Joey

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: we'll review this again as we build out configs to support OpenBGPd - when we do that we'll most likely centralise elements like this.*
