### ISSUE TITLE
sflow backend instead of mrtg

### ISSUE THREAD

**Issue by netfreak98** [inex/IXP-Manager#677]
Hi guys,

today we implemented the sflow P2P graphs. Really a nice feature. Are there any plans to implement manager wide sflow based graphs? In our setup we can not monitor all ports using SNMP (e.g. virtual interfaces or resold ports). In some cases there are also a lot of gaps in the graphes due to SNMP timeouts and stuff like that.

Thanks in advance!

Joey

**Comment by nickhilliard** [comment]
we don't plan to add this as a supported feature.

There are two sflow mechanisms: flow records and counter records.  At the moment, we use flow data to build the p2p graphs but would caution that if you add all these up, you won't necessarily end up with what the mrtg graphs show.  The sflow counter data would be more interesting, but there is no widely-used software which uses this information to populate TSDBs for graphing, and also it won't give you output in the situation where the traffic is not coming from a defined interface (physical or virtual).

Occasionally, we've compared the sflow aggregate to the mrtg aggregate to see how close they are.  Sometimes it's good (+/- 5%).  Other times not so good (large bumps all over the sflow data, rendering it mostly useless).  If the results were better, we'd be more enthusiastic about doing something here, but they're not generally.

The best option is to use switching kit which can deliver per-virtual-port stats, and to make sure that the equipment and the management network don't drop packets.

**Comment by netfreak98** [comment]
Thanks!

one last question if you allow. What do you mean by "switching kit"?

**Comment by nickhilliard** [comment]
"ethernet switches"
