### ISSUE TITLE
Error 500 when changing password

### ISSUE THREAD

**Issue by steiostb** [inex/IXP-Manager#679]
### ISSUE TYPE

Bug Report

##### OS

 Debian 4.19.98-1

##### VERSION

define( 'APPLICATION_VERSION', '5.7.0' );
define( 'APPLICATION_VERDATE', '2020082000' );
   
##### ENVIRONMENT 
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

ii  libapache2-mod-php7.3             7.3.19-1~deb10u1              amd64        server-side,                                                HTML-embedded scripting language (Apache 2 module)
ii  php-common                        2:69                          all          Common files                                                for PHP packages
ii  php-composer-ca-bundle            1.1.4-1                       all          utility libra                                               ry to find a path to the system CA bundle
ii  php-composer-semver               1.4.2-1                       all          utilities, ve                                               rsion constraint parsing and validation
ii  php-composer-spdx-licenses        1.5.0-1                       all          SPDX licenses                                                list and validation library
ii  php-composer-xdebug-handler       1.3.2-1                       all          Restarts a pr                                               ocess without xdebug
ii  php-ds                            1.2.6-2+b1                    amd64        PHP extension                                                providing efficient data structures for PHP 7
ii  php-gettext                       1.0.12-0.1                    all          transitional                                                dummy package for php-php-gettext
ii  php-igbinary                      3.0.0-1                       amd64        igbinary PHP                                                serializer
ii  php-json-schema                   5.2.8-1                       all          implementatio                                               n of JSON schema
ii  php-memcache                      3.0.9~20170802.e702b5f-2      amd64        memcache exte                                               nsion module for PHP
ii  php-memcached                     3.1.3+2.2.0-1                 amd64        memcached ext                                               ension module for PHP, uses libmemcached
ii  php-msgpack                       2.0.3-1                       amd64        PHP extension                                                for interfacing with MessagePack
ii  php-pear                          1:1.10.6+submodules+notgz-1.1 all          PEAR Base Sys                                               tem
ii  php-php-gettext                   1.0.12-0.1                    all          read gettext                                                MO files directly, without requiring anything other than PHP
ii  php-psr-log                       1.1.0-1                       all          common interf                                               ace for logging libraries
ii  php-rrd                           2.0.1+1.1.3-6                 amd64        PHP bindings                                                to rrd tool system
ii  php-snmp                          2:7.3+69                      all          SNMP module f                                               or PHP [default]
ii  php-symfony-console               3.4.22+dfsg-2+deb10u1         all          run tasks fro                                               m the command line
ii  php-symfony-debug                 3.4.22+dfsg-2+deb10u1         all          tools to make                                                debugging of PHP code easier
ii  php-symfony-filesystem            3.4.22+dfsg-2+deb10u1         all          basic filesys                                               tem utilities
ii  php-symfony-finder                3.4.22+dfsg-2+deb10u1         all          find files an                                               d directories
ii  php-symfony-process               3.4.22+dfsg-2+deb10u1         all          execute comma                                               nds in sub-processes
ii  php-yaml                          2.0.2+1.3.1-4                 amd64        YAML-1.1 pars                                               er and emitter for PHP
ii  php7.3                            7.3.19-1~deb10u1              all          server-side,                                                HTML-embedded scripting language (metapackage)
ii  php7.3-bcmath                     7.3.19-1~deb10u1              amd64        Bcmath module                                                for PHP
ii  php7.3-cgi                        7.3.19-1~deb10u1              amd64        server-side,                                                HTML-embedded scripting language (CGI binary)
ii  php7.3-cli                        7.3.19-1~deb10u1              amd64        command-line                                                interpreter for the PHP scripting language
ii  php7.3-common                     7.3.19-1~deb10u1              amd64        documentation                                               , examples and common module for PHP
ii  php7.3-curl                       7.3.19-1~deb10u1              amd64        CURL module f                                               or PHP
ii  php7.3-gd                         7.3.19-1~deb10u1              amd64        GD module for                                                PHP
ii  php7.3-intl                       7.3.19-1~deb10u1              amd64        International                                               isation module for PHP
ii  php7.3-json                       7.3.19-1~deb10u1              amd64        JSON module f                                               or PHP
ii  php7.3-mbstring                   7.3.19-1~deb10u1              amd64        MBSTRING modu                                               le for PHP
ii  php7.3-mysql                      7.3.19-1~deb10u1              amd64        MySQL module                                                for PHP
ii  php7.3-opcache                    7.3.19-1~deb10u1              amd64        Zend OpCache                                                module for PHP
ii  php7.3-readline                   7.3.19-1~deb10u1              amd64        readline modu                                               le for PHP
ii  php7.3-snmp                       7.3.19-1~deb10u1              amd64        SNMP module f                                               or PHP
ii  php7.3-xml                        7.3.19-1~deb10u1              amd64        DOM, SimpleXM                                               L, WDDX, XML, and XSL module for PHP
ii  php7.3-zip                        7.3.19-1~deb10u1              amd64        Zip module fo                                               r PHP

##### SUMMARY

According to this commit https://github.com/inex/IXP-Manager/commit/1b060d348ba432cda8c2ff9ab0093985e9bc7834, database/Repositories/User.php should contain the deleteActiveSession function, but this function in not included in the 5.7.0 release, among other lines in this commit.

##### STEPS TO REPRODUCE

Click on "My Account" -> "Profile" and type inn old and new password and click "Update password".

##### EXPECTED RESULTS

A page with "your password was changed"

##### ACTUAL RESULTS

A page with error 500.
[2020-10-29 11:27:29] production.ERROR: Undefined method 'deleteActiveSession'. The method name must start with either findBy, findOneBy or c                                       ountBy! {"userId":4,"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'deleteActiveSession'. The method name must star                                       t with either findBy, findOneBy or countBy! at /usr/local/ixp/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:235)
[stacktrace]
#0 /usr/local/ixp/app/Http/Controllers/ProfileController.php(127): Doctrine\\ORM\\EntityRepository->__call('deleteActiveSes...', Array)
#1 [internal function]: IXP\\Http\\Controllers\\ProfileController->updatePassword(Object(IXP\\Http\\Requests\\Profile\\Password))
#2 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('                                       updatePassword', Array)
#4 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(                                       Illuminate\\Routing\\Route), Object(IXP\\Http\\Controllers\\ProfileController), 'updatePassword')
#5 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#6 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#7 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{clos                                       ure}(Object(Illuminate\\Http\\Request))
#8 /usr/local/ixp/app/Http/Middleware/Google2FA.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\H                                       ttp\\Request))
#9 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): IXP\\Http\\Middleware\\Google2FA->handle(Object(Illumin                                       ate\\Http\\Request), Object(Closure))
#10 /usr/local/ixp/app/Http/Middleware/ControllerEnabled.php(96): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illu                                       minate\\Http\\Request))
#11 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): IXP\\Http\\Middleware\\ControllerEnabled->handle(Objec                                       t(Illuminate\\Http\\Request), Object(Closure))
#12 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Ill                                       uminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->h                                       andle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /usr/local/ixp/app/Http/Middleware/Authenticate.php(80): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminat                                       e\\Http\\Request))
#15 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): IXP\\Http\\Middleware\\Authenticate->handle(Object(Ill                                       uminate\\Http\\Request), Object(Closure))
#16 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline                                       ->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfTo                                       ken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Il                                       luminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->                                       handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminat                                       e\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(                                       Object(Illuminate\\Http\\Request), Object(Closure))
#22 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeli                                       ne->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResp                                       onse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illumina                                       te\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle                                       (Object(Illuminate\\Http\\Request), Object(Closure))
#26 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\                                       {closure}(Object(Illuminate\\Http\\Request))
#27 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(I                                       lluminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\                                       Http\\Request), Object(Illuminate\\Routing\\Route))
#30 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illum                                       inate\\Http\\Request))
#31 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illu                                       minate\\Http\\Request))
#32 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foun                                       dation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#33 /usr/local/ixp/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Il                                       luminate\\Http\\Request))
#34 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illumina                                       te\\Http\\Request), Object(Closure))
#35 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeli                                       ne->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRe                                       quest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeli                                       ne->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRe                                       quest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipelin                                       e->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePost                                       Size->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\                                       Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMain                                       tenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\                                       {closure}(Object(Illuminate\\Http\\Request))
#44 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closu                                       re))
#45 /usr/local/ixp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequest                                       ThroughRouter(Object(Illuminate\\Http\\Request))
#46 /usr/local/ixp/public/index.php(85): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}

**Comment by yannrobin** [comment]
This will be fixed in the new version of IXP manager.
