### ISSUE TITLE
Facility should restrict rack selection

### ISSUE THREAD

**Issue by pashdown** [inex/IXP-Manager#691]
##### ISSUE TYPE

Bug Report

##### VERSION

```
define( 'APPLICATION_VERSION', '5.7.0' );
define( 'APPLICATION_VERDATE', '2020082000' );
```

##### ENVIRONMENT 

```
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

##### CONFIGURATION

```
APP_DEBUG=false
APP_URL="http://198.60.22.101"
APP_TIMEZONE="UTC"
APP_LOG="single"
IXP_FE_FRONTEND_CUSTOMER_ONE=customer
IXP_FE_FRONTEND_CUSTOMER_MANY=customers
IXP_FE_FRONTEND_CUSTOMER_OWNER="customer's"
IXP_FE_FRONTEND_CUSTOMER_OWNERS="customers'"
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=false
IXP_FE_FRONTEND_DISABLED_LOGO=false
GRAPHER_BACKENDS="dummy"
GRAPHER_CACHE_ENABLED=true
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
CACHE_DRIVER=memcached
DOCTRINE_PROXY_AUTOGENERATE=false
DOCTRINE_CACHE=memcached
DOCTRINE_CACHE_NAMESPACE=IXPMANAGERNAMESPACE
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq3
```

##### SUMMARY

When setting up a switch, rack selection should fall under facility selection.  Instead I have to name the racks with a tag that indicates facility.
##### STEPS TO REPRODUCE
Go setup a switch.

##### EXPECTED RESULTS

Select facility and choose from racks inside that facility.
##### ACTUAL RESULTS

All the racks in all the facilities are shown.
##### IMPORTANCE

Minor annoyance.

**Comment by barryo** [comment]
@yannrobin - should be possible to do this on the page without ajax by including the location_id with the cabinets.

**Comment by barryo** [comment]
@yannrobin  - easiest is to just use an option group and list the racks by facility: https://select2.org/options
