### ISSUE TITLE
ifType selection in Switcher\snmpPollSwitchPorts() excludes useful ports

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#695]
##### ISSUE TYPE

Bug Report

##### VERSION

```
IXP Manager >= 5.0
```

##### SUMMARY

snmpPollSwitchPorts() restricts the type of port to ifType `ethernetCsmacd`, `l2vlan` and `l3ipvlan`, because most NOS's include various types of virtual port which are not relevant to IXP operation.  Sometimes, some vendors (e.g. Juniper) use a richer set of ports, and a wider selection of ifTypes.  If these ifTypes were enabled in the general case, IXP-M operators would be presented with lots of port types that were irrelevant to ixp service.

This is a traditional user interface situation: we need a balance between hiding the inherent complexity of what's going on, while enabling enough flexibility to allow the operator to do what they need, while ensuring that the underlying code base and config is maintainable as a long term proposition.

##### EXPECTED RESULTS

juniper irb interface and subinterfaces should appear.

##### ACTUAL RESULTS

juniper irb interface and subinterfaces don't appear.

##### Proposals for fix

couple of options here:

  - a flag per installation or per switch to disable the `ifType` check in `snmpPollSwitchPorts()`
  - a select list to allow additional ifTypes to be polled
  - other?

**Comment by barryo** [comment]
Other option chosen - documented here: https://docs.ixpmanager.org/usage/switches/#snmp-and-port-types-iftype

In 10+ years, this is a real corner case and this is the option that preserves the *balance [of] hiding the inherent complexity of what's going on*.
