### ISSUE TITLE
Reset password error 500

### ISSUE THREAD

**Issue by gizmo15** [inex/IXP-Manager#698]
Hi,

Via the webinterface, i add a new user, no problem i received the welcome mail but when i use the reset password link in the mail i have this message :
```
500
Server Error :: username is not defined.
```

The log from laravel.log :
```
[2021-03-05 09:04:00] production.NOTICE: gizmo Added a User  with ID 9  
[2021-03-05 09:04:27] production.ERROR: username is not defined. {"exception":"[object] (RuntimeException(code: 0): username is not defined. at /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Extensions/He
lpers.php:343)
[stacktrace]
#0 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Extensions/Helpers.php(365): Foil\\Extensions\\Helpers->getIn(Array, Array, true)
#1 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Extensions/Helpers.php(240): Foil\\Extensions\\Helpers->get('username')
#2 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Extensions/Helpers.php(121): Foil\\Extensions\\Helpers->raw('username', '', NULL)
#3 [internal function]: Foil\\Extensions\\Helpers->variable('username')
#4 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Kernel/Command.php(168): call_user_func_array(Array, Array)
#5 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Kernel/Command.php(195): Foil\\Kernel\\Command->execute('v', Array, Array)
#6 [internal function]: Foil\\Kernel\\Command->doRun('v', 'username')
#7 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Kernel/Command.php(181): call_user_func_array(Array, Array)
#8 [internal function]: Foil\\Kernel\\Command->doRunIsolated('v', 'username')
#9 /mnt/external/www/ixpmanager-git/vendor/foil/foil/src/Kernel/Command.php(104): call_user_func_array(Array, Array)
#10 [internal function]: Foil\\Kernel\\Command->run('v', 'username')
```

In the Username box i have this content :
`ht<!DOCTYPE html><ml lang=`

If i replace it with the username, i have an error 419. I set the timezone in the .env file and in php.ini-production but nothing change.

In the database, i see the user :
```
ixpmanager@localhost [ixpmanager]> select custid, name, username, password, email from user where name='btassou';
+--------+---------+----------+--------------------------------------------------------------+--------------------------------+
| custid | name    | username | password                                                     | email                          |
+--------+---------+----------+--------------------------------------------------------------+--------------------------------+
|      1 | btassou | btassou  | $2y$10$t0IBtN/zEwxbF9AIRJ.JAeWacrj9h1bjnsx5x3TAkrq/zSa95osAW | boris.tassou+test@securmail.fr |
+--------+---------+----------+--------------------------------------------------------------+--------------------------------+
1 row in set (0.00 sec)
```

My configuration :
FreeBSD 12.1
php74-7.4.15
php74-composer-1.10.20
php74-ctype-7.4.15
php74-curl-7.4.15
php74-dom-7.4.15
php74-fileinfo-7.4.15
php74-filter-7.4.15
php74-gd-7.4.15
php74-gettext-7.4.15
php74-gmp-7.4.15
php74-iconv-7.4.15
php74-intl-7.4.15
php74-json-7.4.15
php74-mbstring-7.4.15
php74-mysqli-7.4.15
php74-openssl-7.4.15
php74-pcntl-7.4.15
php74-pdo-7.4.15
php74-pdo_mysql-7.4.15
php74-pear-1.10.12
php74-pear-PHP_Parser-0.2.2
php74-phar-7.4.15
php74-posix-7.4.15
php74-session-7.4.15
php74-simplexml-7.4.15
php74-sockets-7.4.15
php74-tokenizer-7.4.15
php74-xml-7.4.15
php74-zlib-7.4.15
mysql80-client-8.0.23
mysql80-server-8.0.23

Thanks for the help!

**Comment by barryo** [comment]
Hi @gizmo15 - not sure what's happening for you with these. I could not / cannot reproduce either issue. My dev box is 7.4.15 also, the main difference being FreeBSD compiled packages 🤷‍♂️. It would probably be worthwhile comparing the php.ini you are using compared to the two stock versions:

https://github.com/php/php-src/blob/PHP-7.4.15/php.ini-development
https://github.com/php/php-src/blob/PHP-7.4.15/php.ini-production

 I think you truncated the logs above? Can you `tail -f` the log, recreate the issue and post all resultant logs to https://pastebin.ibn.ie/ and then the URL here please?

**Comment by gizmo15** [comment]
The full stacktrace : https://pastebin.ibn.ie/?a0163724c87a504a#C5VgW21fv65BQ9EdjayJ6X8KfD5UXWPCjC4Uxdfv5tvv
```

[root@ns /tmp]# diff php.ini-prod /usr/local/etc/php.ini-production 
388c388
< max_execution_time = 30
---
> max_execution_time = 600
962c962
< ;date.timezone =
---
> date.timezone = Europe/Paris
```

And no diff between php.ini-dev with the stock version and the one on my VM.

**Comment by barryo** [comment]
I was looking for templates in lines 15-20 but they've been truncated.

Can you share the URL / body of the email that you get in the reset email? Ideally as you get it (you can `TRUNCATE password_resets`).

**Comment by gizmo15** [comment]
The full content of the email :
https://pastebin.ibn.ie/?82a772fe5ed0c4cd#FDhqoSAuaaeGbMRyUg4hwmC6qsseUE5bcHA4KVPEnt9F

**Comment by barryo** [comment]
This looks like an email client issue:

Can you untangle this:

```
Reset password: https://manager.XXXXXXXXX/password=
/reset/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?use=
rname=3Dbtassou
```

so it looks like:

```
https://manager.XXXXXXXXX/password/reset/XXXX?username=btassou
```

**Comment by gizmo15** [comment]
if i copy/paste the url behind the button reset password, the url is look like what you write.

https://norishare.com/ZShUAKYK

**Comment by barryo** [comment]
Anything else unusual on your end - non-standard browser? 

If you want to forward the email as an attachment to barry.odonovan <at> inex <dot> ie I'll take a look. But I cannot reproduce and the error seems to indicate an issue with the email / browser.

**Comment by gizmo15** [comment]
i forward the reset email.

i tried with chromium without any modules/plugins in private session

**Comment by barryo** [comment]
Thanks @gizmo15 

The URL looks good as you say.

I'm not really sure where to take this from here. I don't have the time right now to spin up a FreeBSD box and test it myself. We are due to launch a new release with two weeks - a major update - but I can't say if that will work or not for you. 

If you want to shortcut the issue, use Ubuntu 18.04 with the installer script for now and see if the updated version in the next little while works?

**Comment by gizmo15** [comment]
i will try with the automated script.

If you want, i can provide you a FreeBSD VM.

**Comment by barryo** [comment]
I might take you up on that but I think only if the newer version doesn't work.

**Comment by gizmo15** [comment]
i build a VM with ubuntu 20.04 and your automated script, when i add a new user i have this message :
500
Server Error :: Expected response code 220 but got an empty response

https://pastebin.ibn.ie/?42cb45e02a17bcd6#7f7qzV6FfmB3c6oemTV9dgXDhWaKp6jYiVR2d1qHgbhb

```
root@ixpmanager:/srv/ixpmanager/storage/logs# git status
On branch release-v5
Your branch is up to date with 'origin/release-v5'.

nothing to commit, working tree clean
```

**Comment by barryo** [comment]
Looks like an email config issue => https://docs.ixpmanager.org/usage/email/

If you're testing, you can just set `MAIL_DRIVER=log`.

**Comment by gizmo15** [comment]
i install sendmail and it works! thanks ;)
