### ISSUE TITLE
Need a way to handle patch panel positions that end in a character

### ISSUE THREAD

**Issue by ninjaix** [inex/IXP-Manager#700]
We have one large American data center operator that uses letters at the end of the jack position.
Example 200-105A thru 200-105X
A work around would be to allow an import from a csv or tsv file.

**Comment by barryo** [comment]
No current plans to fix this @ninjaix - it's a corner case with too much complexity; as is the suggested solution. I'd suggest using an SQL editor to edit the ports manually.
