### ISSUE TITLE
Accessing to ixp management interface from remote machine on docker enviroment

### ISSUE THREAD

**Issue by leostereo** [inex/IXP-Manager#704]
Im running ixp manager on  remote docker enviroment.
When trying to connect to http://[server_ip]:8880 it redirects to http://localhost:8880/auth/login and of course it fails accessing.
At first I thought it was related to my browser but after trying on different clients it has same behaviour.
Is there some whay to avoid this redirection ? 
 btw , im trying following docker:
 [https://github.com/inex/ixp-manager-docker](url)
 Regards.

**Comment by barryo** [comment]
Duplicate of inex/ixp-manager-docker#1 - will follow up there.
