### ISSUE TITLE
[Feature Request] Support the full range of 4-octet AS numbers

### ISSUE THREAD

**Issue by nicholascw** [inex/IXP-Manager#705]
**Is your feature request related to a problem? Please describe.**
I understood that this issue is not affecting most other public IXPs, but currently in the default MySQL tables structure, `cust` table's `autsys` has a type of INT, which is indeed 4-octets, but signed in the MySQL, therefore allowing a maximum of `2147483647` instead of `4294967295` given by [RFC4893](https://tools.ietf.org/html/rfc4893).

**Describe the solution you'd like**
My simple workaround is change it into BIGINT type in MySQL.

**Additional context**
I was only trying to utilize IXP manager inside [dn42 network](https://dn42.eu).

**Comment by barryo** [comment]
Hi @nicholascw  - this was already fixed in v5.7 via inex/IXP-Manager#664 - you'll also find a quick fix there that you can implement pending an upgrade.
