### ISSUE TITLE
AS-SET-s stored in IXP manager visible/manageable by members

### ISSUE THREAD

**Issue by marioklobucar** [inex/IXP-Manager#708]
Hi

At this time, users cannot see their AS-SETs set up within the IXP manager.
Therefore, we are not able to invite users to periodically check the correctness of the information that is important for prefix filtering and let us know if there are any changes.
It would also be convenient to consider the possibility of members actually changing these values themselves.
In addition, in the administrator interface itself, there are different field labels when viewing (IPv4 AS-SET), or field editing (IPv4 Peering Macro).

Thanks in advance
Mario

**Comment by barryo** [comment]
@yannrobin - for now could you please add a section to the custuser/custadmin Details tab which contains:

*  Peering Policy 
*  IRRDB source
*  ASN 
*  IPv4 AS-SET 
*  IPv6 AS-SET 

[add to release-v5 and v6 please]
