### ISSUE TITLE
Document store require login for members-only folders

### ISSUE THREAD

**Issue by davidc** [inex/IXP-Manager#709]
**Is your feature request related to a problem? Please describe.**

The document store is a great place to store files for members. Of course it also allows public documents to be stored as well, so the whole section doesn't require login.

This leads to a suboptimal situation when the user is not logged in and they are linked to a folder full of member-only files. They are presented with a blank page with no indication of a problem and no login dialog.

For example we link directly to an AGM's folder to our members list, so they can access the relevant files. We always have to also say "(please login if the page appears blank)".

**Describe the solution you'd like**

I would suggest that if the user is not logged in, and the folder contains no files with public access, they are automatically redirected to the login dialog (and after logging in are redirected back to the folder).

Note that there is currently also an information leak when not logged in - you can see the title of the folder if you can guess its (sequential) ID, even if you don't have access to anything in it. This would automatically be fixed by the above solution of redirecting to the login page if there are no public files in that folder.

Finally, in order to prevent a further information leak as to whether a folder even exists at all, I would suggest that if a not-logged-in user attempts to access a folder that doesn't even exist (/docstore/9999), they follow the same logic to be redirected to the login page. (This is admittedly a minor vulnerability, since if the title-display vulnerability is fixed, all they can learn from this method is how many folders exist).

**Describe alternatives you've considered**

Following earlier confusion from members, we now always say "please login if the page appears blank", however it feels a bit unprofessional that it is not done automatically.

**Additional context**

This is not an issue for us, but there might also be a situation where a folder contains both public and private files. In that case, it might be useful for the user to know that more files could be seen if they were to login. However that in itself would disclose that more files exist.

**Comment by barryo** [comment]
The headache here is that if the structure is parent A -> child B -> child C and C contains a file that is public but A and B don't then it's hard to get to C without a direct link.

The idea in this case was that the structure would be visible and that's a user decision to lay it out like that.

However, the system is not working as documented:

> Note that you do not need to set any permissions on directories - directories (and directory hierarchy) will only be visible to each user class if they contain files that the specific user class should be able to see.

@yannrobin:

1. if a user tries to access a folder that does not exist, it throws a 404. This should remain as is. This is not a redirect to login situation. The data exposure through enumeration is just that a folder may or may not exist.
2. if a user tries to access a folder / hierarchy that has nothing for them, please:
   * redirect to login via 401 (if not logged in)
   * throw a general 401 if logged in but permissions not sufficient


[apply to release-v5 and v6 please]

**Comment by yannrobin** [comment]
Should be fixed, might need some more tests to be sure that this behave as expected.

**Comment by davidc** [comment]
Hi, we have installed 5.8.0 for testing.

This is redirecting to the login page but doesn't take them to the requested folder after login. Can this be fixed otherwise this is a bad experience where the user then has to hit back until they reach the page that linked them and click the link again.
