### ISSUE TITLE
Have a "private" directory analogous to the "public" one,with files only loadable by logged in users

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#71]
At the moment files (e.g. images) placed in the `[IXPM_URL]/public` directory for use by IXP-Manager are also publicly (not-logged-in) accessible by URL. It would be good to have an analogous `[IXPM_URL]/private` directory which would be a clearly understood place where IXP-Manager can load images, etc from for a _logged in_ user only (checks login cookie/session). I guess something similar could be achieved by the far more complex method of "wrapping" content inside files with smarty logic in the views directory, but I believe as a simple (and easy-to-understand) option for "non-publicly-viewable" stuff this would also be useful. Example use-case: image files for embedding in documentation pages suitable for logged in users, but not for public browsing...

**Comment by barryo** [comment]
Implemented in [v5.4.0](https://github.com/inex/IXP-Manager/releases/tag/v5.4.0).
