### ISSUE TITLE
Generate LOAs for switches

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#719]
**Is your feature request related to a problem? Please describe.**

In some of our POPs cross-connects are directly connected to the peering switches, but IXP Manager supports creating LOAs only for patch panels.

**Describe the solution you'd like**

I wish that IXP Manager could create LOAs not only for patch panels but also for switches.

**Describe alternatives you've considered**

Somehow defining fake patch panels corresponding to switches? But then a lot of time would be spent synchronizing the status of the patch panel with the status of the switch, and it would be hard to show the real names of the switch ports.

**Comment by barryo** [comment]
Hi @rfc1036 - this came up recently on the mailing lists also. 

The alternative you alluded to above was also the suggestion made there: 

> There won't be functionality to generate LoAs to switch ports but, as 
> you identified above, you can make that work by creating a patch panel 
> to represent your switch.

Patch panels and ports is one of the more complex pieces of code in IXP Manager and we could not shoe-horn switches in there as it would be a complete mess. Facilitating this would really require a rewrite of that feature - which may happen as we learn more from how it is used - but it's something we're planning anytime soon, sorry.
