### ISSUE TITLE
Add support for granular disclosure of exchange infrastructure via the IX-F Member Export Schema

### ISSUE THREAD

**Issue by leovegoda** [inex/IXP-Manager#722]
This feature request is being created for the purposes of documentation for code under development already.

While some exchanges are willing to share detailed information about their infrastructure via the IX-F Member Export Schema, others either do not want to or cannot due to regulation. Enabling exchanges to share a limited set of data about their infrastructure would help exchanges find others using the same platforms to learn from each other and shows the diversity of platforms in use across the market.

Giving exchanges granular control over what is shared should result in more information being shared overall, as exchanges that would have decided against sharing detailed information opt to share details about equipment vendors and product lines. Adding granular controls over what to share should lead to exchange operators making a conscious decision and this could help them improve their security stance.

**Comment by barryo** [comment]
In progress with @yannrobin

**Comment by barryo** [comment]
Implemented in 3cba6f613faf960481a932e9608b45fbe9367746 and b71113bc0f52beeb0f5c4d554cf32b1d089413c4. 

Will be released with v6.0.1 sometime this week.

Documented here: https://docs.ixpmanager.org/features/ixf-export/#excluding-some-data
