### ISSUE TITLE
Moving simplex patch panel ports doesn't work

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#743]
##### ISSUE TYPE

Bug Report

##### VERSION
```
define( 'APPLICATION_VERSION', '6.1.0' );
define( 'APPLICATION_VERDATE', '2021091500' );
```

##### SUMMARY
Trying to move a simplex patch panel port from one to another fails.

I've tried a few different ports and same result. Interestingly, duplex ports seem to move okay.

Submititing without making a selection results in error: 

`Server Error :: Call to a member function isDuplexPort() on null`

##### STEPS TO REPRODUCE

See screencast: [YouTube](https://www.youtube.com/watch?v=FE_WrxBdZ4k)

**Comment by barryo** [comment]
Thanks @listerr  - fixed above.
