### ISSUE TITLE
Undefined array key protocol when install from latest ubuntu 20.04

### ISSUE THREAD

**Issue by faisalr3za** [inex/IXP-Manager#747]
#################################################################

Installing PHP, Apache, MySQL, etc. Please be very patient...[done]
Cloning IXP Manager GitHub repository...[done]
Create Bcrypt hashed password for user...[done]
Creating database and database users...mysql: [Warning] Using a password on the command line interface can be insecure.
[done]
Creating .env file...[done]
Running composer to install PHP dependencies (please be patient)... [done]
Generating application key... [done]
Setting up IXP Manager database... [done]
Creating IXP Manager database views... mysql: [Warning] Using a password on the command line interface can be insecure.
[done]
Creating initial database entities...mysql: [Warning] Using a password on the command line interface can be insecure.

In IRRDBs.php line 120:
                                  
  Undefined array key "protocol"

**Comment by barryo** [comment]
Thanks @faisalr3za - should be fixed now that I have merged e5b55cd9d82015cbcaf669348238e3205c88d464 from master to release-v6 branch.
