### ISSUE TITLE
Switch configuration port list erroneously lists non-rate limited port as rate limited.

### ISSUE THREAD

**Issue by listerr** [inex/IXP-Manager#757]
##### ISSUE TYPE

Bug Report

##### VERSION

```
define( 'APPLICATION_VERSION', '6.2.0' );
define( 'APPLICATION_VERDATE', '2021111400' );
```   

##### SUMMARY

/resources/views/switches/configuration.foil.php

If one port in a member virtual interface is rate limited and anoither port in another virtual interface is not, this view seems to incorrectly list the non-rate limited port as being also rate limited.

##### STEPS TO REPRODUCE

- Set rate-limit on one port (virtual interface) but not the other.

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/3037635/143619598-06753b2f-6743-460f-bf12-828cd56e6ff7.png)

**Comment by barryo** [comment]
@listerr - I'm afraid I'm going to close this as WONTFIX at this time. We use MySQL;s `GROUP_CONCAT(expr)` in the query to build this table. Unfortunately, this does not allow for blanks / placeholders where one port is rate limited and the other is not.

To illustrate, the results of the query in your edge case are:

```
  1 => array:15 [
    "switchname" => "swic-cix-edge1"
    "switchid" => 78
    "ifName" => "swp11,swp12"
    "speed" => "10000,10000"
    "rate_limit" => "4000"
    "portstatus" => "1,1"
```

So you can see the issue above: two ifName's, two speeds, two status' but only one rate_limit.

Possible fixes like, e.g., defaulting to zero instead of null would work but this would be a mangling of the meaning of zero vs. null to solve this issue. 

A proper fix would require a significant rewrite of the way the query / feature works. I feel this is sufficiently in the corner case box to live with. For now at least.

**Comment by barryo** [comment]
Also ref'd in the code now for future development.

**Comment by listerr** [comment]
Okay, I can see how this is awkward for the ports within the same virtual interface. 

Out of curiosity I just made a query that gets a (more) correct output.

It's less likely you'd have two ports, say, in a LAG, one of which is rate limited and one is not. (If you've got a LAG, there's probably not going to be a rate-limit, and the only other case is if one port is not connected yet.)

I can see it's properly scoped on the cust overview page but not in this page. As the two interfaces _are in different virtual interfaces_, we can at least fix it for this (more likely) case where it's erroneously grouping them together anyway, by including the virtual interface id in the GROUP BY.

So you get a separate row for each group of things in different virtual interfaces, rather than bunching them all together regardless of which virtual interface they belong to.

To approximate this page output:

```
SELECT
    cust.id,
    cust.abbreviatedName,
    switch.name AS switch,
    Group_Concat(DISTINCT swi.name) AS port,
    Group_Concat(phy.speed) AS Group_Concat_speed,
    vlan.name AS peering_vlan,
    cust.autsys,
    Group_Concat(phy.rate_limit) AS Group_Concat_rate_limit,
    Group_Concat(DISTINCT ipv4address.address) AS ipv4address,
    Group_Concat(DISTINCT ipv6address.address) AS ipv6address,
    Group_Concat(phy.status) AS Group_Concat_status
FROM
    cust cust
    LEFT OUTER JOIN virtualinterface vir ON vir.custid = cust.id
    LEFT OUTER JOIN vlaninterface vla ON vla.virtualinterfaceid = vir.id
    LEFT OUTER JOIN physicalinterface phy ON phy.virtualinterfaceid = vir.id
    LEFT OUTER JOIN switchport swi ON phy.switchportid = swi.id
    INNER JOIN switch ON swi.switchid = switch.id
    LEFT OUTER JOIN ipv4address ON vla.ipv4addressid = ipv4address.id
    LEFT OUTER JOIN ipv6address ON vla.ipv6addressid = ipv6address.id
    INNER JOIN vlan vlan ON vla.vlanid = vlan.id
WHERE
    cust.dateleave IS NULL AND
    cust.type != 3 AND
    vlan.id = 1
GROUP BY
    cust.id,
    cust.abbreviatedName,
    switch.name,
    cust.autsys,
    vlan.name,
    cust.type,
    cust.dateleave,
    vir.id,
    vlan.id
```

(Hmm. too much coffee??)
