### ISSUE TITLE
Template entered cannot be found in resources/skins/$skin

### ISSUE THREAD

**Issue by Martolins** [inex/IXP-Manager#763]
##### ISSUE TYPE

Bug Report

##### OS

	Ubuntu 20.04.3 
##### VERSION

```
define( 'APPLICATION_VERSION', '6.2.0' );
define( 'APPLICATION_VERDATE', '2021111400' );

```

##### ENVIRONMENT 

```

```

##### CONFIGURATION

```

```

##### STEPS TO REPRODUCE
In IXP Admin Actions menu:
1) Routers
2) Create a new Router

##### ACTUAL RESULTS

While trying to add a Route Server in IXP Manager and specifying the template path as suggested (_api/v4/router/server/openbgpd/standard_), It errors with: **"The template you entered cannot be found. Please check the help message for more information."** 

I put my custom template under the path 
_/srv/ixpmanager/resources/skins/$skin_name/api/v4/router/server/openbgpd_ and I changed **VIEW_SKIN** variable in _.env_ file with the right value, but it doesn't work. It seems that it doesn't look for the _standard.foil.php_ file in the **Skins** directory. I've already configured it in the same way in the past using IXP manager 5.7.0 version and it worked. So now I can't understand what is the problem.

How can I solve it?

Thank you

**Comment by nickhilliard** [comment]
ixp manager doesn't support creating openbgp route server configurations (yet).  You need to select Bird2.

**Comment by Martolins** [comment]
We have our own custom openbgpd templates in production using the old version of IXP manager (5.8.0) and it works.
