### ISSUE TITLE
routers peering ip in welcome email

### ISSUE THREAD

**Issue by freedomwarrior** [inex/IXP-Manager#793]
Hello!
How can I access to routers peering ip(or router id) in welcome email template ?

**Comment by barryo** [comment]
Not sure which 'router' you mean?

See our (INEX's) comprehensive welcome email and the member's new IP here:

https://github.com/inex/IXP-Manager/blob/master/resources/skins/inex/customer/emails/welcome-email.blade.php#L67

**Comment by freedomwarrior** [comment]
> Not sure which 'router' you mean?
> 
> See our (INEX's) comprehensive welcome email and the member's new IP here:
> 
> https://github.com/inex/IXP-Manager/blob/master/resources/skins/inex/customer/emails/welcome-email.blade.php#L67

I don't want to hardcode the ip addresses of my RS1 and RS2 in welcome email.
And I looking a way how can I access to `router->peering_ip` in welcome email.

**Comment by barryo** [comment]
> I don't want to hardcode the ip addresses of my RS1 and RS2 in welcome email.

In terms of effort vs. reward, ideally your route server IP addresses will hardly ever change so hard coding is the option of least resistance here. Presumable you'll hard code other IX-specific detail in your welcome email anyway?

If you really want to do it, you could try code like:

```php
IXP\Models\Router::routeServer()->notQuarantine()->each( function( $router ) {
    echo $router->peering_ip . "\n";  
} );
```

where the router object has:

```
       IXP\Models\Router {#3223
         id: 5,
         vlan_id: 1,
         handle: "rs1-lan1-ipv4",
         protocol: 4,
         type: 1,
         name: "INEX LAN1 - Route Server - IPv4",
         shortname: "RS1 - LAN1 - IPv4",
         router_id: "192.0.2.18",
         peering_ip: "192.0.2.18",
         asn: 65501,
         software: "1",
         mgmt_host: "203.0.113.18",
         api: "http://rs1-lan1-ipv4.mgmt.example.com/api",
         api_type: 0,
         lg_access: 0,
         quarantine: 0,
         bgp_lc: 0,
         template: "api/v4/router/server/bird/standard",
         skip_md5: 0,
         rpki: 0,
         software_version: null,
         operating_system: null,
         operating_system_version: null,
         rfc1997_passthru: 0,
         created_at: null,
         updated_at: null,
         last_updated: null,
       },
```
