### ISSUE TITLE
User wishing to do an IXF export for just one Infrastructure where an IFX_ID exists

### ISSUE THREAD

**Issue by ninjaix** [inex/IXP-Manager#800]
We had a member ticket where they wanted to do an export via the API for just one infrastructure.   Let's say DB id 10 or IXF-ID 927.  They are getting everything.  The existing documentation and implementation is only for infrastructures NOT in IXF for a single infrastructure..

**Comment by barryo** [comment]
Hi Paul - is there a real requirement for this I wonder? Could they not just filter for the infrastructure they need? Either way, they're parsing the JSON?

**Comment by ninjaix** [comment]
Barry - It's a new member.  I  did give them a parsed output to make
whatever they were using for work. I think it would be a nice addon but
there are plenty of other things I'd like to do first!
