### ISSUE TITLE
NOT able to add Alcatel ALE-OS6900-X20 switch 

### ISSUE THREAD

**Issue by amits1980** [inex/IXP-Manager#805]
HI  I am not able to add  Alcatel ALE-OS6900-X20 switch in IXP manager , getting 500

Server Error :: Undefined array key 1  error on webpage.

![IXP ERROR](https://user-images.githubusercontent.com/105969912/169655328-be5678b9-fc29-4a60-8286-997158d739c6.JPG)

Kindly help.

**Comment by amits1980** [comment]
Anybody can help me about this issue.

**Comment by nickhilliard** [comment]
this is related to https://github.com/opensolutions/OSS_SNMP, which doesn't support the device in question.  Please see https://github.com/opensolutions/OSS_SNMP/wiki/Writing-MIBs for more info on how to resolve it.
