### ISSUE TITLE
Roadmap for version 6.3?

### ISSUE THREAD

**Issue by salvadorb** [inex/IXP-Manager#811]
Hi,
I hope you're doing well. I'm wondering if there's any plan for version 6.3? I have a suggestion, add an integration with Netbox, so IPAM and DCIM can be connected with ixp manager and unsynchronized data can be avoided. 

Best regards

**Comment by barryo** [comment]
Hi @salvadorb,

we've just released v6.3 which is mostly security hardening related.

The IXP Manager Sponsorship Program is about to start the process or recruiting a new developer so we need to get that done before we nail down a specific roadmap. There are specific things on the list:

* OpenDBPd support for route servers
* Member portal area needs a complete reworking
* time-series database integration for peer to peer graphs and visualisations out of that

> add an integration with Netbox, so IPAM and DCIM can be connected with ixp manager and unsynchronized data can be avoided

I don't think the IXP Manager project specifically will develop integrations like this. How everyone does these and represents their data can be different. We could certainly look at example scripts for this or assisting with it. We use IXP Manager and Netbox too but we haven't integrated them for a number of reasons but mostly:

1. DCIM: IXP Manager is not meant to be a DCIM replacement or provide DCIM functionality outside a really small scope (facilities -> racks -> switches). I.e. the specific scope for IXPs. For Netbox, we just add the switches as needed. 
2. IPAM: again, IXP Manager is only interested in IPAM for a really small specific scope: the peering LANs. IXP Manager doesn't do IPAM generally or for anything else. What we do in Netbox is just mark the range as for the IXP and then use IXP Manager for specific information.
