### ISSUE TITLE
Use Local or Shared Copy of PeeringDB

### ISSUE THREAD

**Issue by ninjaix** [inex/IXP-Manager#817]
We would like to see either an option to use a single shared local mysql copy of PeeringDB or have IXP-Manager download this as part of the installation.

Background:
IXP Manager already utilizes PeeringDB to populate member info on setup.
We utilize a local copy of PeeringDB that we setup using PeeringDB-PY here on Github. It is run along with our IXP-Manager database on a separate MySQL server (instance).  We update this 4x daily.  We do this to:
 - to use in our CRM
 - to use with peering-manager
 - to use in some other tool sets
 - to pull a list of ASN with 'Never via Route' set and feed that into our route servers running bird2 with IXP-Manager templates.  We are currently testing this an expect to be able to contribute back our version later this month for evaluation. see https://github.com/inex/IXP-Manager/issues/798
 - to be able to update, programmatically, the may prefixes allowed per protocol, we have the basic of a script but not ready for prime-time.
 - this would not change the way PeeringDB OAUTH is handled. 

The impact on storage, memory and processor is pretty minimal.  The update frequency of a separate PeeringDB database should be able to be set in either a cronjob or .env

**Comment by barryo** [comment]
It should be possible to reference a local PeeringDB install via the `.env` variable `IXP_API_PEERING_DB_URL`.

See [this line of the config file](https://github.com/inex/IXP-Manager/blob/master/config/ixp_api.php#L99). The `%s` is a placeholder for PeeringDB credentials and is used if `IXP_API_PEERING_DB_USERNAME` / `IXP_API_PEERING_DB_PASSWORD` is set but you will need to keep the `%s` as the `sprintf` is used either way.
