### ISSUE TITLE
MRTG Integration with empty graphs

### ISSUE THREAD

**Issue by kotso** [inex/IXP-Manager#826]
Hello,

Running latest version IXPManager and having issue with MRTG integration.

Issue is that IXPManager shows empty graphs, checking page source for graph images shows `src="data:image/png;base64,"` 

And I have no any error in httpd error log or laravel logs. 

I further investigated issue and made sure that mart itself working, to check it I just dumped one of rrd files and it contains all the data, but still all graphs shows as empty.

I would apriciate any idea/help to debug issue further.

IXPmanager: latest current release from GitHub
OS: AlmaLinux 8.7

MRTG: mrtg-2.17.7-1
RRDTool: rrdtool-1.7.0-16
PHP: PHP 8.0.27

PHP Modules installed: 

```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by kotso** [comment]
MRTG and HTTPD are running under same user to avoid any permission issues and selinux is disabled.

**Comment by nickhilliard** [comment]
Not a bug => can you bring this up on the IXP Manager mailing list? https://www.ixpmanager.org/support
