### ISSUE TITLE
Update on compatible Switches - Maybe SONiC?

### ISSUE THREAD

**Issue by fischerdouglas** [inex/IXP-Manager#827]
I looked in the [official IXPManager documentation](https://docs.ixpmanager.org/) and I didn't find explicit references about which switch platforms are supported in integrations and automations.

I also had a quick look on github for the [IXP Manager Provision Templates](https://github.com/inex/ixp-manager-provisioning), but could only find references to Arista-EOS and Cumulus.

The most explicit reference in public documentation that I could find was in the [PDF of the APRICOT presentation](https://2018.apricot.net/assets/files/APNT806/inex-apricot-ixp-automation-2018.pdf), on page 11.
But it's been 5 years since then.
Which makes me believe that probably new platforms could have been added.

Would it be possible to get any update on this?

**Comment by nickhilliard** [comment]
@fischerdouglas we use GH issues for bug reports only.  Can you bring up this topic on ixpmanager@inex.ie?
