### ISSUE TITLE
Logo on login page not loading (IPv6/AAAA for www.ixpmanager.org)

### ISSUE THREAD

**Issue by 9er** [inex/IXP-Manager#831]
##### ISSUE TYPE

Bug Report

##### VERSION

all (between 5.7.0 and 6.3.0)

##### CONFIGURATION

relevant:

```
IDENTITY_BIGLOGO="//www.ixpmanager.org/images/logos/ixp-manager.png"
```

##### SUMMARY

The IXP Manager (biglogo) on the login page does not load. By default, it's loaded from `https://www.ixpmanager.org/images/logos/ixp-manager.png`. This points to:

`www.ixpmanager.org has IPv6 address 2001:7f8:18:2::183`

The address is inside the INEX peering LAN and therefore not routed on the internet, so the server can't be reached.

##### STEPS TO REPRODUCE

Open any IXP Manager login page that uses the default logo.

##### EXPECTED RESULTS

The beautiful IXP Manager logo :)

##### ACTUAL RESULTS

Connection timeout.

##### IMPORTANCE

We just replaced the logo, but fixing the AAAA record for the default URL would still be worth it :)

##### RELEVANT LOGS

N/A

Thanks for all your work on the IXP Manager!

**Comment by barryo** [comment]
Hi @9er 

This looks like a local issue to you or a more generic v6 routing issue - checked from multiple v6 sources via:

```
$ wget -6 -O /dev/null https://www.ixpmanager.org/images/logos/ixp-manager.png
--2023-02-18 17:45:42--  https://www.ixpmanager.org/images/logos/ixp-manager.png
Resolving www.ixpmanager.org (www.ixpmanager.org)... 2001:7f8:18:2::183
Connecting to www.ixpmanager.org (www.ixpmanager.org)|2001:7f8:18:2::183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6907 (6.7K) [image/png]
Saving to: ‘/dev/null’

/dev/null                               100%[=============================================================================>]   6.75K  --.-KB/s    in 0s

2023-02-18 17:45:42 (6.43 GB/s) - ‘/dev/null’ saved [6907/6907]
```

> The address is inside the INEX peering LAN and therefore not routed on the internet, so the server can't be reached.

No, this address isn't a peering address, it's a routed network.

I'm going to close this as it's not an IXP Manager issue but we'll note it to INEX Ops team and have them check deeper re external routing.
