### ISSUE TITLE
Support RS:1102:1 community

### ISSUE THREAD

**Issue by rlaager** [inex/IXP-Manager#843]
The bird2 template does this, in `ixp_community_filter`:
```
    # Implement widely used community filtering schema.
    if (0, peerasn) ~ bgp_community then
            return false;
    if (routeserverasn, peerasn) ~ bgp_community then
            return true;
    if (0, routeserverasn) ~ bgp_community then
            return false;
```

But neither that, nor the caller set the RS:1102:1 community, which is a Euro-IX standard community: https://www.euro-ix.net/en/forixps/large-bgp-communities/

**Comment by rlaager** [comment]
Nevermind. I’m dumb. I’m was distracted with something else and didn’t think this through.

You obviously can’t set a community on a prefix you are NOT sending, and since this is per participant, there is nowhere to flag it to show in the looking glass (and the looking glass is not per participant anyway).

**Comment by barryo** [comment]
Probably what you're looking for is https://github.com/inex/IXP-Manager/blob/master/resources/views/api/v4/router/server/bird2/neighbors.foil.php
