### ISSUE TITLE
Support bgpq4

### ISSUE THREAD

**Issue by rlaager** [inex/IXP-Manager#844]
bgpq4 (versions 1.7 and up) support the RADB::AS-FOO syntax.

https://github.com/bgp/bgpq4#notes-on-sources
https://github.com/bgp/bgpq4/commit/08b81f7d1973b8ccdbf627bb60063a97bc1c1fed

The command line arguments seem the same, so I don't know that there's actually anything to do here other than document that it works.

**Comment by rlaager** [comment]
bgpq4 does not support the `-3` argument, so this is an issue:
https://github.com/inex/IXP-Manager/blob/bcaab7cb2bb9f281f75056878ccceb5ed7d9da45/app/Utils/Bgpq3.php#L105

**Comment by barryo** [comment]
What's the fallout of not having the -3 argument?

Does bgpq4 make that assumption by default?

**Comment by barryo** [comment]
Answering my own question - the fallout is significant. 

```
$ bgpq3 -jt AS-HURRICANE | tail -2
  64465,64466,64470,64477,64481,64490
]}
```

```
bgpq3 -3jt AS-HURRICANE | tail -3
  400757,400759,400771,400786,400800,400810,400846,401307,
  522123,645180
]}
```

So this requires some minor coding. Tagging as feature request.

**Comment by rlaager** [comment]
I agree that bgpq4 does it by default.

**Comment by rlaager** [comment]
I submitted a pull request to bgpq4. The response in the issue was favorable and the PR is trivial, so I'm optimistic this will be accepted.

**Comment by rlaager** [comment]
The PR has been merged. So that will show up in bgpq4 1.10 (I assume that will be the version) whenever they release it.
