### ISSUE TITLE
Allow showing contact emails in public IX-F export

### ISSUE THREAD

**Issue by rlaager** [inex/IXP-Manager#849]
The IX-F export only shows contact_email `$detailed` is set, which is set to `Auth::check()` here: https://github.com/inex/IXP-Manager/blob/9b278b77966187d235e6eeb1a80811cfb9dc7f49/app/Http/Controllers/Api/V4/MemberExportController.php#L69

In other words, you only get the contact_email if you are logged in.

MICE has traditionally shown these publicly. And generally speaking, these are the same as what is in PeeringDB anyway.

Would you be agreeable to an option to show these publicly? If so, do you have suggestions on how to implement that?

One possible answer would be to make the IX-F export skinnable and move the check into the template. Then I could just skin it and remove the check. But @barryo is against that here: https://github.com/inex/IXP-Manager/issues/838#issuecomment-1527723747

**Comment by barryo** [comment]
Hi @rlaager  - PeeringDB also put that information behind an authwall iirc.

Nearly all networks have NOC contact details that are different to generic frontline support@ for customers and we need to entice networks to provide that information to their peers. One of the ways we do that is by assuring them it will only be available to other members of the exchange (i.e. not public). They'll also want this to avoid email harvesting by spam bots, etc. 

I think we have a good compromise here and it would be quite problematic to change it for us and all other ixps that have relied on this and make similar commitments.
