### ISSUE TITLE
Feature-request: internationalization (gettext-style)

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#86]
On our own install we have used skins to make a large percentage of the interface's text Greek, but this has two problems:
- much of the viewable text is controller-generated and can't be "skinned" (so can't be translated that way)
- a whole tree of skinned translations requires _substantial_ maintenance-time every time a view's structure is changed in the main code

It would be good to migrate all non-custom visible text to a gettext-style internationalization scheme so that non-English in the interface can be a viable, maintainable option.

**Comment by barryo** [comment]
This is on a long-term plan list -> closing issue.
