### ISSUE TITLE
Regression: MRTG Graphs for reseller uplink ports are no longer generated.

### ISSUE THREAD

**Issue by ichilton** [inex/IXP-Manager#860]
Commit https://github.com/inex/IXP-Manager/commit/e40be75de9deec22978df766dee88b912242316b, which was to fix https://github.com/inex/IXP-Manager/issues/855 contains a regression: it no longer generates graphs for reseller uplink ports.

It should generate port graphs for reseller uplink ports, it just shouldn't sum reseller uplink ports in the aggregates.

**Comment by barryo** [comment]
@ichilton - pull from release-v6 to get 4420a5905e0b310c7703a6d3002422c3654fc400 which should fix it I think. Seems to work for INEX.

**Comment by ichilton** [comment]
@barryo Thank you very much! - will pull now and test!
