### ISSUE TITLE
Add "restrictive" peering policy

### ISSUE THREAD

**Issue by lucix-mich** [inex/IXP-Manager#866]
IXP Manager currently doesn't have a "restrictive" option for peering policy. At LU-CIX, we have that option. PeeringDB also offers this option. It is used "in the wild".

I see two options:

- either simply add this peering policy to the proposed list,
- or better even, provide an option to edit the list of peering policies to match what is offered at the IXP. I suppose this should not create any interdependencies since I _think_ policies are only for documentary purpose, but don't influence anything else.

Thanks and cheers

Michel

**Comment by barryo** [comment]
Hi @lucix-mich  - this was discussed in #858 and we couldn't see any difference between selective and restrictive and nor could PeeringDB explain a difference as I recall.
