### ISSUE TITLE
ERROR : OSS_SNMP Exception Polling Switch xxxx by SNMP

### ISSUE THREAD

**Issue by rifqifdlr** [inex/IXP-Manager#867]
Hello my name is Rifqi, I just want to use ixpmanager. I have a problem with adding a switch via SNMP. There are 2 switches that I use. The first is Arista, the second is Edgecore. Arista can be added to ixpmanager, but not for Edgecore. There is an error reading according to what I made in the title. Is it because Edgecore is not listed as a vendor in the ixpmanager? If so, can it be added to the Edgecore switch vendor category? Thank You

**Comment by barryo** [comment]
Hi @rifqifdlr - the switch needs to be supported by another project that we use over at https://github.com/opensolutions/OSS_SNMP

Can you look at the instructions here https://github.com/opensolutions/OSS_SNMP/wiki/Device-Discovery#adding-new-devices and open a ticket?

Also note that with Edgecore, they can run different NOS' so provide those details too. E.g. Cumulus on Edgecore should work fine.

Once it's updated in the project, we'll pull it in for the next release.
