### ISSUE TITLE
Query related to Looking glass for PfxExp table

### ISSUE THREAD

**Issue by nitesh058** [inex/IXP-Manager#869]
Hi Team,
We have a query in looking glass related to **PfxExp** route table.

In our two BGP sessions, export routes (PfxExp) are only showing count, not able to click on it to view routes, please find the screenshot.

Please help on this or do we have to make any additional changes for routes visibility in looking glass, as for the other two we have no issue and are also able to click on their prefix count. 

![image](https://github.com/inex/IXP-Manager/assets/39797731/82f1cac5-b379-448a-850e-a3d7db160b69)

**Comment by nickhilliard** [comment]
this is determined by the `MAX_ROUTES` setting in the birdseye .env config file.

Please direct questions to the ixpmanager@inex.ie mailing list.  We use github issues for bug tracking only.

https://www.ixpmanager.org/support/mailing-lists
