### ISSUE TITLE
Getting issue with 32 bit route server ASN

### ISSUE THREAD

**Issue by nitesh058** [inex/IXP-Manager#871]
Hi,
We are using 32 bit ASN (150528) Route Server, till last week, route server's configuration from IXP Manager was operating without issue.
But now, the new configuration generated file is giving below-mentioned error.

Error:
**bird: /usr/local/etc/bird/bird-rs1-ipv4.conf.1793224:184:26 filter preevaluation, line 184: Can't operate with value out of bounds in pair constructor**

Note: It is not giving any error for 16 bit ASN Test Route Servers.
Kindly look into this and appreciate, if you can provide the solution for 32 bit ASN route server.

Also I have tried below link, which is suggested by Barry in somewhere, but it not working for us.
https://gist.github.com/barryo/ded53053ddf9ab86b5bb3a9698f9219a/revisions

**Comment by nickhilliard** [comment]
Please direct questions to the ixpmanager@inex.ie mailing list. We use github issues for bug tracking only.

https://www.ixpmanager.org/support/mailing-lists
