### ISSUE TITLE
ERROR: OSS_SNMP exception polling switch ports for DC01-LEAF-01 by SNMP

### ISSUE THREAD

**Issue by rifqifdlr** [inex/IXP-Manager#872]
##### ISSUE TYPE

ERROR: OSS_SNMP exception polling switch ports for DC01-LEAF-01 by SNMP

##### OS

Ubuntu 20.04 OS running IXP Manager
##### VERSION

define( 'APPLICATION_VERSION', '6.3.1' );
define( 'APPLICATION_VERDATE', '2023062000' );

##### ENVIRONMENT 

php8.0.29

##### CONFIGURATION

APP_DEBUG=false
APP_URL="http://172.16.1.250"
APP_TIMEZONE="UTC"
APP_LOG="single"
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=true
IXP_FE_FRONTEND_DISABLED_LOGO=true
 IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
GRAPHER_BACKENDS="mrtg"
GRAPHER_CACHE_ENABLED=true
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
CACHE_DRIVER=memcached
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq3
##### SUMMARY
Hello, I have a problem in my ixpmanager. When I add my switch with SNMP it show error: oss_snmp exception polling switch ports. My switch is arista DCS-7160-32CQ-F, then my switch is running behind a switch controller by Arista Cloud Converged Fabric. But when I adding without a controller its fine. I think that ixpmanager can't run with a switch controller that has SDN technology, but can only add an ordinary switch.

**Comment by barryo** [comment]
> I think that ixpmanager can't run with a switch controller that has SDN technology, but can only add an ordinary switch.

That may certainly be the case. We use a package called [OSS_SNMP](https://github.com/opensolutions/OSS_SNMP) which is a fairly simple snmp request tool for specific OIDs. I imagine your SDN is more complex as it would need to additionally identify the switch in the request?

I'll close this as it's not something IXP Manager can directly support and suggest you pop over to OSS_SNMP with a ticket and I can try and help there. We'd need much more detail of what the SNMP requests should look like though.
