### ISSUE TITLE
Could not perform walk OID .1.3.6.1.2.1.31.1.1.1.18

### ISSUE THREAD

**Issue by rifqifdlr** [inex/IXP-Manager#874]
ISSUE TYPE
Could not perform walk OID .1.3.6.1.2.1.31.1.1.1.18

OS
Ubuntu 20.04 OS running IXP Manager

VERSION
define( 'APPLICATION_VERSION', '6.3.1' );
define( 'APPLICATION_VERDATE', '2023062000' );

ENVIRONMENT
php8.0.29

CONFIGURATION
APP_DEBUG=false
APP_URL="http://172.16.1.250/"
APP_TIMEZONE="UTC"
APP_LOG="single"
IXP_RESELLER_ENABLED=false
IXP_AS112_UI_ACTIVE=true
IXP_FE_FRONTEND_DISABLED_LOGO=true
IXP_FE_FRONTEND_DISABLED_LOOKING_GLASS=false
GRAPHER_BACKENDS="mrtg"
GRAPHER_CACHE_ENABLED=true
GRAPHER_BACKEND_MRTG_DBTYPE="rrd"
GRAPHER_BACKEND_MRTG_WORKDIR="/srv/mrtg"
GRAPHER_BACKEND_MRTG_LOGDIR="/srv/mrtg"
IXP_API_JSONEXPORTSCHEMA_PUBLIC=true
CACHE_DRIVER=memcached
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq3

Question
Hello, my name is Rifqi, I have a case namely "Could not perform walk OID .1.3.6.1.2.1.31.1.1.1.18". This happens on edgecore switches. However, if I try it on another switch like Arista it works. Is there a solution so that my edgecore switch can do this?

**Comment by nickhilliard** [comment]
This is a support request, not an IXP Manager bug. Can you subscribe to the mailing list and post there?

https://www.ixpmanager.org/support/mailing-lists

**Comment by rifqifdlr** [comment]
I have done subscribe to the mailing list, can you help me how to post there?

**Comment by nickhilliard** [comment]
https://www.inex.ie/mailman/listinfo/ixpmanager

```
Using ixpmanager
--
To post a message to all the list members, send email to 	  ixpmanager@inex.ie.
```

**Comment by rifqifdlr** [comment]
OK, thank you!
