### ISSUE TITLE
Use MANRS API

### ISSUE THREAD

**Issue by rlaager** [inex/IXP-Manager#884]
https://www.manrs.org/wp-json/manrs/v1/asn is not updating.

For example, AS10750 is a MANRS participant but not in the above list: https://manrs.org/participant/5635/

I am reaching out to MANRS, but I suspect their answer is going to be to use their (new?) API: https://manrs.stoplight.io/docs/manrs-public-api/a92b125a409fa-list-asn-info

It looks like that is going to require a token as a setting in IXP Manager.

**Comment by nickhilliard** [comment]
The MANRS URL seems to be updating again, and now includes 10750.  Did you get a reply from the MANRS ops people about long term support plans for [/wp-json/manrs/v1/asn](https://www.manrs.org/wp-json/manrs/v1/asn)?

**Comment by rlaager** [comment]
They have not responded at all.

**Comment by nickhilliard** [comment]
MANRS hasn't indicated that they're sunsetting the API. If they do, we'll update the IXP Manager code.

**Comment by rlaager** [comment]
They actually just responded to me earlier today. “we are planning to keep this endpoint for at least a year and will coordinate the transition with the developers of the IXP Manager.”
