### ISSUE TITLE
Collector Startup Failure After Upgrade to Version 6.4.0

### ISSUE THREAD

**Issue by elias0311** [inex/IXP-Manager#895]
This report details an issue with the route collector failing to start after upgrading to IXP Manager version 6.4.0. Despite updating the provisioning script, the route collector still encounters an error preventing its startup.

Error Message:

ERROR: /usr/sbin/bird was not running for /etc/bird/bird-rc1-lan1-ipv4.conf.1550 and could not be started
Analysis:

While the configuration files in the /etc/bird/ directory have been downloaded successfully, it appears there is a configuration issue preventing the bird service from starting using these configurations. This issue is specific to the route collector and does not affect the route-servers, which are functioning as expected.

**Comment by barryo** [comment]
Hi @elias0311 - can you provide the output of:

```
bird --version
bird -c test.conf -p
```

and then the configuration around the lines it complains about?

**Comment by barryo** [comment]
@elias0311  - please replace `test.conf` with the appropriate configuration file for you.

**Comment by elias0311** [comment]
@barryo 

bird -c /etc/bird/bird-rc1-lan1-ipv4.conf.19932 -p
no showing error but when i try to connect to bird with socket say connection refused

birdc -s /var/run/bird/bird-rc1-lan1-ipv4.ctl
Unable to connect to server control socket (/var/run/bird/bird-rc1-lan1-ipv4.ctl): Connection refused

**Comment by nickhilliard** [comment]
@elias0311 this looks like a configuration problem rather than a bug. Can you take the issue to the ixpmanager users mailing list:

https://www.ixpmanager.org/support/mailing-lists

**Comment by barryo** [comment]
> bird -c /etc/bird/bird-rc1-lan1-ipv4.conf.19932 -p
> no showing error but when i try to connect to bird with socket say connection refused

Is there any output? What is the return code (`echo $?`)?

What happens if you try to run it manually:

```
/usr/sbin/bird -c /etc/bird/bird-rc1-lan1-ipv4.conf.19932 -s /var/run/bird/bird-rc1-lan1-ipv4.ctl
```

**Comment by elias0311** [comment]
>What happens if you try to run it manually:

>/usr/sbin/bird -c /etc/bird/bird-rc1-lan1-ipv4.conf.19932 -s /var/run/bird/bird-rc1-lan1-ipv4.ctl
Nothing happend, bird still not running

**Comment by barryo** [comment]
@elias0311 I think you need to engage someone with Linux command line skills locally to help you diagnose this as it does not seem like an IXP Manager issue.
