### ISSUE TITLE
IX-F Member Export Cannot Exlcude ASN/Tag

### ISSUE THREAD

**Issue by takizo** [inex/IXP-Manager#898]
##### ISSUE TYPE

Bug Report

##### OS

Ubuntu 22.04 

##### VERSION

6.3.1

```

```

##### SUMMARY

Trying to exclude certain members for IX-F member export page (https://ixpmanager.dev/api/v4/member-export/ixf/1.0). Exclude ASN / TAG are not working., the tag has been created for the member. 

Example

IXP_API_JSONEXPORTSCHEMA_EXCLUDE_ASNUM="215859"
IXP_API_JSONEXPORTSCHEMA_EXCLUDE_TAGS="no-ixf-export"

##### STEPS TO REPRODUCE

Add these lines in .env 

IXP_API_JSONEXPORTSCHEMA_EXCLUDE_ASNUM="215859"
IXP_API_JSONEXPORTSCHEMA_EXCLUDE_TAGS="no-ixf-export"

##### EXPECTED RESULTS

Not suppose to show the excluded ASN, how's the page https://ixpmanager.dev/api/v4/member-export/ixf/1.0 are still seeing the member with the ASN 215859 

##### ACTUAL RESULTS

Still showing ASN215859 result in JSON format.

**Comment by barryo** [comment]
Hi @takizo - this was a known issue in previous versions but works as expected in v6.4.0/v6.4.1.
