### ISSUE TITLE
ISSUE WITH MRTG

### ISSUE THREAD

**Issue by cfalconapven** [inex/IXP-Manager#901]
Hi, actually this is my first time using IXP Manager, I have a question and it is if graphics from MRTG are just coming from configured VLANs on IXP manager, despite I set up a production VLAN to try if graphics are working before starting peering tasks I have had no success on Debian 11. 

My .env file has the next config:
--------------------------------------------------------------
#######################################################################################
### Graphing - see https://docs.ixpmanager.org/grapher/introduction

# Enable the backends you have configured. E.g.:
GRAPHER_BACKENDS="mrtg|sflow|smokeping"

# On a new installation, we just use placeholders from the dummy backend:
#GRAPHER_BACKENDS="dummy"

# With the cache enabled, IXP Manager does not have to regenerate / reload / reprocess
# log / rrd / image files if we have cached them and they are less than 5mins old. This
# is enabled by default which is the recommended setting.
GRAPHER_CACHE_ENABLED=true

#################################################################################
##

# For backwards compatibility, the default is 'log' but 'rrd' is more modern:
GRAPHER_BACKEND_MRTG_DBTYPE="log"
-------------------------------------------------------------------------------------------------------------------------

The configuration for mrtg automatically generated looks like this: 
root@ixp:/srv/ixpmanager# php artisan grapher:generate-configuration -B mrtg | less
###
### Generated: 2024-07-26 09:15:26

#
# IXP Manager MRTG configuration file
#
# This file is generated by IXP Manager.
#

### Global Config Options
WorkDir: /srv/mrtg
RunAsDaemon:Yes
Interval:5
IconDir: /images/

### Global Defaults
#  to get bits instead of bytes and graphs growing to the right
Options[_]: growright, bits
WithPeak[_]: ym
PageTop[_]: <h1>Servicios Nap Ven, C.A Traffic Analysis</h1>
PageFoot[_]:  <table border=0 cellspacing=0 cellpadding=0 width=476>
  <tr valign=top>
   <td width="95%" align=right style="font: Arial,Helvetica; size: 80%">
     Based on configuration last generated by <a href="https://github.com/inex/IXP-Manager">IXP Manager</a> at 2024-07-26 09:15:26   </td>
  </tr>
 </table>

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
###
###
###
###
###
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#
# ixp001-infra002-bits
#

Target[ixp001-infra002-bits]:    1.3.6.1.2.1.31.1.1.1.6#Ethernet1&1.3.6.1.2.1.31.1.1.1.10#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-infra002-bits]:     Servicios Nap Ven, C.A Bits / second on CIRION-LA URBINA
Options[ixp001-infra002-bits]:   growright,bits , pngdate
YLegend[ixp001-infra002-bits]:   Bits / Second
MaxBytes[ixp001-infra002-bits]:  1250000000
Directory[ixp001-infra002-bits]: infras/002

#####################################################################################################################
#
# ixp001-infra002-pkts
#

Target[ixp001-infra002-pkts]:    1.3.6.1.2.1.31.1.1.1.7#Ethernet1&1.3.6.1.2.1.31.1.1.1.11#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-infra002-pkts]:     Servicios Nap Ven, C.A Packets / second on CIRION-LA URBINA
Options[ixp001-infra002-pkts]:   growright , pngdate
YLegend[ixp001-infra002-pkts]:   Packets / Second
MaxBytes[ixp001-infra002-pkts]:  19531250
Directory[ixp001-infra002-pkts]: infras/002

#####################################################################################################################
#
# ixp001-infra002-errs
#

Target[ixp001-infra002-errs]:    1.3.6.1.2.1.2.2.1.14#Ethernet1&1.3.6.1.2.1.2.2.1.20#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-infra002-errs]:     Servicios Nap Ven, C.A Errors / second on CIRION-LA URBINA
Options[ixp001-infra002-errs]:   growright , pngdate
YLegend[ixp001-infra002-errs]:   Errors / Second
MaxBytes[ixp001-infra002-errs]:  19531250
Directory[ixp001-infra002-errs]: infras/002

#####################################################################################################################
#
# ixp001-infra002-discs
#

Target[ixp001-infra002-discs]:    1.3.6.1.2.1.2.2.1.13#Ethernet1&1.3.6.1.2.1.2.2.1.19#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-infra002-discs]:     Servicios Nap Ven, C.A Discards / second on CIRION-LA URBINA
Options[ixp001-infra002-discs]:   growright , pngdate
YLegend[ixp001-infra002-discs]:   Discards / Second
MaxBytes[ixp001-infra002-discs]:  19531250
Directory[ixp001-infra002-discs]: infras/002

#####################################################################################################################
#
# ixp001-infra002-bcasts
#

Target[ixp001-infra002-bcasts]:    1.3.6.1.2.1.31.1.1.1.9#Ethernet1&1.3.6.1.2.1.31.1.1.1.13#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-infra002-bcasts]:     Servicios Nap Ven, C.A Broadcasts / second on CIRION-LA URBINA
Options[ixp001-infra002-bcasts]:   growright , pngdate
YLegend[ixp001-infra002-bcasts]:   Broadcasts / Second
MaxBytes[ixp001-infra002-bcasts]:  19531250
Directory[ixp001-infra002-bcasts]: infras/002

#####################################################################################################################
#
# ixp001-bits
#

Target[ixp001-bits]:    1.3.6.1.2.1.31.1.1.1.6#Ethernet1&1.3.6.1.2.1.31.1.1.1.10#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-bits]:     Servicios Nap Ven, C.A - Bits / second
Options[ixp001-bits]:   growright,bits , pngdate
YLegend[ixp001-bits]:   Bits / Second
MaxBytes[ixp001-bits]:  1250000000
Directory[ixp001-bits]: ixp

#####################################################################################################################
#
# ixp001-pkts
#

Target[ixp001-pkts]:    1.3.6.1.2.1.31.1.1.1.7#Ethernet1&1.3.6.1.2.1.31.1.1.1.11#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-pkts]:     Servicios Nap Ven, C.A - Packets / second
Options[ixp001-pkts]:   growright , pngdate
YLegend[ixp001-pkts]:   Packets / Second
MaxBytes[ixp001-pkts]:  19531250
Directory[ixp001-pkts]: ixp

#####################################################################################################################
#
# ixp001-errs
#

Target[ixp001-errs]:    1.3.6.1.2.1.2.2.1.14#Ethernet1&1.3.6.1.2.1.2.2.1.20#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-errs]:     Servicios Nap Ven, C.A - Errors / second
Options[ixp001-errs]:   growright , pngdate
YLegend[ixp001-errs]:   Errors / Second
MaxBytes[ixp001-errs]:  19531250
Directory[ixp001-errs]: ixp

#####################################################################################################################
#
# ixp001-discs
#

Target[ixp001-discs]:    1.3.6.1.2.1.2.2.1.13#Ethernet1&1.3.6.1.2.1.2.2.1.19#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-discs]:     Servicios Nap Ven, C.A - Discards / second
Options[ixp001-discs]:   growright , pngdate
YLegend[ixp001-discs]:   Discards / Second
MaxBytes[ixp001-discs]:  19531250
Directory[ixp001-discs]: ixp

#####################################################################################################################
#
# ixp001-bcasts
#

Target[ixp001-bcasts]:    1.3.6.1.2.1.31.1.1.1.9#Ethernet1&1.3.6.1.2.1.31.1.1.1.13#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[ixp001-bcasts]:     Servicios Nap Ven, C.A - Broadcasts / second
Options[ixp001-bcasts]:   growright , pngdate
YLegend[ixp001-bcasts]:   Broadcasts / Second
MaxBytes[ixp001-bcasts]:  19531250
Directory[ixp001-bcasts]: ixp

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
###
###
###
###
###
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#
# location-aggregate-00001-bits
#

Target[location-aggregate-00001-bits]:    1.3.6.1.2.1.31.1.1.1.6#Ethernet1&1.3.6.1.2.1.31.1.1.1.10#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[location-aggregate-00001-bits]:     Servicios Nap Ven, C.A - Peering Bits / second on CIRION-LA URBINA
Options[location-aggregate-00001-bits]:   growright,bits , pngdate
YLegend[location-aggregate-00001-bits]:   Bits / Second
MaxBytes[location-aggregate-00001-bits]:  1250000000
Directory[location-aggregate-00001-bits]: locations/001

#####################################################################################################################
#
# location-aggregate-00001-pkts
#

Target[location-aggregate-00001-pkts]:    1.3.6.1.2.1.31.1.1.1.7#Ethernet1&1.3.6.1.2.1.31.1.1.1.11#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[location-aggregate-00001-pkts]:     Servicios Nap Ven, C.A - Peering Packets / second on CIRION-LA URBINA
Options[location-aggregate-00001-pkts]:   growright , pngdate
YLegend[location-aggregate-00001-pkts]:   Packets / Second
MaxBytes[location-aggregate-00001-pkts]:  19531250
Directory[location-aggregate-00001-pkts]: locations/001

#####################################################################################################################
#
# location-aggregate-00001-errs
#

Target[location-aggregate-00001-errs]:    1.3.6.1.2.1.2.2.1.14#Ethernet1&1.3.6.1.2.1.2.2.1.20#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[location-aggregate-00001-errs]:     Servicios Nap Ven, C.A - Peering Errors / second on CIRION-LA URBINA
Options[location-aggregate-00001-errs]:   growright , pngdate
YLegend[location-aggregate-00001-errs]:   Errors / Second
MaxBytes[location-aggregate-00001-errs]:  19531250
Directory[location-aggregate-00001-errs]: locations/001

#####################################################################################################################
#
# location-aggregate-00001-discs
#

Target[location-aggregate-00001-discs]:    1.3.6.1.2.1.2.2.1.13#Ethernet1&1.3.6.1.2.1.2.2.1.19#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[location-aggregate-00001-discs]:     Servicios Nap Ven, C.A - Peering Discards / second on CIRION-LA URBINA
Options[location-aggregate-00001-discs]:   growright , pngdate
YLegend[location-aggregate-00001-discs]:   Discards / Second
MaxBytes[location-aggregate-00001-discs]:  19531250
Directory[location-aggregate-00001-discs]: locations/001

#####################################################################################################################
#
# location-aggregate-00001-bcasts
#

Target[location-aggregate-00001-bcasts]:    1.3.6.1.2.1.31.1.1.1.9#Ethernet1&1.3.6.1.2.1.31.1.1.1.13#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[location-aggregate-00001-bcasts]:     Servicios Nap Ven, C.A - Peering Broadcasts / second on CIRION-LA URBINA
Options[location-aggregate-00001-bcasts]:   growright , pngdate
YLegend[location-aggregate-00001-bcasts]:   Broadcasts / Second
MaxBytes[location-aggregate-00001-bcasts]:  19531250
Directory[location-aggregate-00001-bcasts]: locations/001

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
###
###
###
###
###
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#
# switch-aggregate-00007-bits
#

Target[switch-aggregate-00007-bits]:    1.3.6.1.2.1.31.1.1.1.6#Ethernet1&1.3.6.1.2.1.31.1.1.1.10#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[switch-aggregate-00007-bits]:     Servicios Nap Ven, C.A - Peering Bits / second on SW-01
Options[switch-aggregate-00007-bits]:   growright,bits , pngdate
YLegend[switch-aggregate-00007-bits]:   Bits / Second
MaxBytes[switch-aggregate-00007-bits]:  1250000000
Directory[switch-aggregate-00007-bits]: switches/007

#####################################################################################################################
#
# switch-aggregate-00007-pkts
#

Target[switch-aggregate-00007-pkts]:    1.3.6.1.2.1.31.1.1.1.7#Ethernet1&1.3.6.1.2.1.31.1.1.1.11#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[switch-aggregate-00007-pkts]:     Servicios Nap Ven, C.A - Peering Packets / second on SW-01
Options[switch-aggregate-00007-pkts]:   growright , pngdate
YLegend[switch-aggregate-00007-pkts]:   Packets / Second
MaxBytes[switch-aggregate-00007-pkts]:  19531250
Directory[switch-aggregate-00007-pkts]: switches/007

#####################################################################################################################
#
# switch-aggregate-00007-errs
#

Target[switch-aggregate-00007-errs]:    1.3.6.1.2.1.2.2.1.14#Ethernet1&1.3.6.1.2.1.2.2.1.20#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[switch-aggregate-00007-errs]:     Servicios Nap Ven, C.A - Peering Errors / second on SW-01
Options[switch-aggregate-00007-errs]:   growright , pngdate
YLegend[switch-aggregate-00007-errs]:   Errors / Second
MaxBytes[switch-aggregate-00007-errs]:  19531250
Directory[switch-aggregate-00007-errs]: switches/007

#####################################################################################################################
#
# switch-aggregate-00007-discs
#

Target[switch-aggregate-00007-discs]:    1.3.6.1.2.1.2.2.1.13#Ethernet1&1.3.6.1.2.1.2.2.1.19#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[switch-aggregate-00007-discs]:     Servicios Nap Ven, C.A - Peering Discards / second on SW-01
Options[switch-aggregate-00007-discs]:   growright , pngdate
YLegend[switch-aggregate-00007-discs]:   Discards / Second
MaxBytes[switch-aggregate-00007-discs]:  19531250
Directory[switch-aggregate-00007-discs]: switches/007

#####################################################################################################################
#
# switch-aggregate-00007-bcasts
#

Target[switch-aggregate-00007-bcasts]:    1.3.6.1.2.1.31.1.1.1.9#Ethernet1&1.3.6.1.2.1.31.1.1.1.13#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[switch-aggregate-00007-bcasts]:     Servicios Nap Ven, C.A - Peering Broadcasts / second on SW-01
Options[switch-aggregate-00007-bcasts]:   growright , pngdate
YLegend[switch-aggregate-00007-bcasts]:   Broadcasts / Second
MaxBytes[switch-aggregate-00007-bcasts]:  19531250
Directory[switch-aggregate-00007-bcasts]: switches/007

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

# Manually insert a bunch of definitions here for your IXP's trunk links
# between switches.  There is really no way to be able to create a sane
# definition of these in the IXP Manager database, so we chicken out and let
# each IXP do it manually.  Simplicity r00lz.
#
# See: https://github.com/inex/IXP-Manager/wiki/MRTG---Traffic-Graphs#inter-switch-link-graphs
#
# Here are some examples.

## degkcp-ixdub1 - LAN1
#Target[core-degkcp-ixdub1-lan1]: #ethernet23:sillypassword@swi1-deg1-2:::::2 + #ethernet24:sillypassword@swi1-deg1-2:::::2
#MaxBytes[core-degkcp-ixdub1-lan1]: 2500000000
#Directory[core-degkcp-ixdub1-lan1]: trunks
#Title[core-degkcp-ixdub1-lan1]: Trunk Core - DEGKCP-IXDUB1 - LAN1

## tcydub1-ixdub1 - LAN1
#Target[core-tcydub1-ixdub1-lan1]: #ethernet23:sillypassword@swi1-ix1-1:::::2 + #ethernet24:sillypassword@swi1-ix1-1:::::2
#MaxBytes[core-tcydub1-ixdub1-lan1]: 2500000000
#Directory[core-tcydub1-ixdub1-lan1]: trunks
#Title[core-tcydub1-ixdub1-lan1]: Trunk Core - TCYDUB1-IXDUB1 - LAN1

## swi1-ix1-1 - swi1-ix1-2
#Target[core-swi1-ix1-1_swi1-ix1-2-lan1]: #ethernet21:sillypassword@swi1-ix1-1:::::2 + #ethernet22:sillypassword@swi1-ix1-1:::::2
#MaxBytes[core-swi1-ix1-1_swi1-ix1-2-lan1]: 2500000000
#Directory[core-swi1-ix1-1_swi1-ix1-2-lan1]: trunks
#Title[core-swi1-ix1-1_swi1-ix1-2-lan1]: Inter-POP Trunk Core - IXDUB1 - swi1-ix1-1 swi1-ix1-2 - LAN1

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
###
###
###
###
###
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
###
#####################################################################################################################
#
# pi00001-bits
#

Target[pi00001-bits]:    1.3.6.1.2.1.31.1.1.1.6#Ethernet1&1.3.6.1.2.1.31.1.1.1.10#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[pi00001-bits]:     NAPVE -- Ethernet1 -- SW-01 -- Bits / second
Options[pi00001-bits]:   growright,bits , pngdate
YLegend[pi00001-bits]:   Bits / Second
MaxBytes[pi00001-bits]:  1250000000
Directory[pi00001-bits]: members/1/00001/ints

#####################################################################################################################
#
# pi00001-pkts
#

Target[pi00001-pkts]:    1.3.6.1.2.1.31.1.1.1.7#Ethernet1&1.3.6.1.2.1.31.1.1.1.11#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[pi00001-pkts]:     NAPVE -- Ethernet1 -- SW-01 -- Packets / second
Options[pi00001-pkts]:   growright , pngdate
YLegend[pi00001-pkts]:   Packets / Second
MaxBytes[pi00001-pkts]:  19531250
Directory[pi00001-pkts]: members/1/00001/ints

#####################################################################################################################
#
# pi00001-errs
#

Target[pi00001-errs]:    1.3.6.1.2.1.2.2.1.14#Ethernet1&1.3.6.1.2.1.2.2.1.20#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[pi00001-errs]:     NAPVE -- Ethernet1 -- SW-01 -- Errors / second
Options[pi00001-errs]:   growright , pngdate
YLegend[pi00001-errs]:   Errors / Second
MaxBytes[pi00001-errs]:  19531250
Directory[pi00001-errs]: members/1/00001/ints

#####################################################################################################################
#
# pi00001-discs
#

Target[pi00001-discs]:    1.3.6.1.2.1.2.2.1.13#Ethernet1&1.3.6.1.2.1.2.2.1.19#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[pi00001-discs]:     NAPVE -- Ethernet1 -- SW-01 -- Discards / second
Options[pi00001-discs]:   growright , pngdate
YLegend[pi00001-discs]:   Discards / Second
MaxBytes[pi00001-discs]:  19531250
Directory[pi00001-discs]: members/1/00001/ints

#####################################################################################################################
#
# pi00001-bcasts
#

Target[pi00001-bcasts]:    1.3.6.1.2.1.31.1.1.1.9#Ethernet1&1.3.6.1.2.1.31.1.1.1.13#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[pi00001-bcasts]:     NAPVE -- Ethernet1 -- SW-01 -- Broadcasts / second
Options[pi00001-bcasts]:   growright , pngdate
YLegend[pi00001-bcasts]:   Broadcasts / Second
MaxBytes[pi00001-bcasts]:  19531250
Directory[pi00001-bcasts]: members/1/00001/ints

#####################################################################################################################
#
# aggregate-00001-bits
#

Target[aggregate-00001-bits]:    1.3.6.1.2.1.31.1.1.1.6#Ethernet1&1.3.6.1.2.1.31.1.1.1.10#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[aggregate-00001-bits]:     NAPVE -- IXP Total Aggregate -- Bits / second
Options[aggregate-00001-bits]:   growright,bits , pngdate
YLegend[aggregate-00001-bits]:   Bits / Second
MaxBytes[aggregate-00001-bits]:  1250000000
Directory[aggregate-00001-bits]: members/1/00001

#####################################################################################################################
#
# aggregate-00001-pkts
#

Target[aggregate-00001-pkts]:    1.3.6.1.2.1.31.1.1.1.7#Ethernet1&1.3.6.1.2.1.31.1.1.1.11#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[aggregate-00001-pkts]:     NAPVE -- IXP Total Aggregate -- Packets / second
Options[aggregate-00001-pkts]:   growright , pngdate
YLegend[aggregate-00001-pkts]:   Packets / Second
MaxBytes[aggregate-00001-pkts]:  19531250
Directory[aggregate-00001-pkts]: members/1/00001

#####################################################################################################################
#
# aggregate-00001-errs
#

Target[aggregate-00001-errs]:    1.3.6.1.2.1.2.2.1.14#Ethernet1&1.3.6.1.2.1.2.2.1.20#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[aggregate-00001-errs]:     NAPVE -- IXP Total Aggregate -- Errors / second
Options[aggregate-00001-errs]:   growright , pngdate
YLegend[aggregate-00001-errs]:   Errors / Second
MaxBytes[aggregate-00001-errs]:  19531250
Directory[aggregate-00001-errs]: members/1/00001

#####################################################################################################################
#
# aggregate-00001-discs
#

Target[aggregate-00001-discs]:    1.3.6.1.2.1.2.2.1.13#Ethernet1&1.3.6.1.2.1.2.2.1.19#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[aggregate-00001-discs]:     NAPVE -- IXP Total Aggregate -- Discards / second
Options[aggregate-00001-discs]:   growright , pngdate
YLegend[aggregate-00001-discs]:   Discards / Second
MaxBytes[aggregate-00001-discs]:  19531250
Directory[aggregate-00001-discs]: members/1/00001

#####################################################################################################################
#
# aggregate-00001-bcasts
#

Target[aggregate-00001-bcasts]:    1.3.6.1.2.1.31.1.1.1.9#Ethernet1&1.3.6.1.2.1.31.1.1.1.13#Ethernet1:N4PV3SP@10.100.0.3:::::2
Title[aggregate-00001-bcasts]:     NAPVE -- IXP Total Aggregate -- Broadcasts / second
Options[aggregate-00001-bcasts]:   growright , pngdate
YLegend[aggregate-00001-bcasts]:   Broadcasts / Second
MaxBytes[aggregate-00001-bcasts]:  19531250
Directory[aggregate-00001-bcasts]: members/1/00001

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
###
###
###
###
###
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

#####################################################################################################################
#####################################################################################################################
#####################################################################################################################

###
### Generation time: 0.005382 secs

Finally, the graphs dashboard shows this if DB_TYPE=log 
![image](https://github.com/user-attachments/assets/1a653dd1-3d6a-4d38-ba8e-9b6c822a1410)

if DB_TYPE=rrd shows this
![image](https://github.com/user-attachments/assets/c5b6e556-2017-463a-93bb-1f1b2241e38e)

Thanks in advance for your help!

**Comment by nickhilliard** [comment]
hi @cfalconapven, we use github only for bug reports, not support requests.  Can you join the mailing list and ask there instead?  thanks. Hope you're safe in VE right now.

https://www.ixpmanager.org/support/mailing-lists
