### ISSUE TITLE
The masklen must not be greater than 64.

### ISSUE THREAD

**Issue by alphaonex86** [inex/IXP-Manager#902]
##### ISSUE TYPE

Bug Report

##### OS

Linux Ubuntu as recommended

##### VERSION

Version 6.4.1

##### SUMMARY
/network-info/create -> try add IPv6 with prefix /112

##### STEPS TO REPRODUCE
/network-info/create -> try add IPv6 with prefix /112

##### EXPECTED RESULTS
Allowed

##### ACTUAL RESULTS
The masklen must not be greater than 64.

##### IMPORTANCE
for this I use /112 prefix

**Comment by nickhilliard** [comment]
For statically assigned ipv6 networks, there isn't an issue using any mask you want.

/64 only applies to SLAAC, and even then only in cases where the ipv6 network stack has not implemented the prefix length parameter specified in section 4.6.2 of RFC4861. 

See [draft-bourbaki-6man-classless-ipv6](https://datatracker.ietf.org/doc/draft-bourbaki-6man-classless-ipv6/) section 5 for more discussion on this.

**Comment by alphaonex86** [comment]
We use statically assigned ipv6 networks.
I planned use IXP manager to manage the IPv6 assignment, but for this limitation I will continue doing it into text file, it's not a problem? I will use IPv6 into my IXP.
I have not finished implement the route server yet, I'm on this.
