### ISSUE TITLE
VLAN into IXPmanager is informational?

### ISSUE THREAD

**Issue by alphaonex86** [inex/IXP-Manager#904]
**NB: Do not create an issue for requests for help.**

Sorry but I have poor English and the doc is not clear for this point:
I need setup manually the VLAN for each member port and register it into IXPmanager as informacional?
Then IXPmanger not change switch configuration nor get VLAN from port access, right?

**Comment by nickhilliard** [comment]
Hi @alphaonex86, we use github only for bug reports, not support requests. Can you join the mailing list and ask there instead? thanks.

nous utilisons github uniquement pour les rapports de bugs, pas pour les demandes d'assistance. Pouvez-vous rejoindre le mailing list «ixpmanager» et poser vos questions là-bas? Merci.

https://www.ixpmanager.org/support/mailing-lists
https://www.inex.ie/mailman/listinfo/ixpmanager
