### ISSUE TITLE
Sflow support for multiple VLAN Interfaces from the same ASN on the same VLAN

### ISSUE THREAD

**Issue by bcix** [inex/IXP-Manager#99]
Hey again,

it looks like that IXP Manager sflow integration does not support the setting
when one ASN has multiple Ports with multiple IP Interfaces (or multiple VLAN Interfaces in IXP Manager language) in the same Peering VLAN.

Hope this will be supported in a future release.

Regards, Thorleif

**Comment by nickhilliard** [comment]
fixed ages ago
